# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: llmhubs/rpc.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "BuiltinModelEntry",
    "ListBuiltinModelsRequest",
    "ListBuiltinModelsResponse",
    "LlmHubRpcBase",
    "LlmHubRpcStub",
    "RuntimeArtifact",
    "RuntimeGenerateRequest",
    "RuntimeGenerateResponse",
    "RuntimeInput",
    "RuntimeInputContent",
    "RuntimeModelDefinition",
    "RuntimeOutputItem",
    "RuntimeStreamChunk",
    "RuntimeTrace",
    "RuntimeUsage",
)

from collections.abc import AsyncIterator, Iterator
from dataclasses import dataclass
from typing import TYPE_CHECKING

import betterproto2
import grpc
import grpclib
from betterproto2 import grpclib as betterproto2_grpclib

from ..message_pool import default_message_pool

if TYPE_CHECKING:
    import grpclib.server

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class BuiltinModelEntry(betterproto2.Message):
    model_key: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    display_name: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    description: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    icon_uri: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)

    model_type: "int" = betterproto2.field(5, betterproto2.TYPE_INT32)

    provider_template_type: "int" = betterproto2.field(6, betterproto2.TYPE_INT32)


default_message_pool.register_message("llmhubs", "BuiltinModelEntry", BuiltinModelEntry)


@dataclass(eq=False, repr=False)
class ListBuiltinModelsRequest(betterproto2.Message):
    pass


default_message_pool.register_message(
    "llmhubs", "ListBuiltinModelsRequest", ListBuiltinModelsRequest
)


@dataclass(eq=False, repr=False)
class ListBuiltinModelsResponse(betterproto2.Message):
    models: "list[BuiltinModelEntry]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )

    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)

    msg: "str" = betterproto2.field(254, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "llmhubs", "ListBuiltinModelsResponse", ListBuiltinModelsResponse
)


@dataclass(eq=False, repr=False)
class RuntimeArtifact(betterproto2.Message):
    artifact_type: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    mime_type: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    filename: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    storage_uri: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)

    download_url: "str" = betterproto2.field(5, betterproto2.TYPE_STRING)


default_message_pool.register_message("llmhubs", "RuntimeArtifact", RuntimeArtifact)


@dataclass(eq=False, repr=False)
class RuntimeGenerateRequest(betterproto2.Message):
    model: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    instructions: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    inputs: "list[RuntimeInput]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, repeated=True
    )

    options: "_google__protobuf__.Struct | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )

    tools: "list[_google__protobuf__.Struct]" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, repeated=True
    )

    model_definition: "RuntimeModelDefinition | None" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, optional=True
    )

    previous_response_id: "str" = betterproto2.field(8, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "llmhubs", "RuntimeGenerateRequest", RuntimeGenerateRequest
)


@dataclass(eq=False, repr=False)
class RuntimeGenerateResponse(betterproto2.Message):
    outputs: "list[RuntimeOutputItem]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )

    artifacts: "list[RuntimeArtifact]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )

    payload: "_google__protobuf__.Struct | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )

    usage: "RuntimeUsage | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )

    trace: "RuntimeTrace | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True
    )

    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)

    msg: "str" = betterproto2.field(254, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "llmhubs", "RuntimeGenerateResponse", RuntimeGenerateResponse
)


@dataclass(eq=False, repr=False)
class RuntimeInput(betterproto2.Message):
    role: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    content: "list[RuntimeInputContent]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("llmhubs", "RuntimeInput", RuntimeInput)


@dataclass(eq=False, repr=False)
class RuntimeInputContent(betterproto2.Message):
    type: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    text: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    image_base64: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    file_url: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)

    file_base64: "str" = betterproto2.field(5, betterproto2.TYPE_STRING)

    call_id: "str" = betterproto2.field(6, betterproto2.TYPE_STRING)

    name: "str" = betterproto2.field(7, betterproto2.TYPE_STRING)

    arguments: "str" = betterproto2.field(8, betterproto2.TYPE_STRING)

    output: "_google__protobuf__.Struct | None" = betterproto2.field(
        9, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    computer_call_output nested data
    """

    image_url: "str" = betterproto2.field(10, betterproto2.TYPE_STRING)

    media_type: "str" = betterproto2.field(11, betterproto2.TYPE_STRING)

    result: "str" = betterproto2.field(12, betterproto2.TYPE_STRING)
    """
    function_result serialized value
    """

    actions: "list[_google__protobuf__.Struct]" = betterproto2.field(
        13, betterproto2.TYPE_MESSAGE, repeated=True
    )
    """
    computer_call actions for history replay
    """

    detail: "str" = betterproto2.field(14, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "llmhubs", "RuntimeInputContent", RuntimeInputContent
)


@dataclass(eq=False, repr=False)
class RuntimeModelDefinition(betterproto2.Message):
    model_key: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    display_name: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    model_type: "int" = betterproto2.field(3, betterproto2.TYPE_INT32)

    provider_template_type: "int" = betterproto2.field(4, betterproto2.TYPE_INT32)

    status: "int" = betterproto2.field(5, betterproto2.TYPE_INT32)

    config: "_google__protobuf__.Struct | None" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, optional=True
    )

    secrets: "dict[str, str]" = betterproto2.field(
        8,
        betterproto2.TYPE_MAP,
        map_meta=betterproto2.map_meta(
            betterproto2.TYPE_STRING, betterproto2.TYPE_STRING
        ),
    )


default_message_pool.register_message(
    "llmhubs", "RuntimeModelDefinition", RuntimeModelDefinition
)


@dataclass(eq=False, repr=False)
class RuntimeOutputItem(betterproto2.Message):
    type: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    text: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    json: "_google__protobuf__.Struct | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )

    call_id: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)

    name: "str" = betterproto2.field(5, betterproto2.TYPE_STRING)

    arguments: "str" = betterproto2.field(6, betterproto2.TYPE_STRING)

    actions: "list[_google__protobuf__.Struct]" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, repeated=True
    )
    """
    computer_call actions
    """


default_message_pool.register_message("llmhubs", "RuntimeOutputItem", RuntimeOutputItem)


@dataclass(eq=False, repr=False)
class RuntimeStreamChunk(betterproto2.Message):
    """
    RuntimeStreamChunk represents a single incremental piece of a streaming response.
    """

    delta: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    """
    incremental text fragment
    """

    outputs: "list[RuntimeOutputItem]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )
    """
    structured outputs (tool calls, etc.)
    """

    finish_reason: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    """
    "stop", "tool_use", "error", or empty
    """

    usage: "RuntimeUsage | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    final usage stats (sent on last chunk)
    """

    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)
    """
    non-zero signals error
    """

    msg: "str" = betterproto2.field(254, betterproto2.TYPE_STRING)
    """
    error message
    """


default_message_pool.register_message(
    "llmhubs", "RuntimeStreamChunk", RuntimeStreamChunk
)


@dataclass(eq=False, repr=False)
class RuntimeTrace(betterproto2.Message):
    provider_template_type: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)

    model: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    latency_ms: "int" = betterproto2.field(3, betterproto2.TYPE_INT64)


default_message_pool.register_message("llmhubs", "RuntimeTrace", RuntimeTrace)


@dataclass(eq=False, repr=False)
class RuntimeUsage(betterproto2.Message):
    prompt_tokens: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)

    completion_tokens: "int" = betterproto2.field(2, betterproto2.TYPE_INT64)

    total_tokens: "int" = betterproto2.field(3, betterproto2.TYPE_INT64)


default_message_pool.register_message("llmhubs", "RuntimeUsage", RuntimeUsage)


class LlmHubRpcStub:
    """
    LLMHubRPC exposes LLMHub runtime operations over gRPC (Backend → Core).
    """

    def __init__(self, channel: grpc.Channel):
        self._channel = channel

    def runtime_generate(
        self, message: "RuntimeGenerateRequest"
    ) -> "RuntimeGenerateResponse":
        return self._channel.unary_unary(
            "/llmhubs.LLMHubRPC/RuntimeGenerate",
            RuntimeGenerateRequest.SerializeToString,
            RuntimeGenerateResponse.FromString,
        )(message)

    def runtime_generate_stream(
        self, message: "RuntimeGenerateRequest"
    ) -> "Iterator[RuntimeStreamChunk]":
        yield from self._channel.unary_stream(
            "/llmhubs.LLMHubRPC/RuntimeGenerateStream",
            RuntimeGenerateRequest.SerializeToString,
            RuntimeStreamChunk.FromString,
        )(message)

    def list_builtin_models(
        self, message: "ListBuiltinModelsRequest | None" = None
    ) -> "ListBuiltinModelsResponse":
        if message is None:
            message = ListBuiltinModelsRequest()

        return self._channel.unary_unary(
            "/llmhubs.LLMHubRPC/ListBuiltinModels",
            ListBuiltinModelsRequest.SerializeToString,
            ListBuiltinModelsResponse.FromString,
        )(message)


from ..google import protobuf as _google__protobuf__


class LlmHubRpcBase(betterproto2_grpclib.ServiceBase):
    """
    LLMHubRPC exposes LLMHub runtime operations over gRPC (Backend → Core).
    """

    async def runtime_generate(
        self, message: "RuntimeGenerateRequest"
    ) -> "RuntimeGenerateResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def runtime_generate_stream(
        self, message: "RuntimeGenerateRequest"
    ) -> "AsyncIterator[RuntimeStreamChunk]":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
        yield RuntimeStreamChunk()

    async def list_builtin_models(
        self, message: "ListBuiltinModelsRequest"
    ) -> "ListBuiltinModelsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_runtime_generate(
        self,
        stream: "grpclib.server.Stream[RuntimeGenerateRequest, RuntimeGenerateResponse]",
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.runtime_generate(request)
        await stream.send_message(response)

    async def __rpc_runtime_generate_stream(
        self,
        stream: "grpclib.server.Stream[RuntimeGenerateRequest, RuntimeStreamChunk]",
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        await self._call_rpc_handler_server_stream(
            self.runtime_generate_stream,
            stream,
            request,
        )

    async def __rpc_list_builtin_models(
        self,
        stream: "grpclib.server.Stream[ListBuiltinModelsRequest, ListBuiltinModelsResponse]",
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.list_builtin_models(request)
        await stream.send_message(response)

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/llmhubs.LLMHubRPC/RuntimeGenerate": grpclib.const.Handler(
                self.__rpc_runtime_generate,
                grpclib.const.Cardinality.UNARY_UNARY,
                RuntimeGenerateRequest,
                RuntimeGenerateResponse,
            ),
            "/llmhubs.LLMHubRPC/RuntimeGenerateStream": grpclib.const.Handler(
                self.__rpc_runtime_generate_stream,
                grpclib.const.Cardinality.UNARY_STREAM,
                RuntimeGenerateRequest,
                RuntimeStreamChunk,
            ),
            "/llmhubs.LLMHubRPC/ListBuiltinModels": grpclib.const.Handler(
                self.__rpc_list_builtin_models,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListBuiltinModelsRequest,
                ListBuiltinModelsResponse,
            ),
        }
