// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"sico-backend/internal/store/skill/internal/dal/model"
)

func newTSkillVersion(db *gorm.DB, opts ...gen.DOOption) tSkillVersion {
	_tSkillVersion := tSkillVersion{}

	_tSkillVersion.tSkillVersionDo.UseDB(db, opts...)
	_tSkillVersion.tSkillVersionDo.UseModel(&model.TSkillVersion{})

	tableName := _tSkillVersion.tSkillVersionDo.TableName()
	_tSkillVersion.ALL = field.NewAsterisk(tableName)
	_tSkillVersion.ID = field.NewInt64(tableName, "id")
	_tSkillVersion.SkillID = field.NewInt64(tableName, "skill_id")
	_tSkillVersion.Version = field.NewString(tableName, "version")
	_tSkillVersion.AssetID = field.NewInt64(tableName, "asset_id")
	_tSkillVersion.Name = field.NewString(tableName, "name")
	_tSkillVersion.Description = field.NewString(tableName, "description")
	_tSkillVersion.CreatorUsername = field.NewString(tableName, "creator_username")
	_tSkillVersion.Status = field.NewInt32(tableName, "status")
	_tSkillVersion.FailReason = field.NewString(tableName, "fail_reason")
	_tSkillVersion.CreatedAt = field.NewInt64(tableName, "created_at")
	_tSkillVersion.UpdatedAt = field.NewInt64(tableName, "updated_at")
	_tSkillVersion.DeletedAt = field.NewField(tableName, "deleted_at")

	_tSkillVersion.fillFieldMap()

	return _tSkillVersion
}

// tSkillVersion Skill immutable version table
type tSkillVersion struct {
	tSkillVersionDo

	ALL             field.Asterisk
	ID              field.Int64  // Primary key
	SkillID         field.Int64  // Skill ID
	Version         field.String // Timestamp version string
	AssetID         field.Int64  // Associated project asset ID
	Name            field.String // Skill version name
	Description     field.String // Skill version description
	CreatorUsername field.String // Version creator username
	Status          field.Int32  // Skill version status: 0-UNKNOWN,1-UPLOADING,2-UPLOADED,3-FAILED
	FailReason      field.String // Failure reason if resolver failed
	CreatedAt       field.Int64  // Create Time in Milliseconds
	UpdatedAt       field.Int64  // Update Time in Milliseconds
	DeletedAt       field.Field  // Delete Time

	fieldMap map[string]field.Expr
}

func (t tSkillVersion) Table(newTableName string) *tSkillVersion {
	t.tSkillVersionDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tSkillVersion) As(alias string) *tSkillVersion {
	t.tSkillVersionDo.DO = *(t.tSkillVersionDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tSkillVersion) updateTableName(table string) *tSkillVersion {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.SkillID = field.NewInt64(table, "skill_id")
	t.Version = field.NewString(table, "version")
	t.AssetID = field.NewInt64(table, "asset_id")
	t.Name = field.NewString(table, "name")
	t.Description = field.NewString(table, "description")
	t.CreatorUsername = field.NewString(table, "creator_username")
	t.Status = field.NewInt32(table, "status")
	t.FailReason = field.NewString(table, "fail_reason")
	t.CreatedAt = field.NewInt64(table, "created_at")
	t.UpdatedAt = field.NewInt64(table, "updated_at")
	t.DeletedAt = field.NewField(table, "deleted_at")

	t.fillFieldMap()

	return t
}

func (t *tSkillVersion) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tSkillVersion) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 12)
	t.fieldMap["id"] = t.ID
	t.fieldMap["skill_id"] = t.SkillID
	t.fieldMap["version"] = t.Version
	t.fieldMap["asset_id"] = t.AssetID
	t.fieldMap["name"] = t.Name
	t.fieldMap["description"] = t.Description
	t.fieldMap["creator_username"] = t.CreatorUsername
	t.fieldMap["status"] = t.Status
	t.fieldMap["fail_reason"] = t.FailReason
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["deleted_at"] = t.DeletedAt
}

func (t tSkillVersion) clone(db *gorm.DB) tSkillVersion {
	t.tSkillVersionDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tSkillVersion) replaceDB(db *gorm.DB) tSkillVersion {
	t.tSkillVersionDo.ReplaceDB(db)
	return t
}

type tSkillVersionDo struct{ gen.DO }

type ITSkillVersionDo interface {
	gen.SubQuery
	Debug() ITSkillVersionDo
	WithContext(ctx context.Context) ITSkillVersionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITSkillVersionDo
	WriteDB() ITSkillVersionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITSkillVersionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITSkillVersionDo
	Not(conds ...gen.Condition) ITSkillVersionDo
	Or(conds ...gen.Condition) ITSkillVersionDo
	Select(conds ...field.Expr) ITSkillVersionDo
	Where(conds ...gen.Condition) ITSkillVersionDo
	Order(conds ...field.Expr) ITSkillVersionDo
	Distinct(cols ...field.Expr) ITSkillVersionDo
	Omit(cols ...field.Expr) ITSkillVersionDo
	Join(table schema.Tabler, on ...field.Expr) ITSkillVersionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITSkillVersionDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITSkillVersionDo
	Group(cols ...field.Expr) ITSkillVersionDo
	Having(conds ...gen.Condition) ITSkillVersionDo
	Limit(limit int) ITSkillVersionDo
	Offset(offset int) ITSkillVersionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITSkillVersionDo
	Unscoped() ITSkillVersionDo
	Create(values ...*model.TSkillVersion) error
	CreateInBatches(values []*model.TSkillVersion, batchSize int) error
	Save(values ...*model.TSkillVersion) error
	First() (*model.TSkillVersion, error)
	Take() (*model.TSkillVersion, error)
	Last() (*model.TSkillVersion, error)
	Find() ([]*model.TSkillVersion, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TSkillVersion, err error)
	FindInBatches(result *[]*model.TSkillVersion, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TSkillVersion) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITSkillVersionDo
	Assign(attrs ...field.AssignExpr) ITSkillVersionDo
	Joins(fields ...field.RelationField) ITSkillVersionDo
	Preload(fields ...field.RelationField) ITSkillVersionDo
	FirstOrInit() (*model.TSkillVersion, error)
	FirstOrCreate() (*model.TSkillVersion, error)
	FindByPage(offset int, limit int) (result []*model.TSkillVersion, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITSkillVersionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tSkillVersionDo) Debug() ITSkillVersionDo {
	return t.withDO(t.DO.Debug())
}

func (t tSkillVersionDo) WithContext(ctx context.Context) ITSkillVersionDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tSkillVersionDo) ReadDB() ITSkillVersionDo {
	return t.Clauses(dbresolver.Read)
}

func (t tSkillVersionDo) WriteDB() ITSkillVersionDo {
	return t.Clauses(dbresolver.Write)
}

func (t tSkillVersionDo) Session(config *gorm.Session) ITSkillVersionDo {
	return t.withDO(t.DO.Session(config))
}

func (t tSkillVersionDo) Clauses(conds ...clause.Expression) ITSkillVersionDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tSkillVersionDo) Returning(value interface{}, columns ...string) ITSkillVersionDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tSkillVersionDo) Not(conds ...gen.Condition) ITSkillVersionDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tSkillVersionDo) Or(conds ...gen.Condition) ITSkillVersionDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tSkillVersionDo) Select(conds ...field.Expr) ITSkillVersionDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tSkillVersionDo) Where(conds ...gen.Condition) ITSkillVersionDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tSkillVersionDo) Order(conds ...field.Expr) ITSkillVersionDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tSkillVersionDo) Distinct(cols ...field.Expr) ITSkillVersionDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tSkillVersionDo) Omit(cols ...field.Expr) ITSkillVersionDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tSkillVersionDo) Join(table schema.Tabler, on ...field.Expr) ITSkillVersionDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tSkillVersionDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITSkillVersionDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tSkillVersionDo) RightJoin(table schema.Tabler, on ...field.Expr) ITSkillVersionDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tSkillVersionDo) Group(cols ...field.Expr) ITSkillVersionDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tSkillVersionDo) Having(conds ...gen.Condition) ITSkillVersionDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tSkillVersionDo) Limit(limit int) ITSkillVersionDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tSkillVersionDo) Offset(offset int) ITSkillVersionDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tSkillVersionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITSkillVersionDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tSkillVersionDo) Unscoped() ITSkillVersionDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tSkillVersionDo) Create(values ...*model.TSkillVersion) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tSkillVersionDo) CreateInBatches(values []*model.TSkillVersion, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tSkillVersionDo) Save(values ...*model.TSkillVersion) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tSkillVersionDo) First() (*model.TSkillVersion, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TSkillVersion), nil
	}
}

func (t tSkillVersionDo) Take() (*model.TSkillVersion, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TSkillVersion), nil
	}
}

func (t tSkillVersionDo) Last() (*model.TSkillVersion, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TSkillVersion), nil
	}
}

func (t tSkillVersionDo) Find() ([]*model.TSkillVersion, error) {
	result, err := t.DO.Find()
	return result.([]*model.TSkillVersion), err
}

func (t tSkillVersionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TSkillVersion, err error) {
	buf := make([]*model.TSkillVersion, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tSkillVersionDo) FindInBatches(result *[]*model.TSkillVersion, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tSkillVersionDo) Attrs(attrs ...field.AssignExpr) ITSkillVersionDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tSkillVersionDo) Assign(attrs ...field.AssignExpr) ITSkillVersionDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tSkillVersionDo) Joins(fields ...field.RelationField) ITSkillVersionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tSkillVersionDo) Preload(fields ...field.RelationField) ITSkillVersionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tSkillVersionDo) FirstOrInit() (*model.TSkillVersion, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TSkillVersion), nil
	}
}

func (t tSkillVersionDo) FirstOrCreate() (*model.TSkillVersion, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TSkillVersion), nil
	}
}

func (t tSkillVersionDo) FindByPage(offset int, limit int) (result []*model.TSkillVersion, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tSkillVersionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tSkillVersionDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tSkillVersionDo) Delete(models ...*model.TSkillVersion) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tSkillVersionDo) withDO(do gen.Dao) *tSkillVersionDo {
	t.DO = *do.(*gen.DO)
	return t
}
