// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"sico-backend/internal/biz/agent"
	impl4 "sico-backend/internal/biz/agent/impl"
	"sico-backend/internal/biz/conversation"
	impl5 "sico-backend/internal/biz/conversation/impl"
	"sico-backend/internal/biz/knowledge"
	impl3 "sico-backend/internal/biz/knowledge/impl"
	"sico-backend/internal/biz/llmhubs"
	"sico-backend/internal/biz/project"
	"sico-backend/internal/biz/project/impl"
	"sico-backend/internal/biz/rbac"
	impl2 "sico-backend/internal/biz/rbac/impl"
	"sico-backend/internal/biz/sandbox"
	impl6 "sico-backend/internal/biz/sandbox/impl"
	"sico-backend/internal/biz/skill"
	impl7 "sico-backend/internal/biz/skill/impl"
	"sico-backend/internal/biz/taskruntime"
	impl8 "sico-backend/internal/biz/taskruntime/impl"
	"sico-backend/internal/di/infra"
	repository4 "sico-backend/internal/store/agent/singleagent/repository"
	repository5 "sico-backend/internal/store/conversation/conversation/repository"
	repository6 "sico-backend/internal/store/conversation/message/repository"
	repository3 "sico-backend/internal/store/knowledge/repository"
	repository8 "sico-backend/internal/store/llmhubs/repository"
	"sico-backend/internal/store/project/repository"
	"sico-backend/internal/store/rbac/enforcer"
	repository2 "sico-backend/internal/store/rbac/repository"
	repository7 "sico-backend/internal/store/skill/repository"
	repository9 "sico-backend/internal/store/taskruntime/repository"
)

// Injectors from wire.go:

func BuildInjector(ctx context.Context) (*Injector, func(), error) {
	db, cleanup, err := infra.ProvideDB(ctx)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := infra.ProvideRedisClient()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	idGenerator, err := infra.ProvideIDGenerator(client)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	storage, err := infra.ProvideBlobStorage(ctx)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	clientConn, err := infra.ProvideCoreGRPCConnection()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	projectRepository := repository.NewProjectRepo(db)
	components := &impl.Components{
		ProjectRepo: projectRepository,
		IDGen:       idGenerator,
		BlobClient:  storage,
	}
	service := project.InitService(components)
	userRepository := repository2.NewUserRepository(db)
	roleRepository := repository2.NewRoleRepository(db)
	userRoleRepository := repository2.NewUserRoleRepository(db)
	casbinRuleRepository := repository2.NewCasbinRuleRepository(db)
	casbinEnforcer, err := enforcer.ProvideCasbinEnforcer(db)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	implComponents := &impl2.Components{
		UserRepo:     userRepository,
		RoleRepo:     roleRepository,
		UserRoleRepo: userRoleRepository,
		CasbinRepo:   casbinRuleRepository,
		Enforcer:     casbinEnforcer,
	}
	rbacService := rbac.InitService(implComponents, client)
	documentRepository := repository3.NewDocumentRepo(db)
	knowledgeTagRepository := repository3.NewKnowledgeTagRepo(db)
	documentTagRepository := repository3.NewDocumentTagRepo(db)
	playbookRepository := repository3.NewPlaybookRepo(db)
	playbookTagRepository := repository3.NewPlaybookTagRepo(db)
	singleAgentInstanceRepository := repository4.NewSingleAgentInstanceRepo(db)
	components2 := &impl3.Components{
		DocumentRepo:      documentRepository,
		KnowledgeTagRepo:  knowledgeTagRepository,
		DocumentTagRepo:   documentTagRepository,
		PlaybookRepo:      playbookRepository,
		PlaybookTagRepo:   playbookTagRepository,
		ProjectRepo:       projectRepository,
		AgentInstanceRepo: singleAgentInstanceRepository,
		Storage:           storage,
		CoreGRPC:          clientConn,
	}
	knowledgeService := knowledge.InitService(components2)
	singleAgentRepository := repository4.NewSingleAgentRepo(db)
	singleAgentLLMHubConfigRepository := repository4.NewSingleAgentLLMHubConfigRepo(db)
	components3 := &impl4.Components{
		SingleAgentRepo:             singleAgentRepository,
		SingleAgentLLMHubConfigRepo: singleAgentLLMHubConfigRepository,
		SingleAgentInstanceRepo:     singleAgentInstanceRepository,
		ProjectRepo:                 projectRepository,
		Storage:                     storage,
	}
	implService := impl4.NewService(components3, db)
	agentService := agent.InitService(implService)
	conversationRepo := repository5.NewConversationRepo(db, idGenerator)
	messageRepo := repository6.NewMessageRepo(db)
	components4 := &impl5.Components{
		ConversationRepo: conversationRepo,
		MessageRepo:      messageRepo,
		AgentService:     agentService,
		ProjectService:   service,
		IDGenerator:      idGenerator,
		Storage:          storage,
		CoreGRPC:         clientConn,
		Cache:            client,
		DB:               db,
	}
	conversationService := conversation.InitService(components4)
	emulatorProvider := impl6.NewEmulatorProvider()
	pool := impl6.NewPool(emulatorProvider, client)
	cron, cleanup3, err := infra.ProvideCron()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	service2 := impl6.NewService(pool, singleAgentInstanceRepository, cron)
	sandboxService := sandbox.InitService(service2)
	skillRepository := repository7.NewSkillRepo(db)
	components5 := &impl7.Components{
		SkillRepo:   skillRepository,
		ProjectRepo: projectRepository,
		CoreGRPC:    clientConn,
	}
	skillService := skill.InitService(components5)
	modelRegistryRepository := repository8.NewModelRegistryRepo(db)
	modelRegistrySecretRepository := repository8.NewModelRegistrySecretRepo(db)
	llmhubsService := llmhubs.InitService(db, clientConn, modelRegistryRepository, modelRegistrySecretRepository, singleAgentLLMHubConfigRepository)
	taskRuntimeRepository := repository9.NewTaskRuntimeRepo(db)
	service3 := impl8.NewService(taskRuntimeRepository)
	taskruntimeService := taskruntime.InitService(service3)
	injector := &Injector{
		DB:              db,
		Cache:           client,
		IDGen:           idGenerator,
		Storage:         storage,
		CoreGRPC:        clientConn,
		ProjectApp:      service,
		RBACApp:         rbacService,
		KnowledgeApp:    knowledgeService,
		AgentApp:        agentService,
		ConversationApp: conversationService,
		SandboxApp:      sandboxService,
		SkillApp:        skillService,
		LLMHubApp:       llmhubsService,
		TaskRuntimeApp:  taskruntimeService,
	}
	return injector, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
