// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"sico-backend/internal/biz/agent"
	impl5 "sico-backend/internal/biz/agent/impl"
	"sico-backend/internal/biz/conversation"
	impl6 "sico-backend/internal/biz/conversation/impl"
	"sico-backend/internal/biz/knowledge"
	impl4 "sico-backend/internal/biz/knowledge/impl"
	"sico-backend/internal/biz/llmhubs"
	"sico-backend/internal/biz/organization"
	impl3 "sico-backend/internal/biz/organization/impl"
	"sico-backend/internal/biz/project"
	"sico-backend/internal/biz/project/impl"
	"sico-backend/internal/biz/rbac"
	impl2 "sico-backend/internal/biz/rbac/impl"
	"sico-backend/internal/biz/sandbox"
	impl7 "sico-backend/internal/biz/sandbox/impl"
	"sico-backend/internal/biz/skill"
	impl8 "sico-backend/internal/biz/skill/impl"
	"sico-backend/internal/biz/taskruntime"
	impl9 "sico-backend/internal/biz/taskruntime/impl"
	"sico-backend/internal/di/infra"
	repository2 "sico-backend/internal/store/agent/singleagent/repository"
	repository6 "sico-backend/internal/store/conversation/conversation/repository"
	repository7 "sico-backend/internal/store/conversation/message/repository"
	repository5 "sico-backend/internal/store/knowledge/repository"
	repository9 "sico-backend/internal/store/llmhubs/repository"
	repository4 "sico-backend/internal/store/organization/repository"
	"sico-backend/internal/store/project/repository"
	"sico-backend/internal/store/rbac/enforcer"
	repository3 "sico-backend/internal/store/rbac/repository"
	repository8 "sico-backend/internal/store/skill/repository"
	repository10 "sico-backend/internal/store/taskruntime/repository"
)

// Injectors from wire.go:

func BuildInjector(ctx context.Context) (*Injector, func(), error) {
	db, cleanup, err := infra.ProvideDB(ctx)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := infra.ProvideRedisClient()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	idGenerator, err := infra.ProvideIDGenerator(client)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	storage, err := infra.ProvideBlobStorage(ctx)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	v, err := infra.ProvideCoreGRPCConnection()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	projectRepository := repository.NewProjectRepo(db)
	singleAgentInstanceRepository := repository2.NewSingleAgentInstanceRepo(db)
	components := &impl.Components{
		ProjectRepo:       projectRepository,
		IDGen:             idGenerator,
		BlobClient:        storage,
		AgentInstanceRepo: singleAgentInstanceRepository,
	}
	service := project.InitService(components)
	userRepository := repository3.NewUserRepository(db)
	userRoleRepository := repository3.NewUserRoleRepository(db)
	casbinRuleRepository := repository3.NewCasbinRuleRepository(db)
	casbinEnforcer, err := enforcer.ProvideCasbinEnforcer(db, client)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	implComponents := &impl2.Components{
		UserRepo:     userRepository,
		UserRoleRepo: userRoleRepository,
		CasbinRepo:   casbinRuleRepository,
		Enforcer:     casbinEnforcer,
		Redis:        client,
	}
	rbacService := rbac.InitService(implComponents, client)
	organizationRepository := repository4.NewOrganizationRepository(db)
	components2 := &impl3.Components{
		OrgRepo: organizationRepository,
	}
	organizationService := organization.InitService(components2)
	documentRepository := repository5.NewDocumentRepo(db)
	knowledgeTagRepository := repository5.NewKnowledgeTagRepo(db)
	documentTagRepository := repository5.NewDocumentTagRepo(db)
	playbookRepository := repository5.NewPlaybookRepo(db)
	playbookTagRepository := repository5.NewPlaybookTagRepo(db)
	components3 := &impl4.Components{
		DocumentRepo:      documentRepository,
		KnowledgeTagRepo:  knowledgeTagRepository,
		DocumentTagRepo:   documentTagRepository,
		PlaybookRepo:      playbookRepository,
		PlaybookTagRepo:   playbookTagRepository,
		ProjectRepo:       projectRepository,
		AgentInstanceRepo: singleAgentInstanceRepository,
		Storage:           storage,
		CoreGRPC:          v,
	}
	knowledgeService := knowledge.InitService(components3)
	singleAgentRepository := repository2.NewSingleAgentRepo(db)
	singleAgentLLMHubConfigRepository := repository2.NewSingleAgentLLMHubConfigRepo(db)
	components4 := &impl5.Components{
		SingleAgentRepo:             singleAgentRepository,
		SingleAgentLLMHubConfigRepo: singleAgentLLMHubConfigRepository,
		SingleAgentInstanceRepo:     singleAgentInstanceRepository,
		ProjectRepo:                 projectRepository,
		Storage:                     storage,
	}
	implService := impl5.NewService(components4, db)
	agentService := agent.InitService(implService)
	conversationRepo := repository6.NewConversationRepo(db, idGenerator)
	messageRepo := repository7.NewMessageRepo(db)
	components5 := &impl6.Components{
		ConversationRepo: conversationRepo,
		MessageRepo:      messageRepo,
		AgentService:     agentService,
		ProjectService:   service,
		IDGenerator:      idGenerator,
		Storage:          storage,
		CoreGRPC:         v,
		Cache:            client,
		DB:               db,
	}
	conversationService := conversation.InitService(components5)
	emulatorProvider := impl7.NewEmulatorProvider()
	pool := impl7.NewPool(emulatorProvider, client)
	cron, cleanup3, err := infra.ProvideCron()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	service2 := impl7.NewService(pool, singleAgentInstanceRepository, cron)
	sandboxService := sandbox.InitService(service2)
	skillRepository := repository8.NewSkillRepo(db)
	components6 := &impl8.Components{
		SkillRepo:   skillRepository,
		ProjectRepo: projectRepository,
		CoreGRPC:    v,
	}
	skillService := skill.InitService(components6)
	modelRegistryRepository := repository9.NewModelRegistryRepo(db)
	modelRegistrySecretRepository := repository9.NewModelRegistrySecretRepo(db)
	llmhubsService := llmhubs.InitService(db, v, modelRegistryRepository, modelRegistrySecretRepository, singleAgentLLMHubConfigRepository)
	taskRuntimeRepository := repository10.NewTaskRuntimeRepo(db)
	service3 := impl9.NewService(taskRuntimeRepository)
	taskruntimeService := taskruntime.InitService(service3)
	injector := &Injector{
		DB:              db,
		Cache:           client,
		IDGen:           idGenerator,
		Storage:         storage,
		CoreGRPC:        v,
		ProjectApp:      service,
		RBACApp:         rbacService,
		OrganizationApp: organizationService,
		KnowledgeApp:    knowledgeService,
		AgentApp:        agentService,
		ConversationApp: conversationService,
		SandboxApp:      sandboxService,
		SkillApp:        skillService,
		LLMHubApp:       llmhubsService,
		TaskRuntimeApp:  taskruntimeService,
	}
	return injector, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
