// Code generated by otelwrapgen; DO NOT EDIT.
package casereplay

import (
	"context"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
	reverse_rpc "sico-backend/internal/transport/reverse_grpc/pb/casereplay"
)

func WithTracing(next Service) Service {
	if next == nil {
		return nil
	}
	return &otelTracedService{next: next}
}

type otelTracedService struct {
	reverse_rpc.UnimplementedReverseCaseReplayRPCServer
	next Service
}

func (w *otelTracedService) Unwrap() Service {
	return w.next
}

func (w *otelTracedService) RpcActivateCaseReplayVersion(arg0 context.Context, arg1 *reverse_rpc.ActivateCaseReplayVersionRequest) (*reverse_rpc.EmptyCaseReplayResponse, error) {
	arg0, span := otel.Tracer("sico-backend/otelwrap").Start(arg0, "Service.RpcActivateCaseReplayVersion")
	defer span.End()

	ret0, ret1 := w.next.RpcActivateCaseReplayVersion(arg0, arg1)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) RpcCreateCaseReplayVersion(arg0 context.Context, arg1 *reverse_rpc.CreateCaseReplayVersionRequest) (*reverse_rpc.CreateCaseReplayVersionResponse, error) {
	arg0, span := otel.Tracer("sico-backend/otelwrap").Start(arg0, "Service.RpcCreateCaseReplayVersion")
	defer span.End()

	ret0, ret1 := w.next.RpcCreateCaseReplayVersion(arg0, arg1)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) RpcGetActiveCaseReplay(arg0 context.Context, arg1 *reverse_rpc.GetActiveCaseReplayRequest) (*reverse_rpc.GetActiveCaseReplayResponse, error) {
	arg0, span := otel.Tracer("sico-backend/otelwrap").Start(arg0, "Service.RpcGetActiveCaseReplay")
	defer span.End()

	ret0, ret1 := w.next.RpcGetActiveCaseReplay(arg0, arg1)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) RpcGetOrCreateCaseReplay(arg0 context.Context, arg1 *reverse_rpc.GetOrCreateCaseReplayRequest) (*reverse_rpc.GetOrCreateCaseReplayResponse, error) {
	arg0, span := otel.Tracer("sico-backend/otelwrap").Start(arg0, "Service.RpcGetOrCreateCaseReplay")
	defer span.End()

	ret0, ret1 := w.next.RpcGetOrCreateCaseReplay(arg0, arg1)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) RpcMarkCaseReplayStale(arg0 context.Context, arg1 *reverse_rpc.MarkCaseReplayStaleRequest) (*reverse_rpc.EmptyCaseReplayResponse, error) {
	arg0, span := otel.Tracer("sico-backend/otelwrap").Start(arg0, "Service.RpcMarkCaseReplayStale")
	defer span.End()

	ret0, ret1 := w.next.RpcMarkCaseReplayStale(arg0, arg1)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) RpcSetCaseReplayVersionActions(arg0 context.Context, arg1 *reverse_rpc.SetCaseReplayVersionActionsRequest) (*reverse_rpc.EmptyCaseReplayResponse, error) {
	arg0, span := otel.Tracer("sico-backend/otelwrap").Start(arg0, "Service.RpcSetCaseReplayVersionActions")
	defer span.End()

	ret0, ret1 := w.next.RpcSetCaseReplayVersionActions(arg0, arg1)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}
