// Code generated by otelwrapgen; DO NOT EDIT.
package scheduledtask

import (
	"context"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
	"sico-backend/internal/transport/http/dto/scheduledtask"
)

func WithTracing(next Service) Service {
	if next == nil {
		return nil
	}
	return &otelTracedService{next: next}
}

type otelTracedService struct {
	next Service
}

func (w *otelTracedService) Unwrap() Service {
	return w.next
}

func (w *otelTracedService) Create(ctx context.Context, req *scheduledtask.CreateScheduledTaskRequest) (*scheduledtask.CreateScheduledTaskResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.Create")
	defer span.End()

	ret0, ret1 := w.next.Create(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) Delete(ctx context.Context, req *scheduledtask.DeleteScheduledTaskRequest) (*scheduledtask.DeleteScheduledTaskResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.Delete")
	defer span.End()

	ret0, ret1 := w.next.Delete(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) Get(ctx context.Context, req *scheduledtask.GetScheduledTaskRequest) (*scheduledtask.GetScheduledTaskResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.Get")
	defer span.End()

	ret0, ret1 := w.next.Get(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) List(ctx context.Context, req *scheduledtask.ListScheduledTasksRequest) (*scheduledtask.ListScheduledTasksResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.List")
	defer span.End()

	ret0, ret1 := w.next.List(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) Start(ctx context.Context) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.Start")
	defer span.End()

	ret0 := w.next.Start(ctx)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedService) Update(ctx context.Context, req *scheduledtask.UpdateScheduledTaskRequest) (*scheduledtask.UpdateScheduledTaskResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.Update")
	defer span.End()

	ret0, ret1 := w.next.Update(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}
