// Code generated by otelwrapgen; DO NOT EDIT.
package repository

import (
	"context"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
	"sico-backend/internal/entity/conversation/message"
)

func WithTracingMessageRepo(next MessageRepo) MessageRepo {
	if next == nil {
		return nil
	}
	return &otelTracedMessageRepo{next: next}
}

type otelTracedMessageRepo struct {
	next MessageRepo
}

func (w *otelTracedMessageRepo) Create(ctx context.Context, msg *message.Message) (*message.Message, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "MessageRepo.Create")
	defer span.End()

	ret0, ret1 := w.next.Create(ctx, msg)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedMessageRepo) GetLatestTurnID(ctx context.Context, conversationID int64) (int64, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "MessageRepo.GetLatestTurnID")
	defer span.End()

	ret0, ret1 := w.next.GetLatestTurnID(ctx, conversationID)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedMessageRepo) GetUserMessageByConversationTurnID(ctx context.Context, conversationID int64, turnID int64) (*message.Message, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "MessageRepo.GetUserMessageByConversationTurnID")
	defer span.End()

	ret0, ret1 := w.next.GetUserMessageByConversationTurnID(ctx, conversationID, turnID)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedMessageRepo) ListByConversationPage(ctx context.Context, conversationID int64, page int32, pageSize int32) ([]*message.Message, bool, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "MessageRepo.ListByConversationPage")
	defer span.End()

	ret0, ret1, ret2 := w.next.ListByConversationPage(ctx, conversationID, page, pageSize)
	if ret2 != nil {
		span.RecordError(ret2)
		span.SetStatus(codes.Error, ret2.Error())
	}
	return ret0, ret1, ret2
}

func (w *otelTracedMessageRepo) ListByFilter(ctx context.Context, filter *MessageFilter) ([]*message.Message, bool, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "MessageRepo.ListByFilter")
	defer span.End()

	ret0, ret1, ret2 := w.next.ListByFilter(ctx, filter)
	if ret2 != nil {
		span.RecordError(ret2)
		span.SetStatus(codes.Error, ret2.Error())
	}
	return ret0, ret1, ret2
}
