// Copyright (c) 2026 Sico Authors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: taskruntime/reverse_rpc.proto

package reverse_rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReverseTaskRuntimeRPC_RpcCreateBatch_FullMethodName       = "/reverse_rpc.ReverseTaskRuntimeRPC/RpcCreateBatch"
	ReverseTaskRuntimeRPC_RpcUpdateBatch_FullMethodName       = "/reverse_rpc.ReverseTaskRuntimeRPC/RpcUpdateBatch"
	ReverseTaskRuntimeRPC_RpcGetBatch_FullMethodName          = "/reverse_rpc.ReverseTaskRuntimeRPC/RpcGetBatch"
	ReverseTaskRuntimeRPC_RpcCreateRun_FullMethodName         = "/reverse_rpc.ReverseTaskRuntimeRPC/RpcCreateRun"
	ReverseTaskRuntimeRPC_RpcUpdateRun_FullMethodName         = "/reverse_rpc.ReverseTaskRuntimeRPC/RpcUpdateRun"
	ReverseTaskRuntimeRPC_RpcLookupIdempotent_FullMethodName  = "/reverse_rpc.ReverseTaskRuntimeRPC/RpcLookupIdempotent"
	ReverseTaskRuntimeRPC_RpcClaimRun_FullMethodName          = "/reverse_rpc.ReverseTaskRuntimeRPC/RpcClaimRun"
	ReverseTaskRuntimeRPC_RpcHeartbeatBatch_FullMethodName    = "/reverse_rpc.ReverseTaskRuntimeRPC/RpcHeartbeatBatch"
	ReverseTaskRuntimeRPC_RpcSetRunProgress_FullMethodName    = "/reverse_rpc.ReverseTaskRuntimeRPC/RpcSetRunProgress"
	ReverseTaskRuntimeRPC_RpcWriteResult_FullMethodName       = "/reverse_rpc.ReverseTaskRuntimeRPC/RpcWriteResult"
	ReverseTaskRuntimeRPC_RpcCancelBatch_FullMethodName       = "/reverse_rpc.ReverseTaskRuntimeRPC/RpcCancelBatch"
	ReverseTaskRuntimeRPC_RpcCancelRun_FullMethodName         = "/reverse_rpc.ReverseTaskRuntimeRPC/RpcCancelRun"
	ReverseTaskRuntimeRPC_RpcGetRun_FullMethodName            = "/reverse_rpc.ReverseTaskRuntimeRPC/RpcGetRun"
	ReverseTaskRuntimeRPC_RpcGetTaskDetail_FullMethodName     = "/reverse_rpc.ReverseTaskRuntimeRPC/RpcGetTaskDetail"
	ReverseTaskRuntimeRPC_RpcListBatchRuns_FullMethodName     = "/reverse_rpc.ReverseTaskRuntimeRPC/RpcListBatchRuns"
	ReverseTaskRuntimeRPC_RpcListBatchesByTurn_FullMethodName = "/reverse_rpc.ReverseTaskRuntimeRPC/RpcListBatchesByTurn"
	ReverseTaskRuntimeRPC_RpcSweepStaleRuns_FullMethodName    = "/reverse_rpc.ReverseTaskRuntimeRPC/RpcSweepStaleRuns"
	ReverseTaskRuntimeRPC_RpcReopenRunForRetry_FullMethodName = "/reverse_rpc.ReverseTaskRuntimeRPC/RpcReopenRunForRetry"
)

// ReverseTaskRuntimeRPCClient is the client API for ReverseTaskRuntimeRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReverseTaskRuntimeRPCClient interface {
	RpcCreateBatch(ctx context.Context, in *CreateBatchRequest, opts ...grpc.CallOption) (*EmptyTaskRuntimeResponse, error)
	RpcUpdateBatch(ctx context.Context, in *UpdateBatchRequest, opts ...grpc.CallOption) (*EmptyTaskRuntimeResponse, error)
	RpcGetBatch(ctx context.Context, in *GetBatchRequest, opts ...grpc.CallOption) (*GetBatchResponse, error)
	RpcCreateRun(ctx context.Context, in *CreateRunRequest, opts ...grpc.CallOption) (*EmptyTaskRuntimeResponse, error)
	RpcUpdateRun(ctx context.Context, in *UpdateRunRequest, opts ...grpc.CallOption) (*EmptyTaskRuntimeResponse, error)
	RpcLookupIdempotent(ctx context.Context, in *LookupIdempotentRequest, opts ...grpc.CallOption) (*GetRunResponse, error)
	RpcClaimRun(ctx context.Context, in *ClaimRunRequest, opts ...grpc.CallOption) (*ClaimRunResponse, error)
	RpcHeartbeatBatch(ctx context.Context, in *HeartbeatBatchRequest, opts ...grpc.CallOption) (*EmptyTaskRuntimeResponse, error)
	RpcSetRunProgress(ctx context.Context, in *SetRunProgressRequest, opts ...grpc.CallOption) (*EmptyTaskRuntimeResponse, error)
	RpcWriteResult(ctx context.Context, in *WriteResultRequest, opts ...grpc.CallOption) (*EmptyTaskRuntimeResponse, error)
	RpcCancelBatch(ctx context.Context, in *CancelBatchRequest, opts ...grpc.CallOption) (*EmptyTaskRuntimeResponse, error)
	RpcCancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*EmptyTaskRuntimeResponse, error)
	RpcGetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*GetRunResponse, error)
	RpcGetTaskDetail(ctx context.Context, in *GetTaskDetailRequest, opts ...grpc.CallOption) (*GetTaskDetailResponse, error)
	RpcListBatchRuns(ctx context.Context, in *ListBatchRunsRequest, opts ...grpc.CallOption) (*ListBatchRunsResponse, error)
	RpcListBatchesByTurn(ctx context.Context, in *ListBatchesByTurnRequest, opts ...grpc.CallOption) (*ListBatchesByTurnResponse, error)
	RpcSweepStaleRuns(ctx context.Context, in *SweepStaleRunsRequest, opts ...grpc.CallOption) (*SweepStaleRunsResponse, error)
	RpcReopenRunForRetry(ctx context.Context, in *ReopenRunForRetryRequest, opts ...grpc.CallOption) (*EmptyTaskRuntimeResponse, error)
}

type reverseTaskRuntimeRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewReverseTaskRuntimeRPCClient(cc grpc.ClientConnInterface) ReverseTaskRuntimeRPCClient {
	return &reverseTaskRuntimeRPCClient{cc}
}

func (c *reverseTaskRuntimeRPCClient) RpcCreateBatch(ctx context.Context, in *CreateBatchRequest, opts ...grpc.CallOption) (*EmptyTaskRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyTaskRuntimeResponse)
	err := c.cc.Invoke(ctx, ReverseTaskRuntimeRPC_RpcCreateBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseTaskRuntimeRPCClient) RpcUpdateBatch(ctx context.Context, in *UpdateBatchRequest, opts ...grpc.CallOption) (*EmptyTaskRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyTaskRuntimeResponse)
	err := c.cc.Invoke(ctx, ReverseTaskRuntimeRPC_RpcUpdateBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseTaskRuntimeRPCClient) RpcGetBatch(ctx context.Context, in *GetBatchRequest, opts ...grpc.CallOption) (*GetBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBatchResponse)
	err := c.cc.Invoke(ctx, ReverseTaskRuntimeRPC_RpcGetBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseTaskRuntimeRPCClient) RpcCreateRun(ctx context.Context, in *CreateRunRequest, opts ...grpc.CallOption) (*EmptyTaskRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyTaskRuntimeResponse)
	err := c.cc.Invoke(ctx, ReverseTaskRuntimeRPC_RpcCreateRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseTaskRuntimeRPCClient) RpcUpdateRun(ctx context.Context, in *UpdateRunRequest, opts ...grpc.CallOption) (*EmptyTaskRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyTaskRuntimeResponse)
	err := c.cc.Invoke(ctx, ReverseTaskRuntimeRPC_RpcUpdateRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseTaskRuntimeRPCClient) RpcLookupIdempotent(ctx context.Context, in *LookupIdempotentRequest, opts ...grpc.CallOption) (*GetRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunResponse)
	err := c.cc.Invoke(ctx, ReverseTaskRuntimeRPC_RpcLookupIdempotent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseTaskRuntimeRPCClient) RpcClaimRun(ctx context.Context, in *ClaimRunRequest, opts ...grpc.CallOption) (*ClaimRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimRunResponse)
	err := c.cc.Invoke(ctx, ReverseTaskRuntimeRPC_RpcClaimRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseTaskRuntimeRPCClient) RpcHeartbeatBatch(ctx context.Context, in *HeartbeatBatchRequest, opts ...grpc.CallOption) (*EmptyTaskRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyTaskRuntimeResponse)
	err := c.cc.Invoke(ctx, ReverseTaskRuntimeRPC_RpcHeartbeatBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseTaskRuntimeRPCClient) RpcSetRunProgress(ctx context.Context, in *SetRunProgressRequest, opts ...grpc.CallOption) (*EmptyTaskRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyTaskRuntimeResponse)
	err := c.cc.Invoke(ctx, ReverseTaskRuntimeRPC_RpcSetRunProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseTaskRuntimeRPCClient) RpcWriteResult(ctx context.Context, in *WriteResultRequest, opts ...grpc.CallOption) (*EmptyTaskRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyTaskRuntimeResponse)
	err := c.cc.Invoke(ctx, ReverseTaskRuntimeRPC_RpcWriteResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseTaskRuntimeRPCClient) RpcCancelBatch(ctx context.Context, in *CancelBatchRequest, opts ...grpc.CallOption) (*EmptyTaskRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyTaskRuntimeResponse)
	err := c.cc.Invoke(ctx, ReverseTaskRuntimeRPC_RpcCancelBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseTaskRuntimeRPCClient) RpcCancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*EmptyTaskRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyTaskRuntimeResponse)
	err := c.cc.Invoke(ctx, ReverseTaskRuntimeRPC_RpcCancelRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseTaskRuntimeRPCClient) RpcGetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*GetRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunResponse)
	err := c.cc.Invoke(ctx, ReverseTaskRuntimeRPC_RpcGetRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseTaskRuntimeRPCClient) RpcGetTaskDetail(ctx context.Context, in *GetTaskDetailRequest, opts ...grpc.CallOption) (*GetTaskDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskDetailResponse)
	err := c.cc.Invoke(ctx, ReverseTaskRuntimeRPC_RpcGetTaskDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseTaskRuntimeRPCClient) RpcListBatchRuns(ctx context.Context, in *ListBatchRunsRequest, opts ...grpc.CallOption) (*ListBatchRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBatchRunsResponse)
	err := c.cc.Invoke(ctx, ReverseTaskRuntimeRPC_RpcListBatchRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseTaskRuntimeRPCClient) RpcListBatchesByTurn(ctx context.Context, in *ListBatchesByTurnRequest, opts ...grpc.CallOption) (*ListBatchesByTurnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBatchesByTurnResponse)
	err := c.cc.Invoke(ctx, ReverseTaskRuntimeRPC_RpcListBatchesByTurn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseTaskRuntimeRPCClient) RpcSweepStaleRuns(ctx context.Context, in *SweepStaleRunsRequest, opts ...grpc.CallOption) (*SweepStaleRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SweepStaleRunsResponse)
	err := c.cc.Invoke(ctx, ReverseTaskRuntimeRPC_RpcSweepStaleRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseTaskRuntimeRPCClient) RpcReopenRunForRetry(ctx context.Context, in *ReopenRunForRetryRequest, opts ...grpc.CallOption) (*EmptyTaskRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyTaskRuntimeResponse)
	err := c.cc.Invoke(ctx, ReverseTaskRuntimeRPC_RpcReopenRunForRetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReverseTaskRuntimeRPCServer is the server API for ReverseTaskRuntimeRPC service.
// All implementations must embed UnimplementedReverseTaskRuntimeRPCServer
// for forward compatibility.
type ReverseTaskRuntimeRPCServer interface {
	RpcCreateBatch(context.Context, *CreateBatchRequest) (*EmptyTaskRuntimeResponse, error)
	RpcUpdateBatch(context.Context, *UpdateBatchRequest) (*EmptyTaskRuntimeResponse, error)
	RpcGetBatch(context.Context, *GetBatchRequest) (*GetBatchResponse, error)
	RpcCreateRun(context.Context, *CreateRunRequest) (*EmptyTaskRuntimeResponse, error)
	RpcUpdateRun(context.Context, *UpdateRunRequest) (*EmptyTaskRuntimeResponse, error)
	RpcLookupIdempotent(context.Context, *LookupIdempotentRequest) (*GetRunResponse, error)
	RpcClaimRun(context.Context, *ClaimRunRequest) (*ClaimRunResponse, error)
	RpcHeartbeatBatch(context.Context, *HeartbeatBatchRequest) (*EmptyTaskRuntimeResponse, error)
	RpcSetRunProgress(context.Context, *SetRunProgressRequest) (*EmptyTaskRuntimeResponse, error)
	RpcWriteResult(context.Context, *WriteResultRequest) (*EmptyTaskRuntimeResponse, error)
	RpcCancelBatch(context.Context, *CancelBatchRequest) (*EmptyTaskRuntimeResponse, error)
	RpcCancelRun(context.Context, *CancelRunRequest) (*EmptyTaskRuntimeResponse, error)
	RpcGetRun(context.Context, *GetRunRequest) (*GetRunResponse, error)
	RpcGetTaskDetail(context.Context, *GetTaskDetailRequest) (*GetTaskDetailResponse, error)
	RpcListBatchRuns(context.Context, *ListBatchRunsRequest) (*ListBatchRunsResponse, error)
	RpcListBatchesByTurn(context.Context, *ListBatchesByTurnRequest) (*ListBatchesByTurnResponse, error)
	RpcSweepStaleRuns(context.Context, *SweepStaleRunsRequest) (*SweepStaleRunsResponse, error)
	RpcReopenRunForRetry(context.Context, *ReopenRunForRetryRequest) (*EmptyTaskRuntimeResponse, error)
	mustEmbedUnimplementedReverseTaskRuntimeRPCServer()
}

// UnimplementedReverseTaskRuntimeRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReverseTaskRuntimeRPCServer struct{}

func (UnimplementedReverseTaskRuntimeRPCServer) RpcCreateBatch(context.Context, *CreateBatchRequest) (*EmptyTaskRuntimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RpcCreateBatch not implemented")
}
func (UnimplementedReverseTaskRuntimeRPCServer) RpcUpdateBatch(context.Context, *UpdateBatchRequest) (*EmptyTaskRuntimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RpcUpdateBatch not implemented")
}
func (UnimplementedReverseTaskRuntimeRPCServer) RpcGetBatch(context.Context, *GetBatchRequest) (*GetBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RpcGetBatch not implemented")
}
func (UnimplementedReverseTaskRuntimeRPCServer) RpcCreateRun(context.Context, *CreateRunRequest) (*EmptyTaskRuntimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RpcCreateRun not implemented")
}
func (UnimplementedReverseTaskRuntimeRPCServer) RpcUpdateRun(context.Context, *UpdateRunRequest) (*EmptyTaskRuntimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RpcUpdateRun not implemented")
}
func (UnimplementedReverseTaskRuntimeRPCServer) RpcLookupIdempotent(context.Context, *LookupIdempotentRequest) (*GetRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RpcLookupIdempotent not implemented")
}
func (UnimplementedReverseTaskRuntimeRPCServer) RpcClaimRun(context.Context, *ClaimRunRequest) (*ClaimRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RpcClaimRun not implemented")
}
func (UnimplementedReverseTaskRuntimeRPCServer) RpcHeartbeatBatch(context.Context, *HeartbeatBatchRequest) (*EmptyTaskRuntimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RpcHeartbeatBatch not implemented")
}
func (UnimplementedReverseTaskRuntimeRPCServer) RpcSetRunProgress(context.Context, *SetRunProgressRequest) (*EmptyTaskRuntimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RpcSetRunProgress not implemented")
}
func (UnimplementedReverseTaskRuntimeRPCServer) RpcWriteResult(context.Context, *WriteResultRequest) (*EmptyTaskRuntimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RpcWriteResult not implemented")
}
func (UnimplementedReverseTaskRuntimeRPCServer) RpcCancelBatch(context.Context, *CancelBatchRequest) (*EmptyTaskRuntimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RpcCancelBatch not implemented")
}
func (UnimplementedReverseTaskRuntimeRPCServer) RpcCancelRun(context.Context, *CancelRunRequest) (*EmptyTaskRuntimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RpcCancelRun not implemented")
}
func (UnimplementedReverseTaskRuntimeRPCServer) RpcGetRun(context.Context, *GetRunRequest) (*GetRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RpcGetRun not implemented")
}
func (UnimplementedReverseTaskRuntimeRPCServer) RpcGetTaskDetail(context.Context, *GetTaskDetailRequest) (*GetTaskDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RpcGetTaskDetail not implemented")
}
func (UnimplementedReverseTaskRuntimeRPCServer) RpcListBatchRuns(context.Context, *ListBatchRunsRequest) (*ListBatchRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RpcListBatchRuns not implemented")
}
func (UnimplementedReverseTaskRuntimeRPCServer) RpcListBatchesByTurn(context.Context, *ListBatchesByTurnRequest) (*ListBatchesByTurnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RpcListBatchesByTurn not implemented")
}
func (UnimplementedReverseTaskRuntimeRPCServer) RpcSweepStaleRuns(context.Context, *SweepStaleRunsRequest) (*SweepStaleRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RpcSweepStaleRuns not implemented")
}
func (UnimplementedReverseTaskRuntimeRPCServer) RpcReopenRunForRetry(context.Context, *ReopenRunForRetryRequest) (*EmptyTaskRuntimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RpcReopenRunForRetry not implemented")
}
func (UnimplementedReverseTaskRuntimeRPCServer) mustEmbedUnimplementedReverseTaskRuntimeRPCServer() {}
func (UnimplementedReverseTaskRuntimeRPCServer) testEmbeddedByValue()                               {}

// UnsafeReverseTaskRuntimeRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReverseTaskRuntimeRPCServer will
// result in compilation errors.
type UnsafeReverseTaskRuntimeRPCServer interface {
	mustEmbedUnimplementedReverseTaskRuntimeRPCServer()
}

func RegisterReverseTaskRuntimeRPCServer(s grpc.ServiceRegistrar, srv ReverseTaskRuntimeRPCServer) {
	// If the following call panics, it indicates UnimplementedReverseTaskRuntimeRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReverseTaskRuntimeRPC_ServiceDesc, srv)
}

func _ReverseTaskRuntimeRPC_RpcCreateBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseTaskRuntimeRPCServer).RpcCreateBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseTaskRuntimeRPC_RpcCreateBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseTaskRuntimeRPCServer).RpcCreateBatch(ctx, req.(*CreateBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverseTaskRuntimeRPC_RpcUpdateBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseTaskRuntimeRPCServer).RpcUpdateBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseTaskRuntimeRPC_RpcUpdateBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseTaskRuntimeRPCServer).RpcUpdateBatch(ctx, req.(*UpdateBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverseTaskRuntimeRPC_RpcGetBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseTaskRuntimeRPCServer).RpcGetBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseTaskRuntimeRPC_RpcGetBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseTaskRuntimeRPCServer).RpcGetBatch(ctx, req.(*GetBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverseTaskRuntimeRPC_RpcCreateRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseTaskRuntimeRPCServer).RpcCreateRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseTaskRuntimeRPC_RpcCreateRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseTaskRuntimeRPCServer).RpcCreateRun(ctx, req.(*CreateRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverseTaskRuntimeRPC_RpcUpdateRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseTaskRuntimeRPCServer).RpcUpdateRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseTaskRuntimeRPC_RpcUpdateRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseTaskRuntimeRPCServer).RpcUpdateRun(ctx, req.(*UpdateRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverseTaskRuntimeRPC_RpcLookupIdempotent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupIdempotentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseTaskRuntimeRPCServer).RpcLookupIdempotent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseTaskRuntimeRPC_RpcLookupIdempotent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseTaskRuntimeRPCServer).RpcLookupIdempotent(ctx, req.(*LookupIdempotentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverseTaskRuntimeRPC_RpcClaimRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseTaskRuntimeRPCServer).RpcClaimRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseTaskRuntimeRPC_RpcClaimRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseTaskRuntimeRPCServer).RpcClaimRun(ctx, req.(*ClaimRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverseTaskRuntimeRPC_RpcHeartbeatBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseTaskRuntimeRPCServer).RpcHeartbeatBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseTaskRuntimeRPC_RpcHeartbeatBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseTaskRuntimeRPCServer).RpcHeartbeatBatch(ctx, req.(*HeartbeatBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverseTaskRuntimeRPC_RpcSetRunProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRunProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseTaskRuntimeRPCServer).RpcSetRunProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseTaskRuntimeRPC_RpcSetRunProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseTaskRuntimeRPCServer).RpcSetRunProgress(ctx, req.(*SetRunProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverseTaskRuntimeRPC_RpcWriteResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseTaskRuntimeRPCServer).RpcWriteResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseTaskRuntimeRPC_RpcWriteResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseTaskRuntimeRPCServer).RpcWriteResult(ctx, req.(*WriteResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverseTaskRuntimeRPC_RpcCancelBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseTaskRuntimeRPCServer).RpcCancelBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseTaskRuntimeRPC_RpcCancelBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseTaskRuntimeRPCServer).RpcCancelBatch(ctx, req.(*CancelBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverseTaskRuntimeRPC_RpcCancelRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseTaskRuntimeRPCServer).RpcCancelRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseTaskRuntimeRPC_RpcCancelRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseTaskRuntimeRPCServer).RpcCancelRun(ctx, req.(*CancelRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverseTaskRuntimeRPC_RpcGetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseTaskRuntimeRPCServer).RpcGetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseTaskRuntimeRPC_RpcGetRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseTaskRuntimeRPCServer).RpcGetRun(ctx, req.(*GetRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverseTaskRuntimeRPC_RpcGetTaskDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseTaskRuntimeRPCServer).RpcGetTaskDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseTaskRuntimeRPC_RpcGetTaskDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseTaskRuntimeRPCServer).RpcGetTaskDetail(ctx, req.(*GetTaskDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverseTaskRuntimeRPC_RpcListBatchRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBatchRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseTaskRuntimeRPCServer).RpcListBatchRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseTaskRuntimeRPC_RpcListBatchRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseTaskRuntimeRPCServer).RpcListBatchRuns(ctx, req.(*ListBatchRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverseTaskRuntimeRPC_RpcListBatchesByTurn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBatchesByTurnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseTaskRuntimeRPCServer).RpcListBatchesByTurn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseTaskRuntimeRPC_RpcListBatchesByTurn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseTaskRuntimeRPCServer).RpcListBatchesByTurn(ctx, req.(*ListBatchesByTurnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverseTaskRuntimeRPC_RpcSweepStaleRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SweepStaleRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseTaskRuntimeRPCServer).RpcSweepStaleRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseTaskRuntimeRPC_RpcSweepStaleRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseTaskRuntimeRPCServer).RpcSweepStaleRuns(ctx, req.(*SweepStaleRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverseTaskRuntimeRPC_RpcReopenRunForRetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReopenRunForRetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseTaskRuntimeRPCServer).RpcReopenRunForRetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseTaskRuntimeRPC_RpcReopenRunForRetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseTaskRuntimeRPCServer).RpcReopenRunForRetry(ctx, req.(*ReopenRunForRetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReverseTaskRuntimeRPC_ServiceDesc is the grpc.ServiceDesc for ReverseTaskRuntimeRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReverseTaskRuntimeRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reverse_rpc.ReverseTaskRuntimeRPC",
	HandlerType: (*ReverseTaskRuntimeRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RpcCreateBatch",
			Handler:    _ReverseTaskRuntimeRPC_RpcCreateBatch_Handler,
		},
		{
			MethodName: "RpcUpdateBatch",
			Handler:    _ReverseTaskRuntimeRPC_RpcUpdateBatch_Handler,
		},
		{
			MethodName: "RpcGetBatch",
			Handler:    _ReverseTaskRuntimeRPC_RpcGetBatch_Handler,
		},
		{
			MethodName: "RpcCreateRun",
			Handler:    _ReverseTaskRuntimeRPC_RpcCreateRun_Handler,
		},
		{
			MethodName: "RpcUpdateRun",
			Handler:    _ReverseTaskRuntimeRPC_RpcUpdateRun_Handler,
		},
		{
			MethodName: "RpcLookupIdempotent",
			Handler:    _ReverseTaskRuntimeRPC_RpcLookupIdempotent_Handler,
		},
		{
			MethodName: "RpcClaimRun",
			Handler:    _ReverseTaskRuntimeRPC_RpcClaimRun_Handler,
		},
		{
			MethodName: "RpcHeartbeatBatch",
			Handler:    _ReverseTaskRuntimeRPC_RpcHeartbeatBatch_Handler,
		},
		{
			MethodName: "RpcSetRunProgress",
			Handler:    _ReverseTaskRuntimeRPC_RpcSetRunProgress_Handler,
		},
		{
			MethodName: "RpcWriteResult",
			Handler:    _ReverseTaskRuntimeRPC_RpcWriteResult_Handler,
		},
		{
			MethodName: "RpcCancelBatch",
			Handler:    _ReverseTaskRuntimeRPC_RpcCancelBatch_Handler,
		},
		{
			MethodName: "RpcCancelRun",
			Handler:    _ReverseTaskRuntimeRPC_RpcCancelRun_Handler,
		},
		{
			MethodName: "RpcGetRun",
			Handler:    _ReverseTaskRuntimeRPC_RpcGetRun_Handler,
		},
		{
			MethodName: "RpcGetTaskDetail",
			Handler:    _ReverseTaskRuntimeRPC_RpcGetTaskDetail_Handler,
		},
		{
			MethodName: "RpcListBatchRuns",
			Handler:    _ReverseTaskRuntimeRPC_RpcListBatchRuns_Handler,
		},
		{
			MethodName: "RpcListBatchesByTurn",
			Handler:    _ReverseTaskRuntimeRPC_RpcListBatchesByTurn_Handler,
		},
		{
			MethodName: "RpcSweepStaleRuns",
			Handler:    _ReverseTaskRuntimeRPC_RpcSweepStaleRuns_Handler,
		},
		{
			MethodName: "RpcReopenRunForRetry",
			Handler:    _ReverseTaskRuntimeRPC_RpcReopenRunForRetry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "taskruntime/reverse_rpc.proto",
}
