# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: knowledge/reverse_rpc.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "GetKnowledgeMetadataRequest",
    "GetKnowledgeMetadataResponse",
    "KnowledgeMetadata",
    "ReverseKnowledgeRpcBase",
    "ReverseKnowledgeRpcStub",
    "UpsertKnowledgePlaybookRequest",
    "UpsertKnowledgePlaybookResponse",
)

from dataclasses import dataclass
from typing import TYPE_CHECKING

import betterproto2
import grpc
import grpclib
from betterproto2 import grpclib as betterproto2_grpclib

from ..message_pool import default_message_pool

if TYPE_CHECKING:
    import grpclib.server

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class GetKnowledgeMetadataRequest(betterproto2.Message):
    knowledge_ids: "list[int]" = betterproto2.field(
        1, betterproto2.TYPE_INT64, repeated=True
    )
    """
    @gotag: json:"knowledgeIds"
    """


default_message_pool.register_message(
    "reverse_rpc", "GetKnowledgeMetadataRequest", GetKnowledgeMetadataRequest
)


@dataclass(eq=False, repr=False)
class GetKnowledgeMetadataResponse(betterproto2.Message):
    data: "list[KnowledgeMetadata]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )
    """
    @gotag: json:"data"
    """

    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)
    """
    @gotag: json:"code"
    """

    msg: "str" = betterproto2.field(254, betterproto2.TYPE_STRING)
    """
    @gotag: json:"msg"
    """


default_message_pool.register_message(
    "reverse_rpc", "GetKnowledgeMetadataResponse", GetKnowledgeMetadataResponse
)


@dataclass(eq=False, repr=False)
class KnowledgeMetadata(betterproto2.Message):
    knowledge_id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: json:"knowledgeId"
    """

    name: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    @gotag: json:"name"
    """

    tags: "list[str]" = betterproto2.field(3, betterproto2.TYPE_STRING, repeated=True)
    """
    @gotag: json:"tags"
    """


default_message_pool.register_message(
    "reverse_rpc", "KnowledgeMetadata", KnowledgeMetadata
)


@dataclass(eq=False, repr=False)
class UpsertKnowledgePlaybookRequest(betterproto2.Message):
    project_id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: json:"projectId"
    """

    agent_instance_id: "int" = betterproto2.field(2, betterproto2.TYPE_INT64)
    """
    @gotag: json:"agentInstanceId"
    """


default_message_pool.register_message(
    "reverse_rpc", "UpsertKnowledgePlaybookRequest", UpsertKnowledgePlaybookRequest
)


@dataclass(eq=False, repr=False)
class UpsertKnowledgePlaybookResponse(betterproto2.Message):
    playbook_id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: json:"playbookId"
    """

    created: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)
    """
    @gotag: json:"created"
    """

    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)
    """
    @gotag: json:"code"
    """

    msg: "str" = betterproto2.field(254, betterproto2.TYPE_STRING)
    """
    @gotag: json:"msg"
    """


default_message_pool.register_message(
    "reverse_rpc", "UpsertKnowledgePlaybookResponse", UpsertKnowledgePlaybookResponse
)


class ReverseKnowledgeRpcStub:
    def __init__(self, channel: grpc.Channel):
        self._channel = channel

    def rpc_list_knowledge_metadata(
        self, message: "GetKnowledgeMetadataRequest"
    ) -> "GetKnowledgeMetadataResponse":
        """
        Fetch knowledge metadata (name and tags) for a list of knowledge document IDs.
        """

        return self._channel.unary_unary(
            "/reverse_rpc.ReverseKnowledgeRPC/RpcListKnowledgeMetadata",
            GetKnowledgeMetadataRequest.SerializeToString,
            GetKnowledgeMetadataResponse.FromString,
        )(message)

    def rpc_upsert_knowledge_playbook(
        self, message: "UpsertKnowledgePlaybookRequest"
    ) -> "UpsertKnowledgePlaybookResponse":
        """
        Create or update a knowledge playbook for a given project and agent instance.
        If a playbook already exists for the (project_id, agent_instance_id) pair,
        only the updated_at timestamp is refreshed; otherwise a new record is created.
        """

        return self._channel.unary_unary(
            "/reverse_rpc.ReverseKnowledgeRPC/RpcUpsertKnowledgePlaybook",
            UpsertKnowledgePlaybookRequest.SerializeToString,
            UpsertKnowledgePlaybookResponse.FromString,
        )(message)


class ReverseKnowledgeRpcBase(betterproto2_grpclib.ServiceBase):
    async def rpc_list_knowledge_metadata(
        self, message: "GetKnowledgeMetadataRequest"
    ) -> "GetKnowledgeMetadataResponse":
        """
        Fetch knowledge metadata (name and tags) for a list of knowledge document IDs.
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def rpc_upsert_knowledge_playbook(
        self, message: "UpsertKnowledgePlaybookRequest"
    ) -> "UpsertKnowledgePlaybookResponse":
        """
        Create or update a knowledge playbook for a given project and agent instance.
        If a playbook already exists for the (project_id, agent_instance_id) pair,
        only the updated_at timestamp is refreshed; otherwise a new record is created.
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_rpc_list_knowledge_metadata(
        self,
        stream: "grpclib.server.Stream[GetKnowledgeMetadataRequest, GetKnowledgeMetadataResponse]",
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.rpc_list_knowledge_metadata(request)
        await stream.send_message(response)

    async def __rpc_rpc_upsert_knowledge_playbook(
        self,
        stream: "grpclib.server.Stream[UpsertKnowledgePlaybookRequest, UpsertKnowledgePlaybookResponse]",
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.rpc_upsert_knowledge_playbook(request)
        await stream.send_message(response)

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/reverse_rpc.ReverseKnowledgeRPC/RpcListKnowledgeMetadata": grpclib.const.Handler(
                self.__rpc_rpc_list_knowledge_metadata,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetKnowledgeMetadataRequest,
                GetKnowledgeMetadataResponse,
            ),
            "/reverse_rpc.ReverseKnowledgeRPC/RpcUpsertKnowledgePlaybook": grpclib.const.Handler(
                self.__rpc_rpc_upsert_knowledge_playbook,
                grpclib.const.Cardinality.UNARY_UNARY,
                UpsertKnowledgePlaybookRequest,
                UpsertKnowledgePlaybookResponse,
            ),
        }
