// Code generated by otelwrapgen; DO NOT EDIT.
package authstate

import (
	"context"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
	"sico-backend/internal/transport/http/dto/authstate"
	reverse_rpc "sico-backend/internal/transport/reverse_grpc/pb/authstate"
)

func WithTracing(next Service) Service {
	if next == nil {
		return nil
	}
	return &otelTracedService{next: next}
}

type otelTracedService struct {
	reverse_rpc.UnimplementedReverseAuthStateRPCServer
	next Service
}

func (w *otelTracedService) Unwrap() Service {
	return w.next
}

func (w *otelTracedService) GetAuthState(ctx context.Context, req *authstate.GetAuthStateRequest) (*authstate.GetAuthStateResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.GetAuthState")
	defer span.End()

	ret0, ret1 := w.next.GetAuthState(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) ImportAuthState(ctx context.Context, req *authstate.ImportAuthStateRequest) (*authstate.ImportAuthStateResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.ImportAuthState")
	defer span.End()

	ret0, ret1 := w.next.ImportAuthState(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) RpcGetAuthState(arg0 context.Context, arg1 *reverse_rpc.GetAuthStateRequest) (*reverse_rpc.GetAuthStateResponse, error) {
	arg0, span := otel.Tracer("sico-backend/otelwrap").Start(arg0, "Service.RpcGetAuthState")
	defer span.End()

	ret0, ret1 := w.next.RpcGetAuthState(arg0, arg1)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) RpcMarkAuthStateExpired(arg0 context.Context, arg1 *reverse_rpc.MarkAuthStateExpiredRequest) (*reverse_rpc.EmptyAuthStateResponse, error) {
	arg0, span := otel.Tracer("sico-backend/otelwrap").Start(arg0, "Service.RpcMarkAuthStateExpired")
	defer span.End()

	ret0, ret1 := w.next.RpcMarkAuthStateExpired(arg0, arg1)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) RpcUpsertAuthState(arg0 context.Context, arg1 *reverse_rpc.UpsertAuthStateRequest) (*reverse_rpc.UpsertAuthStateResponse, error) {
	arg0, span := otel.Tracer("sico-backend/otelwrap").Start(arg0, "Service.RpcUpsertAuthState")
	defer span.End()

	ret0, ret1 := w.next.RpcUpsertAuthState(arg0, arg1)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) UpdateAuthStateStatus(ctx context.Context, req *authstate.UpdateAuthStateStatusRequest) (*authstate.UpdateAuthStateStatusResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.UpdateAuthStateStatus")
	defer span.End()

	ret0, ret1 := w.next.UpdateAuthStateStatus(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}
