// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: authstate/reverse_rpc.proto

package reverse_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthStateStatus int32

const (
	AuthStateStatus_AUTH_STATE_STATUS_UNKNOWN  AuthStateStatus = 0
	AuthStateStatus_AUTH_STATE_STATUS_VALID    AuthStateStatus = 1
	AuthStateStatus_AUTH_STATE_STATUS_EXPIRED  AuthStateStatus = 2
	AuthStateStatus_AUTH_STATE_STATUS_DISABLED AuthStateStatus = 3
)

// Enum value maps for AuthStateStatus.
var (
	AuthStateStatus_name = map[int32]string{
		0: "AUTH_STATE_STATUS_UNKNOWN",
		1: "AUTH_STATE_STATUS_VALID",
		2: "AUTH_STATE_STATUS_EXPIRED",
		3: "AUTH_STATE_STATUS_DISABLED",
	}
	AuthStateStatus_value = map[string]int32{
		"AUTH_STATE_STATUS_UNKNOWN":  0,
		"AUTH_STATE_STATUS_VALID":    1,
		"AUTH_STATE_STATUS_EXPIRED":  2,
		"AUTH_STATE_STATUS_DISABLED": 3,
	}
)

func (x AuthStateStatus) Enum() *AuthStateStatus {
	p := new(AuthStateStatus)
	*p = x
	return p
}

func (x AuthStateStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthStateStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_authstate_reverse_rpc_proto_enumTypes[0].Descriptor()
}

func (AuthStateStatus) Type() protoreflect.EnumType {
	return &file_authstate_reverse_rpc_proto_enumTypes[0]
}

func (x AuthStateStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthStateStatus.Descriptor instead.
func (AuthStateStatus) EnumDescriptor() ([]byte, []int) {
	return file_authstate_reverse_rpc_proto_rawDescGZIP(), []int{0}
}

type EmptyAuthStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,253,opt,name=code,proto3" json:"code"`
	Msg           string                 `protobuf:"bytes,254,opt,name=msg,proto3" json:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyAuthStateResponse) Reset() {
	*x = EmptyAuthStateResponse{}
	mi := &file_authstate_reverse_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyAuthStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyAuthStateResponse) ProtoMessage() {}

func (x *EmptyAuthStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authstate_reverse_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyAuthStateResponse.ProtoReflect.Descriptor instead.
func (*EmptyAuthStateResponse) Descriptor() ([]byte, []int) {
	return file_authstate_reverse_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *EmptyAuthStateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EmptyAuthStateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type AuthState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	AccountKey      string                 `protobuf:"bytes,2,opt,name=account_key,json=accountKey,proto3" json:"accountKey"`
	SiteHost        string                 `protobuf:"bytes,3,opt,name=site_host,json=siteHost,proto3" json:"siteHost"`
	StateBlobPath   string                 `protobuf:"bytes,4,opt,name=state_blob_path,json=stateBlobPath,proto3" json:"stateBlobPath"`
	Status          AuthStateStatus        `protobuf:"varint,5,opt,name=status,proto3,enum=reverse_rpc.AuthStateStatus" json:"status"`
	ExpiresAt       int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expiresAt"`
	LastValidatedAt int64                  `protobuf:"varint,7,opt,name=last_validated_at,json=lastValidatedAt,proto3" json:"lastValidatedAt"`
	Metadata        string                 `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata"`
	CreatedAt       int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"createdAt"`
	UpdatedAt       int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updatedAt"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthState) Reset() {
	*x = AuthState{}
	mi := &file_authstate_reverse_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthState) ProtoMessage() {}

func (x *AuthState) ProtoReflect() protoreflect.Message {
	mi := &file_authstate_reverse_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthState.ProtoReflect.Descriptor instead.
func (*AuthState) Descriptor() ([]byte, []int) {
	return file_authstate_reverse_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *AuthState) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuthState) GetAccountKey() string {
	if x != nil {
		return x.AccountKey
	}
	return ""
}

func (x *AuthState) GetSiteHost() string {
	if x != nil {
		return x.SiteHost
	}
	return ""
}

func (x *AuthState) GetStateBlobPath() string {
	if x != nil {
		return x.StateBlobPath
	}
	return ""
}

func (x *AuthState) GetStatus() AuthStateStatus {
	if x != nil {
		return x.Status
	}
	return AuthStateStatus_AUTH_STATE_STATUS_UNKNOWN
}

func (x *AuthState) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *AuthState) GetLastValidatedAt() int64 {
	if x != nil {
		return x.LastValidatedAt
	}
	return 0
}

func (x *AuthState) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *AuthState) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AuthState) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetAuthStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountKey    string                 `protobuf:"bytes,1,opt,name=account_key,json=accountKey,proto3" json:"accountKey"`
	SiteHost      string                 `protobuf:"bytes,2,opt,name=site_host,json=siteHost,proto3" json:"siteHost"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthStateRequest) Reset() {
	*x = GetAuthStateRequest{}
	mi := &file_authstate_reverse_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthStateRequest) ProtoMessage() {}

func (x *GetAuthStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authstate_reverse_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthStateRequest.ProtoReflect.Descriptor instead.
func (*GetAuthStateRequest) Descriptor() ([]byte, []int) {
	return file_authstate_reverse_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *GetAuthStateRequest) GetAccountKey() string {
	if x != nil {
		return x.AccountKey
	}
	return ""
}

func (x *GetAuthStateRequest) GetSiteHost() string {
	if x != nil {
		return x.SiteHost
	}
	return ""
}

type GetAuthStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found"`
	AuthState     *AuthState             `protobuf:"bytes,2,opt,name=auth_state,json=authState,proto3" json:"authState"`
	Code          int32                  `protobuf:"varint,253,opt,name=code,proto3" json:"code"`
	Msg           string                 `protobuf:"bytes,254,opt,name=msg,proto3" json:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthStateResponse) Reset() {
	*x = GetAuthStateResponse{}
	mi := &file_authstate_reverse_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthStateResponse) ProtoMessage() {}

func (x *GetAuthStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authstate_reverse_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthStateResponse.ProtoReflect.Descriptor instead.
func (*GetAuthStateResponse) Descriptor() ([]byte, []int) {
	return file_authstate_reverse_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *GetAuthStateResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetAuthStateResponse) GetAuthState() *AuthState {
	if x != nil {
		return x.AuthState
	}
	return nil
}

func (x *GetAuthStateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetAuthStateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpsertAuthStateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountKey      string                 `protobuf:"bytes,1,opt,name=account_key,json=accountKey,proto3" json:"accountKey"`
	SiteHost        string                 `protobuf:"bytes,2,opt,name=site_host,json=siteHost,proto3" json:"siteHost"`
	StateBlobPath   string                 `protobuf:"bytes,3,opt,name=state_blob_path,json=stateBlobPath,proto3" json:"stateBlobPath"`
	Status          AuthStateStatus        `protobuf:"varint,4,opt,name=status,proto3,enum=reverse_rpc.AuthStateStatus" json:"status"`
	ExpiresAt       int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expiresAt"`
	LastValidatedAt int64                  `protobuf:"varint,6,opt,name=last_validated_at,json=lastValidatedAt,proto3" json:"lastValidatedAt"`
	Metadata        string                 `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpsertAuthStateRequest) Reset() {
	*x = UpsertAuthStateRequest{}
	mi := &file_authstate_reverse_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertAuthStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertAuthStateRequest) ProtoMessage() {}

func (x *UpsertAuthStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authstate_reverse_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertAuthStateRequest.ProtoReflect.Descriptor instead.
func (*UpsertAuthStateRequest) Descriptor() ([]byte, []int) {
	return file_authstate_reverse_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertAuthStateRequest) GetAccountKey() string {
	if x != nil {
		return x.AccountKey
	}
	return ""
}

func (x *UpsertAuthStateRequest) GetSiteHost() string {
	if x != nil {
		return x.SiteHost
	}
	return ""
}

func (x *UpsertAuthStateRequest) GetStateBlobPath() string {
	if x != nil {
		return x.StateBlobPath
	}
	return ""
}

func (x *UpsertAuthStateRequest) GetStatus() AuthStateStatus {
	if x != nil {
		return x.Status
	}
	return AuthStateStatus_AUTH_STATE_STATUS_UNKNOWN
}

func (x *UpsertAuthStateRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *UpsertAuthStateRequest) GetLastValidatedAt() int64 {
	if x != nil {
		return x.LastValidatedAt
	}
	return 0
}

func (x *UpsertAuthStateRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type UpsertAuthStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Code          int32                  `protobuf:"varint,253,opt,name=code,proto3" json:"code"`
	Msg           string                 `protobuf:"bytes,254,opt,name=msg,proto3" json:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertAuthStateResponse) Reset() {
	*x = UpsertAuthStateResponse{}
	mi := &file_authstate_reverse_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertAuthStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertAuthStateResponse) ProtoMessage() {}

func (x *UpsertAuthStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authstate_reverse_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertAuthStateResponse.ProtoReflect.Descriptor instead.
func (*UpsertAuthStateResponse) Descriptor() ([]byte, []int) {
	return file_authstate_reverse_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *UpsertAuthStateResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpsertAuthStateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpsertAuthStateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type MarkAuthStateExpiredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountKey    string                 `protobuf:"bytes,1,opt,name=account_key,json=accountKey,proto3" json:"accountKey"`
	SiteHost      string                 `protobuf:"bytes,2,opt,name=site_host,json=siteHost,proto3" json:"siteHost"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAuthStateExpiredRequest) Reset() {
	*x = MarkAuthStateExpiredRequest{}
	mi := &file_authstate_reverse_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAuthStateExpiredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAuthStateExpiredRequest) ProtoMessage() {}

func (x *MarkAuthStateExpiredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authstate_reverse_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAuthStateExpiredRequest.ProtoReflect.Descriptor instead.
func (*MarkAuthStateExpiredRequest) Descriptor() ([]byte, []int) {
	return file_authstate_reverse_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *MarkAuthStateExpiredRequest) GetAccountKey() string {
	if x != nil {
		return x.AccountKey
	}
	return ""
}

func (x *MarkAuthStateExpiredRequest) GetSiteHost() string {
	if x != nil {
		return x.SiteHost
	}
	return ""
}

var File_authstate_reverse_rpc_proto protoreflect.FileDescriptor

const file_authstate_reverse_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1bauthstate/reverse_rpc.proto\x12\vreverse_rpc\"@\n" +
	"\x16EmptyAuthStateResponse\x12\x13\n" +
	"\x04code\x18\xfd\x01 \x01(\x05R\x04code\x12\x11\n" +
	"\x03msg\x18\xfe\x01 \x01(\tR\x03msg\"\xdc\x02\n" +
	"\tAuthState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vaccount_key\x18\x02 \x01(\tR\n" +
	"accountKey\x12\x1b\n" +
	"\tsite_host\x18\x03 \x01(\tR\bsiteHost\x12&\n" +
	"\x0fstate_blob_path\x18\x04 \x01(\tR\rstateBlobPath\x124\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1c.reverse_rpc.AuthStateStatusR\x06status\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\x12*\n" +
	"\x11last_validated_at\x18\a \x01(\x03R\x0flastValidatedAt\x12\x1a\n" +
	"\bmetadata\x18\b \x01(\tR\bmetadata\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\"S\n" +
	"\x13GetAuthStateRequest\x12\x1f\n" +
	"\vaccount_key\x18\x01 \x01(\tR\n" +
	"accountKey\x12\x1b\n" +
	"\tsite_host\x18\x02 \x01(\tR\bsiteHost\"\x8b\x01\n" +
	"\x14GetAuthStateResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x125\n" +
	"\n" +
	"auth_state\x18\x02 \x01(\v2\x16.reverse_rpc.AuthStateR\tauthState\x12\x13\n" +
	"\x04code\x18\xfd\x01 \x01(\x05R\x04code\x12\x11\n" +
	"\x03msg\x18\xfe\x01 \x01(\tR\x03msg\"\x9b\x02\n" +
	"\x16UpsertAuthStateRequest\x12\x1f\n" +
	"\vaccount_key\x18\x01 \x01(\tR\n" +
	"accountKey\x12\x1b\n" +
	"\tsite_host\x18\x02 \x01(\tR\bsiteHost\x12&\n" +
	"\x0fstate_blob_path\x18\x03 \x01(\tR\rstateBlobPath\x124\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1c.reverse_rpc.AuthStateStatusR\x06status\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\x12*\n" +
	"\x11last_validated_at\x18\x06 \x01(\x03R\x0flastValidatedAt\x12\x1a\n" +
	"\bmetadata\x18\a \x01(\tR\bmetadata\"Q\n" +
	"\x17UpsertAuthStateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x13\n" +
	"\x04code\x18\xfd\x01 \x01(\x05R\x04code\x12\x11\n" +
	"\x03msg\x18\xfe\x01 \x01(\tR\x03msg\"[\n" +
	"\x1bMarkAuthStateExpiredRequest\x12\x1f\n" +
	"\vaccount_key\x18\x01 \x01(\tR\n" +
	"accountKey\x12\x1b\n" +
	"\tsite_host\x18\x02 \x01(\tR\bsiteHost*\x8c\x01\n" +
	"\x0fAuthStateStatus\x12\x1d\n" +
	"\x19AUTH_STATE_STATUS_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17AUTH_STATE_STATUS_VALID\x10\x01\x12\x1d\n" +
	"\x19AUTH_STATE_STATUS_EXPIRED\x10\x02\x12\x1e\n" +
	"\x1aAUTH_STATE_STATUS_DISABLED\x10\x032\xbe\x02\n" +
	"\x13ReverseAuthStateRPC\x12X\n" +
	"\x0fRpcGetAuthState\x12 .reverse_rpc.GetAuthStateRequest\x1a!.reverse_rpc.GetAuthStateResponse\"\x00\x12a\n" +
	"\x12RpcUpsertAuthState\x12#.reverse_rpc.UpsertAuthStateRequest\x1a$.reverse_rpc.UpsertAuthStateResponse\"\x00\x12j\n" +
	"\x17RpcMarkAuthStateExpired\x12(.reverse_rpc.MarkAuthStateExpiredRequest\x1a#.reverse_rpc.EmptyAuthStateResponse\"\x00BGZEsico-backend/internal/transport/reverse_grpc/pb/authstate/reverse_rpcb\x06proto3"

var (
	file_authstate_reverse_rpc_proto_rawDescOnce sync.Once
	file_authstate_reverse_rpc_proto_rawDescData []byte
)

func file_authstate_reverse_rpc_proto_rawDescGZIP() []byte {
	file_authstate_reverse_rpc_proto_rawDescOnce.Do(func() {
		file_authstate_reverse_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authstate_reverse_rpc_proto_rawDesc), len(file_authstate_reverse_rpc_proto_rawDesc)))
	})
	return file_authstate_reverse_rpc_proto_rawDescData
}

var file_authstate_reverse_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_authstate_reverse_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_authstate_reverse_rpc_proto_goTypes = []any{
	(AuthStateStatus)(0),                // 0: reverse_rpc.AuthStateStatus
	(*EmptyAuthStateResponse)(nil),      // 1: reverse_rpc.EmptyAuthStateResponse
	(*AuthState)(nil),                   // 2: reverse_rpc.AuthState
	(*GetAuthStateRequest)(nil),         // 3: reverse_rpc.GetAuthStateRequest
	(*GetAuthStateResponse)(nil),        // 4: reverse_rpc.GetAuthStateResponse
	(*UpsertAuthStateRequest)(nil),      // 5: reverse_rpc.UpsertAuthStateRequest
	(*UpsertAuthStateResponse)(nil),     // 6: reverse_rpc.UpsertAuthStateResponse
	(*MarkAuthStateExpiredRequest)(nil), // 7: reverse_rpc.MarkAuthStateExpiredRequest
}
var file_authstate_reverse_rpc_proto_depIdxs = []int32{
	0, // 0: reverse_rpc.AuthState.status:type_name -> reverse_rpc.AuthStateStatus
	2, // 1: reverse_rpc.GetAuthStateResponse.auth_state:type_name -> reverse_rpc.AuthState
	0, // 2: reverse_rpc.UpsertAuthStateRequest.status:type_name -> reverse_rpc.AuthStateStatus
	3, // 3: reverse_rpc.ReverseAuthStateRPC.RpcGetAuthState:input_type -> reverse_rpc.GetAuthStateRequest
	5, // 4: reverse_rpc.ReverseAuthStateRPC.RpcUpsertAuthState:input_type -> reverse_rpc.UpsertAuthStateRequest
	7, // 5: reverse_rpc.ReverseAuthStateRPC.RpcMarkAuthStateExpired:input_type -> reverse_rpc.MarkAuthStateExpiredRequest
	4, // 6: reverse_rpc.ReverseAuthStateRPC.RpcGetAuthState:output_type -> reverse_rpc.GetAuthStateResponse
	6, // 7: reverse_rpc.ReverseAuthStateRPC.RpcUpsertAuthState:output_type -> reverse_rpc.UpsertAuthStateResponse
	1, // 8: reverse_rpc.ReverseAuthStateRPC.RpcMarkAuthStateExpired:output_type -> reverse_rpc.EmptyAuthStateResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_authstate_reverse_rpc_proto_init() }
func file_authstate_reverse_rpc_proto_init() {
	if File_authstate_reverse_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authstate_reverse_rpc_proto_rawDesc), len(file_authstate_reverse_rpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authstate_reverse_rpc_proto_goTypes,
		DependencyIndexes: file_authstate_reverse_rpc_proto_depIdxs,
		EnumInfos:         file_authstate_reverse_rpc_proto_enumTypes,
		MessageInfos:      file_authstate_reverse_rpc_proto_msgTypes,
	}.Build()
	File_authstate_reverse_rpc_proto = out.File
	file_authstate_reverse_rpc_proto_goTypes = nil
	file_authstate_reverse_rpc_proto_depIdxs = nil
}
