syntax = "proto3";

package reverse_rpc;
option go_package = "sico-backend/internal/transport/reverse_grpc/pb/llmhubs/reverse_rpc";

service ReverseLLMHubRPC {
    rpc RpcUploadArtifact(UploadArtifactRequest) returns (UploadArtifactResponse) {}
}

message UploadArtifactRequest {
    bytes content = 1;                  // @gotag: json:"content"
    string filename = 2;               // @gotag: json:"filename"
    string content_type = 3;           // @gotag: json:"contentType"
    string path_prefix = 4;            // @gotag: json:"pathPrefix"
    string artifact_type = 5;          // @gotag: json:"artifactType"
}

message UploadArtifactData {
    string storage_uri = 1;            // @gotag: json:"storageUri"
    string download_url = 2;           // @gotag: json:"downloadUrl"
    string filename = 3;               // @gotag: json:"filename"
    string content_type = 4;           // @gotag: json:"contentType"
    string artifact_type = 5;          // @gotag: json:"artifactType"
}

message UploadArtifactResponse {
    UploadArtifactData data = 1;       // @gotag: json:"data"
    int32 code = 253;                  // @gotag: json:"code"
    string msg = 254;                  // @gotag: json:"msg"
}
