// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"sico-backend/internal/store/project/internal/dal/model"
)

func newTProjectAsset(db *gorm.DB, opts ...gen.DOOption) tProjectAsset {
	_tProjectAsset := tProjectAsset{}

	_tProjectAsset.tProjectAssetDo.UseDB(db, opts...)
	_tProjectAsset.tProjectAssetDo.UseModel(&model.TProjectAsset{})

	tableName := _tProjectAsset.tProjectAssetDo.TableName()
	_tProjectAsset.ALL = field.NewAsterisk(tableName)
	_tProjectAsset.ID = field.NewInt64(tableName, "id")
	_tProjectAsset.ProjectID = field.NewString(tableName, "project_id")
	_tProjectAsset.ObjectKey = field.NewString(tableName, "object_key")
	_tProjectAsset.CreatorUsername = field.NewString(tableName, "creator_username")
	_tProjectAsset.CreatedAt = field.NewInt64(tableName, "created_at")
	_tProjectAsset.UpdatedAt = field.NewInt64(tableName, "updated_at")
	_tProjectAsset.DeletedAt = field.NewField(tableName, "deleted_at")
	_tProjectAsset.Extra = field.NewString(tableName, "extra")

	_tProjectAsset.fillFieldMap()

	return _tProjectAsset
}

// tProjectAsset Project Asset
type tProjectAsset struct {
	tProjectAssetDo

	ALL             field.Asterisk
	ID              field.Int64  // Primary Key ID
	ProjectID       field.String // Project ID
	ObjectKey       field.String // Object Key
	CreatorUsername field.String // Publisher Username
	CreatedAt       field.Int64  // Create Time in Milliseconds
	UpdatedAt       field.Int64  // Update Time in Milliseconds
	DeletedAt       field.Field  // Delete Time
	Extra           field.String // Extended fields

	fieldMap map[string]field.Expr
}

func (t tProjectAsset) Table(newTableName string) *tProjectAsset {
	t.tProjectAssetDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tProjectAsset) As(alias string) *tProjectAsset {
	t.tProjectAssetDo.DO = *(t.tProjectAssetDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tProjectAsset) updateTableName(table string) *tProjectAsset {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.ProjectID = field.NewString(table, "project_id")
	t.ObjectKey = field.NewString(table, "object_key")
	t.CreatorUsername = field.NewString(table, "creator_username")
	t.CreatedAt = field.NewInt64(table, "created_at")
	t.UpdatedAt = field.NewInt64(table, "updated_at")
	t.DeletedAt = field.NewField(table, "deleted_at")
	t.Extra = field.NewString(table, "extra")

	t.fillFieldMap()

	return t
}

func (t *tProjectAsset) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tProjectAsset) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 8)
	t.fieldMap["id"] = t.ID
	t.fieldMap["project_id"] = t.ProjectID
	t.fieldMap["object_key"] = t.ObjectKey
	t.fieldMap["creator_username"] = t.CreatorUsername
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["deleted_at"] = t.DeletedAt
	t.fieldMap["extra"] = t.Extra
}

func (t tProjectAsset) clone(db *gorm.DB) tProjectAsset {
	t.tProjectAssetDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tProjectAsset) replaceDB(db *gorm.DB) tProjectAsset {
	t.tProjectAssetDo.ReplaceDB(db)
	return t
}

type tProjectAssetDo struct{ gen.DO }

type ITProjectAssetDo interface {
	gen.SubQuery
	Debug() ITProjectAssetDo
	WithContext(ctx context.Context) ITProjectAssetDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITProjectAssetDo
	WriteDB() ITProjectAssetDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITProjectAssetDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITProjectAssetDo
	Not(conds ...gen.Condition) ITProjectAssetDo
	Or(conds ...gen.Condition) ITProjectAssetDo
	Select(conds ...field.Expr) ITProjectAssetDo
	Where(conds ...gen.Condition) ITProjectAssetDo
	Order(conds ...field.Expr) ITProjectAssetDo
	Distinct(cols ...field.Expr) ITProjectAssetDo
	Omit(cols ...field.Expr) ITProjectAssetDo
	Join(table schema.Tabler, on ...field.Expr) ITProjectAssetDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITProjectAssetDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITProjectAssetDo
	Group(cols ...field.Expr) ITProjectAssetDo
	Having(conds ...gen.Condition) ITProjectAssetDo
	Limit(limit int) ITProjectAssetDo
	Offset(offset int) ITProjectAssetDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITProjectAssetDo
	Unscoped() ITProjectAssetDo
	Create(values ...*model.TProjectAsset) error
	CreateInBatches(values []*model.TProjectAsset, batchSize int) error
	Save(values ...*model.TProjectAsset) error
	First() (*model.TProjectAsset, error)
	Take() (*model.TProjectAsset, error)
	Last() (*model.TProjectAsset, error)
	Find() ([]*model.TProjectAsset, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TProjectAsset, err error)
	FindInBatches(result *[]*model.TProjectAsset, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TProjectAsset) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITProjectAssetDo
	Assign(attrs ...field.AssignExpr) ITProjectAssetDo
	Joins(fields ...field.RelationField) ITProjectAssetDo
	Preload(fields ...field.RelationField) ITProjectAssetDo
	FirstOrInit() (*model.TProjectAsset, error)
	FirstOrCreate() (*model.TProjectAsset, error)
	FindByPage(offset int, limit int) (result []*model.TProjectAsset, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITProjectAssetDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tProjectAssetDo) Debug() ITProjectAssetDo {
	return t.withDO(t.DO.Debug())
}

func (t tProjectAssetDo) WithContext(ctx context.Context) ITProjectAssetDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tProjectAssetDo) ReadDB() ITProjectAssetDo {
	return t.Clauses(dbresolver.Read)
}

func (t tProjectAssetDo) WriteDB() ITProjectAssetDo {
	return t.Clauses(dbresolver.Write)
}

func (t tProjectAssetDo) Session(config *gorm.Session) ITProjectAssetDo {
	return t.withDO(t.DO.Session(config))
}

func (t tProjectAssetDo) Clauses(conds ...clause.Expression) ITProjectAssetDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tProjectAssetDo) Returning(value interface{}, columns ...string) ITProjectAssetDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tProjectAssetDo) Not(conds ...gen.Condition) ITProjectAssetDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tProjectAssetDo) Or(conds ...gen.Condition) ITProjectAssetDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tProjectAssetDo) Select(conds ...field.Expr) ITProjectAssetDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tProjectAssetDo) Where(conds ...gen.Condition) ITProjectAssetDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tProjectAssetDo) Order(conds ...field.Expr) ITProjectAssetDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tProjectAssetDo) Distinct(cols ...field.Expr) ITProjectAssetDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tProjectAssetDo) Omit(cols ...field.Expr) ITProjectAssetDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tProjectAssetDo) Join(table schema.Tabler, on ...field.Expr) ITProjectAssetDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tProjectAssetDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITProjectAssetDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tProjectAssetDo) RightJoin(table schema.Tabler, on ...field.Expr) ITProjectAssetDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tProjectAssetDo) Group(cols ...field.Expr) ITProjectAssetDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tProjectAssetDo) Having(conds ...gen.Condition) ITProjectAssetDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tProjectAssetDo) Limit(limit int) ITProjectAssetDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tProjectAssetDo) Offset(offset int) ITProjectAssetDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tProjectAssetDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITProjectAssetDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tProjectAssetDo) Unscoped() ITProjectAssetDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tProjectAssetDo) Create(values ...*model.TProjectAsset) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tProjectAssetDo) CreateInBatches(values []*model.TProjectAsset, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tProjectAssetDo) Save(values ...*model.TProjectAsset) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tProjectAssetDo) First() (*model.TProjectAsset, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TProjectAsset), nil
	}
}

func (t tProjectAssetDo) Take() (*model.TProjectAsset, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TProjectAsset), nil
	}
}

func (t tProjectAssetDo) Last() (*model.TProjectAsset, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TProjectAsset), nil
	}
}

func (t tProjectAssetDo) Find() ([]*model.TProjectAsset, error) {
	result, err := t.DO.Find()
	return result.([]*model.TProjectAsset), err
}

func (t tProjectAssetDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TProjectAsset, err error) {
	buf := make([]*model.TProjectAsset, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tProjectAssetDo) FindInBatches(result *[]*model.TProjectAsset, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tProjectAssetDo) Attrs(attrs ...field.AssignExpr) ITProjectAssetDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tProjectAssetDo) Assign(attrs ...field.AssignExpr) ITProjectAssetDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tProjectAssetDo) Joins(fields ...field.RelationField) ITProjectAssetDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tProjectAssetDo) Preload(fields ...field.RelationField) ITProjectAssetDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tProjectAssetDo) FirstOrInit() (*model.TProjectAsset, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TProjectAsset), nil
	}
}

func (t tProjectAssetDo) FirstOrCreate() (*model.TProjectAsset, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TProjectAsset), nil
	}
}

func (t tProjectAssetDo) FindByPage(offset int, limit int) (result []*model.TProjectAsset, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tProjectAssetDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tProjectAssetDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tProjectAssetDo) Delete(models ...*model.TProjectAsset) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tProjectAssetDo) withDO(do gen.Dao) *tProjectAssetDo {
	t.DO = *do.(*gen.DO)
	return t
}
