// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q           = new(Query)
	TCasbinRule *tCasbinRule
	TUser       *tUser
	TUserRole   *tUserRole
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	TCasbinRule = &Q.TCasbinRule
	TUser = &Q.TUser
	TUserRole = &Q.TUserRole
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:          db,
		TCasbinRule: newTCasbinRule(db, opts...),
		TUser:       newTUser(db, opts...),
		TUserRole:   newTUserRole(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	TCasbinRule tCasbinRule
	TUser       tUser
	TUserRole   tUserRole
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		TCasbinRule: q.TCasbinRule.clone(db),
		TUser:       q.TUser.clone(db),
		TUserRole:   q.TUserRole.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		TCasbinRule: q.TCasbinRule.replaceDB(db),
		TUser:       q.TUser.replaceDB(db),
		TUserRole:   q.TUserRole.replaceDB(db),
	}
}

type queryCtx struct {
	TCasbinRule ITCasbinRuleDo
	TUser       ITUserDo
	TUserRole   ITUserRoleDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		TCasbinRule: q.TCasbinRule.WithContext(ctx),
		TUser:       q.TUser.WithContext(ctx),
		TUserRole:   q.TUserRole.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
