// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"sico-backend/internal/store/rbac/internal/dal/model"
)

func newTCasbinRule(db *gorm.DB, opts ...gen.DOOption) tCasbinRule {
	_tCasbinRule := tCasbinRule{}

	_tCasbinRule.tCasbinRuleDo.UseDB(db, opts...)
	_tCasbinRule.tCasbinRuleDo.UseModel(&model.TCasbinRule{})

	tableName := _tCasbinRule.tCasbinRuleDo.TableName()
	_tCasbinRule.ALL = field.NewAsterisk(tableName)
	_tCasbinRule.ID = field.NewInt64(tableName, "id")
	_tCasbinRule.Ptype = field.NewString(tableName, "ptype")
	_tCasbinRule.V0 = field.NewString(tableName, "v0")
	_tCasbinRule.V1 = field.NewString(tableName, "v1")
	_tCasbinRule.V2 = field.NewString(tableName, "v2")
	_tCasbinRule.V3 = field.NewString(tableName, "v3")
	_tCasbinRule.V4 = field.NewString(tableName, "v4")
	_tCasbinRule.V5 = field.NewString(tableName, "v5")

	_tCasbinRule.fillFieldMap()

	return _tCasbinRule
}

// tCasbinRule Casbin policy storage
type tCasbinRule struct {
	tCasbinRuleDo

	ALL   field.Asterisk
	ID    field.Int64
	Ptype field.String
	V0    field.String
	V1    field.String
	V2    field.String
	V3    field.String
	V4    field.String
	V5    field.String

	fieldMap map[string]field.Expr
}

func (t tCasbinRule) Table(newTableName string) *tCasbinRule {
	t.tCasbinRuleDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tCasbinRule) As(alias string) *tCasbinRule {
	t.tCasbinRuleDo.DO = *(t.tCasbinRuleDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tCasbinRule) updateTableName(table string) *tCasbinRule {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.Ptype = field.NewString(table, "ptype")
	t.V0 = field.NewString(table, "v0")
	t.V1 = field.NewString(table, "v1")
	t.V2 = field.NewString(table, "v2")
	t.V3 = field.NewString(table, "v3")
	t.V4 = field.NewString(table, "v4")
	t.V5 = field.NewString(table, "v5")

	t.fillFieldMap()

	return t
}

func (t *tCasbinRule) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tCasbinRule) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 8)
	t.fieldMap["id"] = t.ID
	t.fieldMap["ptype"] = t.Ptype
	t.fieldMap["v0"] = t.V0
	t.fieldMap["v1"] = t.V1
	t.fieldMap["v2"] = t.V2
	t.fieldMap["v3"] = t.V3
	t.fieldMap["v4"] = t.V4
	t.fieldMap["v5"] = t.V5
}

func (t tCasbinRule) clone(db *gorm.DB) tCasbinRule {
	t.tCasbinRuleDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tCasbinRule) replaceDB(db *gorm.DB) tCasbinRule {
	t.tCasbinRuleDo.ReplaceDB(db)
	return t
}

type tCasbinRuleDo struct{ gen.DO }

type ITCasbinRuleDo interface {
	gen.SubQuery
	Debug() ITCasbinRuleDo
	WithContext(ctx context.Context) ITCasbinRuleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITCasbinRuleDo
	WriteDB() ITCasbinRuleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITCasbinRuleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITCasbinRuleDo
	Not(conds ...gen.Condition) ITCasbinRuleDo
	Or(conds ...gen.Condition) ITCasbinRuleDo
	Select(conds ...field.Expr) ITCasbinRuleDo
	Where(conds ...gen.Condition) ITCasbinRuleDo
	Order(conds ...field.Expr) ITCasbinRuleDo
	Distinct(cols ...field.Expr) ITCasbinRuleDo
	Omit(cols ...field.Expr) ITCasbinRuleDo
	Join(table schema.Tabler, on ...field.Expr) ITCasbinRuleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITCasbinRuleDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITCasbinRuleDo
	Group(cols ...field.Expr) ITCasbinRuleDo
	Having(conds ...gen.Condition) ITCasbinRuleDo
	Limit(limit int) ITCasbinRuleDo
	Offset(offset int) ITCasbinRuleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITCasbinRuleDo
	Unscoped() ITCasbinRuleDo
	Create(values ...*model.TCasbinRule) error
	CreateInBatches(values []*model.TCasbinRule, batchSize int) error
	Save(values ...*model.TCasbinRule) error
	First() (*model.TCasbinRule, error)
	Take() (*model.TCasbinRule, error)
	Last() (*model.TCasbinRule, error)
	Find() ([]*model.TCasbinRule, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TCasbinRule, err error)
	FindInBatches(result *[]*model.TCasbinRule, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TCasbinRule) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITCasbinRuleDo
	Assign(attrs ...field.AssignExpr) ITCasbinRuleDo
	Joins(fields ...field.RelationField) ITCasbinRuleDo
	Preload(fields ...field.RelationField) ITCasbinRuleDo
	FirstOrInit() (*model.TCasbinRule, error)
	FirstOrCreate() (*model.TCasbinRule, error)
	FindByPage(offset int, limit int) (result []*model.TCasbinRule, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITCasbinRuleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tCasbinRuleDo) Debug() ITCasbinRuleDo {
	return t.withDO(t.DO.Debug())
}

func (t tCasbinRuleDo) WithContext(ctx context.Context) ITCasbinRuleDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tCasbinRuleDo) ReadDB() ITCasbinRuleDo {
	return t.Clauses(dbresolver.Read)
}

func (t tCasbinRuleDo) WriteDB() ITCasbinRuleDo {
	return t.Clauses(dbresolver.Write)
}

func (t tCasbinRuleDo) Session(config *gorm.Session) ITCasbinRuleDo {
	return t.withDO(t.DO.Session(config))
}

func (t tCasbinRuleDo) Clauses(conds ...clause.Expression) ITCasbinRuleDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tCasbinRuleDo) Returning(value interface{}, columns ...string) ITCasbinRuleDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tCasbinRuleDo) Not(conds ...gen.Condition) ITCasbinRuleDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tCasbinRuleDo) Or(conds ...gen.Condition) ITCasbinRuleDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tCasbinRuleDo) Select(conds ...field.Expr) ITCasbinRuleDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tCasbinRuleDo) Where(conds ...gen.Condition) ITCasbinRuleDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tCasbinRuleDo) Order(conds ...field.Expr) ITCasbinRuleDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tCasbinRuleDo) Distinct(cols ...field.Expr) ITCasbinRuleDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tCasbinRuleDo) Omit(cols ...field.Expr) ITCasbinRuleDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tCasbinRuleDo) Join(table schema.Tabler, on ...field.Expr) ITCasbinRuleDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tCasbinRuleDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITCasbinRuleDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tCasbinRuleDo) RightJoin(table schema.Tabler, on ...field.Expr) ITCasbinRuleDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tCasbinRuleDo) Group(cols ...field.Expr) ITCasbinRuleDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tCasbinRuleDo) Having(conds ...gen.Condition) ITCasbinRuleDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tCasbinRuleDo) Limit(limit int) ITCasbinRuleDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tCasbinRuleDo) Offset(offset int) ITCasbinRuleDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tCasbinRuleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITCasbinRuleDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tCasbinRuleDo) Unscoped() ITCasbinRuleDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tCasbinRuleDo) Create(values ...*model.TCasbinRule) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tCasbinRuleDo) CreateInBatches(values []*model.TCasbinRule, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tCasbinRuleDo) Save(values ...*model.TCasbinRule) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tCasbinRuleDo) First() (*model.TCasbinRule, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TCasbinRule), nil
	}
}

func (t tCasbinRuleDo) Take() (*model.TCasbinRule, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TCasbinRule), nil
	}
}

func (t tCasbinRuleDo) Last() (*model.TCasbinRule, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TCasbinRule), nil
	}
}

func (t tCasbinRuleDo) Find() ([]*model.TCasbinRule, error) {
	result, err := t.DO.Find()
	return result.([]*model.TCasbinRule), err
}

func (t tCasbinRuleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TCasbinRule, err error) {
	buf := make([]*model.TCasbinRule, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tCasbinRuleDo) FindInBatches(result *[]*model.TCasbinRule, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tCasbinRuleDo) Attrs(attrs ...field.AssignExpr) ITCasbinRuleDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tCasbinRuleDo) Assign(attrs ...field.AssignExpr) ITCasbinRuleDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tCasbinRuleDo) Joins(fields ...field.RelationField) ITCasbinRuleDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tCasbinRuleDo) Preload(fields ...field.RelationField) ITCasbinRuleDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tCasbinRuleDo) FirstOrInit() (*model.TCasbinRule, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TCasbinRule), nil
	}
}

func (t tCasbinRuleDo) FirstOrCreate() (*model.TCasbinRule, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TCasbinRule), nil
	}
}

func (t tCasbinRuleDo) FindByPage(offset int, limit int) (result []*model.TCasbinRule, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tCasbinRuleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tCasbinRuleDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tCasbinRuleDo) Delete(models ...*model.TCasbinRule) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tCasbinRuleDo) withDO(do gen.Dao) *tCasbinRuleDo {
	t.DO = *do.(*gen.DO)
	return t
}
