// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTModelRegistrySecret = "t_model_registry_secret"

// TModelRegistrySecret Model registry secrets storage
type TModelRegistrySecret struct {
	ID              int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:Primary key" json:"id"`                                 // Primary key
	ModelRegistryID int64  `gorm:"column:model_registry_id;not null;comment:FK to t_model_registry" json:"model_registry_id"`             // FK to t_model_registry
	SecretKey       string `gorm:"column:secret_key;not null;comment:Secret identifier, e.g. bearer_token, api_key" json:"secret_key"`    // Secret identifier, e.g. bearer_token, api_key
	SecretValue     string `gorm:"column:secret_value;comment:Encrypted secret value" json:"secret_value"`                                // Encrypted secret value
	CreatedAt       int64  `gorm:"column:created_at;not null;autoCreateTime:milli;comment:Create time in milliseconds" json:"created_at"` // Create time in milliseconds
	UpdatedAt       int64  `gorm:"column:updated_at;not null;autoUpdateTime:milli;comment:Update time in milliseconds" json:"updated_at"` // Update time in milliseconds
}

// TableName TModelRegistrySecret's table name
func (*TModelRegistrySecret) TableName() string {
	return TableNameTModelRegistrySecret
}
