# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: knowledge/knowledge.proto, knowledge/rpc.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "CreateKnowledgeDocumentData",
    "CreateKnowledgeDocumentRequest",
    "CreateKnowledgeDocumentResponse",
    "CreateKnowledgeTagData",
    "CreateKnowledgeTagRequest",
    "CreateKnowledgeTagResponse",
    "DeleteKnowledgeDocumentRequest",
    "DeleteKnowledgeDocumentResponse",
    "DeleteKnowledgePlaybookRequest",
    "DeleteKnowledgePlaybookResponse",
    "DeleteKnowledgeTagRequest",
    "DeleteKnowledgeTagResponse",
    "ExtractDocumentResponse",
    "GetDocumentDetailsRequest",
    "GetDocumentDetailsResponse",
    "GetKnowledgeDocumentData",
    "GetKnowledgeDocumentDetailsData",
    "GetKnowledgeDocumentDetailsRequest",
    "GetKnowledgeDocumentDetailsResponse",
    "GetKnowledgeDocumentRequest",
    "GetKnowledgeDocumentResponse",
    "GetKnowledgePlaybookData",
    "GetKnowledgePlaybookDetailsData",
    "GetKnowledgePlaybookDetailsGrpcRequest",
    "GetKnowledgePlaybookDetailsGrpcResponse",
    "GetKnowledgePlaybookDetailsRequest",
    "GetKnowledgePlaybookDetailsResponse",
    "GetKnowledgePlaybookRequest",
    "GetKnowledgePlaybookResponse",
    "GetKnowledgeTagData",
    "GetKnowledgeTagRequest",
    "GetKnowledgeTagResponse",
    "KnowledgeDocument",
    "KnowledgeDocumentStatus",
    "KnowledgeDocumentType",
    "KnowledgeItem",
    "KnowledgeItemType",
    "KnowledgePlaybook",
    "KnowledgePlaybookExtraInfo",
    "KnowledgeServiceBase",
    "KnowledgeServiceStub",
    "KnowledgeTag",
    "ListKnowledgeDocumentData",
    "ListKnowledgeDocumentRequest",
    "ListKnowledgeDocumentResponse",
    "ListKnowledgeItemsData",
    "ListKnowledgeItemsRequest",
    "ListKnowledgeItemsResponse",
    "ListKnowledgePlaybookData",
    "ListKnowledgePlaybookRequest",
    "ListKnowledgePlaybookResponse",
    "ListKnowledgeTagData",
    "ListKnowledgeTagRequest",
    "ListKnowledgeTagResponse",
    "UpdateKnowledgeDocumentRequest",
    "UpdateKnowledgeDocumentResponse",
    "UpdateKnowledgePlaybookRequest",
    "UpdateKnowledgePlaybookResponse",
    "UpdateKnowledgeTagRequest",
    "UpdateKnowledgeTagResponse",
)

from dataclasses import dataclass
from typing import TYPE_CHECKING

import betterproto2
import grpc
import grpclib
from betterproto2 import grpclib as betterproto2_grpclib

from ..message_pool import default_message_pool

if TYPE_CHECKING:
    import grpclib.server

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class KnowledgeDocumentStatus(betterproto2.Enum):
    """
    Knowledge Document status
    """

    UNKNOWN = 0
    """
    @gotag: json:"KNOWLEDGE_DOCUMENT_STATUS_UNKNOWN"
    """

    FAILED = 1
    """
    @gotag: json:"KNOWLEDGE_DOCUMENT_STATUS_FAILED"
    """

    UPLOADED = 2
    """
    @gotag: json:"KNOWLEDGE_DOCUMENT_STATUS_UPLOADED"
    """

    INGESTED = 3
    """
    @gotag: json:"KNOWLEDGE_DOCUMENT_STATUS_INGESTED"
    """

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "KNOWLEDGE_DOCUMENT_STATUS_UNKNOWN",
            1: "KNOWLEDGE_DOCUMENT_STATUS_FAILED",
            2: "KNOWLEDGE_DOCUMENT_STATUS_UPLOADED",
            3: "KNOWLEDGE_DOCUMENT_STATUS_INGESTED",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "KNOWLEDGE_DOCUMENT_STATUS_UNKNOWN": 0,
            "KNOWLEDGE_DOCUMENT_STATUS_FAILED": 1,
            "KNOWLEDGE_DOCUMENT_STATUS_UPLOADED": 2,
            "KNOWLEDGE_DOCUMENT_STATUS_INGESTED": 3,
        }


class KnowledgeDocumentType(betterproto2.Enum):
    """
    Knowledge Document type
    """

    UNKNOWN = 0
    """
    @gotag: json:"KNOWLEDGE_DOCUMENT_TYPE_UNKNOWN"
    """

    FILE = 1
    """
    @gotag: json:"KNOWLEDGE_DOCUMENT_TYPE_FILE"
    """

    LINK = 2
    """
    @gotag: json:"KNOWLEDGE_DOCUMENT_TYPE_LINK"
    """

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "KNOWLEDGE_DOCUMENT_TYPE_UNKNOWN",
            1: "KNOWLEDGE_DOCUMENT_TYPE_FILE",
            2: "KNOWLEDGE_DOCUMENT_TYPE_LINK",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "KNOWLEDGE_DOCUMENT_TYPE_UNKNOWN": 0,
            "KNOWLEDGE_DOCUMENT_TYPE_FILE": 1,
            "KNOWLEDGE_DOCUMENT_TYPE_LINK": 2,
        }


class KnowledgeItemType(betterproto2.Enum):
    """
    Unified knowledge item type
    """

    UNKNOWN = 0
    """
    @gotag: json:"KNOWLEDGE_ITEM_TYPE_UNKNOWN"
    """

    DOCUMENT = 1
    """
    @gotag: json:"KNOWLEDGE_ITEM_TYPE_DOCUMENT"
    """

    PLAYBOOK = 2
    """
    @gotag: json:"KNOWLEDGE_ITEM_TYPE_PLAYBOOK"
    """

    DELIVERABLE = 3
    """
    @gotag: json:"KNOWLEDGE_ITEM_TYPE_DELIVERABLE"
    """

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "KNOWLEDGE_ITEM_TYPE_UNKNOWN",
            1: "KNOWLEDGE_ITEM_TYPE_DOCUMENT",
            2: "KNOWLEDGE_ITEM_TYPE_PLAYBOOK",
            3: "KNOWLEDGE_ITEM_TYPE_DELIVERABLE",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "KNOWLEDGE_ITEM_TYPE_UNKNOWN": 0,
            "KNOWLEDGE_ITEM_TYPE_DOCUMENT": 1,
            "KNOWLEDGE_ITEM_TYPE_PLAYBOOK": 2,
            "KNOWLEDGE_ITEM_TYPE_DELIVERABLE": 3,
        }


@dataclass(eq=False, repr=False)
class CreateKnowledgeDocumentData(betterproto2.Message):
    id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: json:"id"
    """


default_message_pool.register_message(
    "knowledge", "CreateKnowledgeDocumentData", CreateKnowledgeDocumentData
)


@dataclass(eq=False, repr=False)
class CreateKnowledgeDocumentRequest(betterproto2.Message):
    """
    Create Knowledge Document
    """

    project_id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: json:"projectId" form:"projectId"
    """

    agent_id: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    @gotag: json:"agentId" form:"agentId"
    """

    asset_id: "int" = betterproto2.field(3, betterproto2.TYPE_INT64)
    """
    @gotag: json:"assetId" form:"assetId"
    """

    link_url: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)
    """
    @gotag: json:"linkUrl" form:"linkUrl" binding:"max=2048"
    """

    document_type: "KnowledgeDocumentType" = betterproto2.field(
        5, betterproto2.TYPE_ENUM, default_factory=lambda: KnowledgeDocumentType(0)
    )
    """
    @gotag: json:"documentType" form:"documentType" binding:"required"
    """

    tag_ids: "list[int]" = betterproto2.field(7, betterproto2.TYPE_INT64, repeated=True)
    """
    @gotag: json:"tagIds" form:"tagIds"
    """

    icon_uri: "str" = betterproto2.field(8, betterproto2.TYPE_STRING)
    """
    @gotag: json:"iconUri" form:"iconUri" binding:"max=256"
    """

    name: "str" = betterproto2.field(9, betterproto2.TYPE_STRING)
    """
    @gotag: json:"name" form:"name" binding:"max=256"
    """


default_message_pool.register_message(
    "knowledge", "CreateKnowledgeDocumentRequest", CreateKnowledgeDocumentRequest
)


@dataclass(eq=False, repr=False)
class CreateKnowledgeDocumentResponse(betterproto2.Message):
    data: "CreateKnowledgeDocumentData | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    @gotag: json:"data"
    """

    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)
    """
    @gotag: json:"code"
    """

    msg: "str" = betterproto2.field(254, betterproto2.TYPE_STRING)
    """
    @gotag: json:"msg"
    """


default_message_pool.register_message(
    "knowledge", "CreateKnowledgeDocumentResponse", CreateKnowledgeDocumentResponse
)


@dataclass(eq=False, repr=False)
class CreateKnowledgeTagData(betterproto2.Message):
    id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: json:"id"
    """


default_message_pool.register_message(
    "knowledge", "CreateKnowledgeTagData", CreateKnowledgeTagData
)


@dataclass(eq=False, repr=False)
class CreateKnowledgeTagRequest(betterproto2.Message):
    """
    Create Knowledge Tag
    """

    project_id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: json:"projectId" form:"projectId" binding:"required"
    """

    name: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    @gotag: json:"name" form:"name" binding:"required,max=256"
    """

    description: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    """
    @gotag: json:"description" form:"description"
    """


default_message_pool.register_message(
    "knowledge", "CreateKnowledgeTagRequest", CreateKnowledgeTagRequest
)


@dataclass(eq=False, repr=False)
class CreateKnowledgeTagResponse(betterproto2.Message):
    data: "CreateKnowledgeTagData | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    @gotag: json:"data"
    """

    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)
    """
    @gotag: json:"code"
    """

    msg: "str" = betterproto2.field(254, betterproto2.TYPE_STRING)
    """
    @gotag: json:"msg"
    """


default_message_pool.register_message(
    "knowledge", "CreateKnowledgeTagResponse", CreateKnowledgeTagResponse
)


@dataclass(eq=False, repr=False)
class DeleteKnowledgeDocumentRequest(betterproto2.Message):
    """
    Delete Knowledge Document
    """

    id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: form:"id" binding:"required"
    """


default_message_pool.register_message(
    "knowledge", "DeleteKnowledgeDocumentRequest", DeleteKnowledgeDocumentRequest
)


@dataclass(eq=False, repr=False)
class DeleteKnowledgeDocumentResponse(betterproto2.Message):
    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)
    """
    @gotag: json:"code"
    """

    msg: "str" = betterproto2.field(254, betterproto2.TYPE_STRING)
    """
    @gotag: json:"msg"
    """


default_message_pool.register_message(
    "knowledge", "DeleteKnowledgeDocumentResponse", DeleteKnowledgeDocumentResponse
)


@dataclass(eq=False, repr=False)
class DeleteKnowledgePlaybookRequest(betterproto2.Message):
    """
    Delete Knowledge Playbook
    """

    id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: form:"id" binding:"required"
    """


default_message_pool.register_message(
    "knowledge", "DeleteKnowledgePlaybookRequest", DeleteKnowledgePlaybookRequest
)


@dataclass(eq=False, repr=False)
class DeleteKnowledgePlaybookResponse(betterproto2.Message):
    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)
    """
    @gotag: json:"code"
    """

    msg: "str" = betterproto2.field(254, betterproto2.TYPE_STRING)
    """
    @gotag: json:"msg"
    """


default_message_pool.register_message(
    "knowledge", "DeleteKnowledgePlaybookResponse", DeleteKnowledgePlaybookResponse
)


@dataclass(eq=False, repr=False)
class DeleteKnowledgeTagRequest(betterproto2.Message):
    """
    Delete Knowledge Tag
    """

    id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: form:"id" binding:"required"
    """


default_message_pool.register_message(
    "knowledge", "DeleteKnowledgeTagRequest", DeleteKnowledgeTagRequest
)


@dataclass(eq=False, repr=False)
class DeleteKnowledgeTagResponse(betterproto2.Message):
    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)
    """
    @gotag: json:"code"
    """

    msg: "str" = betterproto2.field(254, betterproto2.TYPE_STRING)
    """
    @gotag: json:"msg"
    """


default_message_pool.register_message(
    "knowledge", "DeleteKnowledgeTagResponse", DeleteKnowledgeTagResponse
)


@dataclass(eq=False, repr=False)
class ExtractDocumentResponse(betterproto2.Message):
    message: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    """
    @gotag: json:"message"
    """

    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)
    """
    @gotag: json:"code"
    """


default_message_pool.register_message(
    "knowledge", "ExtractDocumentResponse", ExtractDocumentResponse
)


@dataclass(eq=False, repr=False)
class GetDocumentDetailsRequest(betterproto2.Message):
    document_id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: json:"documentId"
    """

    project_id: "int" = betterproto2.field(2, betterproto2.TYPE_INT64)
    """
    @gotag: json:"projectId"
    """

    agent_id: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    """
    @gotag: json:"agentId"
    """


default_message_pool.register_message(
    "knowledge", "GetDocumentDetailsRequest", GetDocumentDetailsRequest
)


@dataclass(eq=False, repr=False)
class GetDocumentDetailsResponse(betterproto2.Message):
    summary: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    """
    @gotag: json:"summary"
    """

    full_text: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    @gotag: json:"fullText"
    """

    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)
    """
    @gotag: json:"code"
    """

    msg: "str" = betterproto2.field(254, betterproto2.TYPE_STRING)
    """
    @gotag: json:"msg"
    """


default_message_pool.register_message(
    "knowledge", "GetDocumentDetailsResponse", GetDocumentDetailsResponse
)


@dataclass(eq=False, repr=False)
class GetKnowledgeDocumentData(betterproto2.Message):
    document: "KnowledgeDocument | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    @gotag: json:"document"
    """


default_message_pool.register_message(
    "knowledge", "GetKnowledgeDocumentData", GetKnowledgeDocumentData
)


@dataclass(eq=False, repr=False)
class GetKnowledgeDocumentDetailsData(betterproto2.Message):
    summary: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    """
    @gotag: json:"summary"
    """

    full_text: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    @gotag: json:"fullText"
    """


default_message_pool.register_message(
    "knowledge", "GetKnowledgeDocumentDetailsData", GetKnowledgeDocumentDetailsData
)


@dataclass(eq=False, repr=False)
class GetKnowledgeDocumentDetailsRequest(betterproto2.Message):
    """
    Get Knowledge Document Details (summary and full text)
    """

    id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: form:"id" binding:"required"
    """


default_message_pool.register_message(
    "knowledge",
    "GetKnowledgeDocumentDetailsRequest",
    GetKnowledgeDocumentDetailsRequest,
)


@dataclass(eq=False, repr=False)
class GetKnowledgeDocumentDetailsResponse(betterproto2.Message):
    data: "GetKnowledgeDocumentDetailsData | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    @gotag: json:"data"
    """

    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)
    """
    @gotag: json:"code"
    """

    msg: "str" = betterproto2.field(254, betterproto2.TYPE_STRING)
    """
    @gotag: json:"msg"
    """


default_message_pool.register_message(
    "knowledge",
    "GetKnowledgeDocumentDetailsResponse",
    GetKnowledgeDocumentDetailsResponse,
)


@dataclass(eq=False, repr=False)
class GetKnowledgeDocumentRequest(betterproto2.Message):
    """
    Get Knowledge Document
    """

    id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: form:"id" binding:"required"
    """


default_message_pool.register_message(
    "knowledge", "GetKnowledgeDocumentRequest", GetKnowledgeDocumentRequest
)


@dataclass(eq=False, repr=False)
class GetKnowledgeDocumentResponse(betterproto2.Message):
    data: "GetKnowledgeDocumentData | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    @gotag: json:"data"
    """

    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)
    """
    @gotag: json:"code"
    """

    msg: "str" = betterproto2.field(254, betterproto2.TYPE_STRING)
    """
    @gotag: json:"msg"
    """


default_message_pool.register_message(
    "knowledge", "GetKnowledgeDocumentResponse", GetKnowledgeDocumentResponse
)


@dataclass(eq=False, repr=False)
class GetKnowledgePlaybookData(betterproto2.Message):
    playbook: "KnowledgePlaybook | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    @gotag: json:"playbook"
    """


default_message_pool.register_message(
    "knowledge", "GetKnowledgePlaybookData", GetKnowledgePlaybookData
)


@dataclass(eq=False, repr=False)
class GetKnowledgePlaybookDetailsData(betterproto2.Message):
    content: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    """
    @gotag: json:"content"
    """

    name: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    @gotag: json:"name"
    """


default_message_pool.register_message(
    "knowledge", "GetKnowledgePlaybookDetailsData", GetKnowledgePlaybookDetailsData
)


@dataclass(eq=False, repr=False)
class GetKnowledgePlaybookDetailsGrpcRequest(betterproto2.Message):
    playbook_id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: json:"playbookId"
    """

    project_id: "int" = betterproto2.field(2, betterproto2.TYPE_INT64)
    """
    @gotag: json:"projectId"
    """

    agent_instance_id: "int" = betterproto2.field(3, betterproto2.TYPE_INT64)
    """
    @gotag: json:"agentInstanceId"
    """


default_message_pool.register_message(
    "knowledge",
    "GetKnowledgePlaybookDetailsGrpcRequest",
    GetKnowledgePlaybookDetailsGrpcRequest,
)


@dataclass(eq=False, repr=False)
class GetKnowledgePlaybookDetailsGrpcResponse(betterproto2.Message):
    content: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    """
    @gotag: json:"content"
    """

    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)
    """
    @gotag: json:"code"
    """

    msg: "str" = betterproto2.field(254, betterproto2.TYPE_STRING)
    """
    @gotag: json:"msg"
    """


default_message_pool.register_message(
    "knowledge",
    "GetKnowledgePlaybookDetailsGrpcResponse",
    GetKnowledgePlaybookDetailsGrpcResponse,
)


@dataclass(eq=False, repr=False)
class GetKnowledgePlaybookDetailsRequest(betterproto2.Message):
    """
    Get Knowledge Playbook Details (content fetched from core via gRPC)
    """

    id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: form:"id" binding:"required"
    """


default_message_pool.register_message(
    "knowledge",
    "GetKnowledgePlaybookDetailsRequest",
    GetKnowledgePlaybookDetailsRequest,
)


@dataclass(eq=False, repr=False)
class GetKnowledgePlaybookDetailsResponse(betterproto2.Message):
    data: "GetKnowledgePlaybookDetailsData | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    @gotag: json:"data"
    """

    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)
    """
    @gotag: json:"code"
    """

    msg: "str" = betterproto2.field(254, betterproto2.TYPE_STRING)
    """
    @gotag: json:"msg"
    """


default_message_pool.register_message(
    "knowledge",
    "GetKnowledgePlaybookDetailsResponse",
    GetKnowledgePlaybookDetailsResponse,
)


@dataclass(eq=False, repr=False)
class GetKnowledgePlaybookRequest(betterproto2.Message):
    """
    Get Knowledge Playbook
    """

    id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: form:"id" binding:"required"
    """


default_message_pool.register_message(
    "knowledge", "GetKnowledgePlaybookRequest", GetKnowledgePlaybookRequest
)


@dataclass(eq=False, repr=False)
class GetKnowledgePlaybookResponse(betterproto2.Message):
    data: "GetKnowledgePlaybookData | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    @gotag: json:"data"
    """

    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)
    """
    @gotag: json:"code"
    """

    msg: "str" = betterproto2.field(254, betterproto2.TYPE_STRING)
    """
    @gotag: json:"msg"
    """


default_message_pool.register_message(
    "knowledge", "GetKnowledgePlaybookResponse", GetKnowledgePlaybookResponse
)


@dataclass(eq=False, repr=False)
class GetKnowledgeTagData(betterproto2.Message):
    tag: "KnowledgeTag | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    @gotag: json:"tag"
    """


default_message_pool.register_message(
    "knowledge", "GetKnowledgeTagData", GetKnowledgeTagData
)


@dataclass(eq=False, repr=False)
class GetKnowledgeTagRequest(betterproto2.Message):
    """
    Get Knowledge Tag
    """

    id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: form:"id" binding:"required"
    """


default_message_pool.register_message(
    "knowledge", "GetKnowledgeTagRequest", GetKnowledgeTagRequest
)


@dataclass(eq=False, repr=False)
class GetKnowledgeTagResponse(betterproto2.Message):
    data: "GetKnowledgeTagData | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    @gotag: json:"data"
    """

    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)
    """
    @gotag: json:"code"
    """

    msg: "str" = betterproto2.field(254, betterproto2.TYPE_STRING)
    """
    @gotag: json:"msg"
    """


default_message_pool.register_message(
    "knowledge", "GetKnowledgeTagResponse", GetKnowledgeTagResponse
)


@dataclass(eq=False, repr=False)
class KnowledgeDocument(betterproto2.Message):
    """
    Knowledge Document entity
    """

    id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: json:"id"
    """

    project_id: "int" = betterproto2.field(2, betterproto2.TYPE_INT64)
    """
    @gotag: json:"projectId"
    """

    agent_id: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    """
    @gotag: json:"agentId"
    """

    asset_id: "int" = betterproto2.field(4, betterproto2.TYPE_INT64)
    """
    @gotag: json:"assetId"
    """

    link_url: "str" = betterproto2.field(5, betterproto2.TYPE_STRING)
    """
    @gotag: json:"linkUrl"
    """

    document_type: "KnowledgeDocumentType" = betterproto2.field(
        6, betterproto2.TYPE_ENUM, default_factory=lambda: KnowledgeDocumentType(0)
    )
    """
    @gotag: json:"documentType"
    """

    status: "KnowledgeDocumentStatus" = betterproto2.field(
        7, betterproto2.TYPE_ENUM, default_factory=lambda: KnowledgeDocumentStatus(0)
    )
    """
    @gotag: json:"status"
    """

    fail_reason: "str" = betterproto2.field(8, betterproto2.TYPE_STRING)
    """
    @gotag: json:"failReason"
    """

    creator_username: "str" = betterproto2.field(9, betterproto2.TYPE_STRING)
    """
    @gotag: json:"creatorUsername"
    """

    created_at: "int" = betterproto2.field(10, betterproto2.TYPE_INT64)
    """
    @gotag: json:"createdAt"
    """

    updated_at: "int" = betterproto2.field(11, betterproto2.TYPE_INT64)
    """
    @gotag: json:"updatedAt"
    """

    attachment: "_common__.Attachment | None" = betterproto2.field(
        12, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    @gotag: json:"attachment"
    """

    tags: "list[KnowledgeTag]" = betterproto2.field(
        13, betterproto2.TYPE_MESSAGE, repeated=True
    )
    """
    @gotag: json:"tags"
    """

    icon_uri: "str" = betterproto2.field(14, betterproto2.TYPE_STRING)
    """
    @gotag: json:"iconUri"
    """

    icon_sas_url: "str" = betterproto2.field(15, betterproto2.TYPE_STRING)
    """
    @gotag: json:"iconSasUrl"
    """

    name: "str" = betterproto2.field(16, betterproto2.TYPE_STRING)
    """
    @gotag: json:"name"
    """


default_message_pool.register_message(
    "knowledge", "KnowledgeDocument", KnowledgeDocument
)


@dataclass(eq=False, repr=False)
class KnowledgeItem(betterproto2.Message):
    """
    KnowledgeItem represents a unified knowledge item (document, playbook, or deliverable).
    """

    type: "KnowledgeItemType" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: KnowledgeItemType(0)
    )
    """
    @gotag: json:"type"
    """

    document: "KnowledgeDocument | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    @gotag: json:"document,omitempty"
    """

    playbook: "KnowledgePlaybook | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    @gotag: json:"playbook,omitempty"
    """

    deliverable: "_project__.ProjectDeliverable | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    @gotag: json:"deliverable,omitempty"
    """

    updated_at: "int" = betterproto2.field(5, betterproto2.TYPE_INT64)
    """
    @gotag: json:"updatedAt"
    """


default_message_pool.register_message("knowledge", "KnowledgeItem", KnowledgeItem)


@dataclass(eq=False, repr=False)
class KnowledgePlaybook(betterproto2.Message):
    """
    Knowledge Playbook entity
    """

    id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: json:"id"
    """

    project_id: "int" = betterproto2.field(2, betterproto2.TYPE_INT64)
    """
    @gotag: json:"projectId"
    """

    agent_instance_id: "int" = betterproto2.field(3, betterproto2.TYPE_INT64)
    """
    @gotag: json:"agentInstanceId"
    """

    name: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)
    """
    @gotag: json:"name"
    """

    created_at: "int" = betterproto2.field(5, betterproto2.TYPE_INT64)
    """
    @gotag: json:"createdAt"
    """

    updated_at: "int" = betterproto2.field(6, betterproto2.TYPE_INT64)
    """
    @gotag: json:"updatedAt"
    """

    tags: "list[KnowledgeTag]" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, repeated=True
    )
    """
    @gotag: json:"tags"
    """

    extra_info: "KnowledgePlaybookExtraInfo | None" = betterproto2.field(
        8, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    @gotag: json:"extraInfo"
    """


default_message_pool.register_message(
    "knowledge", "KnowledgePlaybook", KnowledgePlaybook
)


@dataclass(eq=False, repr=False)
class KnowledgePlaybookExtraInfo(betterproto2.Message):
    """
    KnowledgePlaybookExtraInfo holds additional display information for a playbook.
    """

    agent_instance: "_common__.AgentInstanceDigest | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    @gotag: json:"agentInstance"
    """


default_message_pool.register_message(
    "knowledge", "KnowledgePlaybookExtraInfo", KnowledgePlaybookExtraInfo
)


@dataclass(eq=False, repr=False)
class KnowledgeTag(betterproto2.Message):
    """
    Knowledge Tag entity
    """

    id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: json:"id"
    """

    project_id: "int" = betterproto2.field(2, betterproto2.TYPE_INT64)
    """
    @gotag: json:"projectId"
    """

    name: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    """
    @gotag: json:"name"
    """

    description: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)
    """
    @gotag: json:"description"
    """

    creator_username: "str" = betterproto2.field(5, betterproto2.TYPE_STRING)
    """
    @gotag: json:"creatorUsername"
    """

    created_at: "int" = betterproto2.field(6, betterproto2.TYPE_INT64)
    """
    @gotag: json:"createdAt"
    """

    updated_at: "int" = betterproto2.field(7, betterproto2.TYPE_INT64)
    """
    @gotag: json:"updatedAt"
    """


default_message_pool.register_message("knowledge", "KnowledgeTag", KnowledgeTag)


@dataclass(eq=False, repr=False)
class ListKnowledgeDocumentData(betterproto2.Message):
    documents: "list[KnowledgeDocument]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )
    """
    @gotag: json:"documents"
    """

    total: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)
    """
    @gotag: json:"total"
    """

    has_next: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)
    """
    @gotag: json:"hasNext"
    """


default_message_pool.register_message(
    "knowledge", "ListKnowledgeDocumentData", ListKnowledgeDocumentData
)


@dataclass(eq=False, repr=False)
class ListKnowledgeDocumentRequest(betterproto2.Message):
    """
    List Knowledge Document
    """

    project_id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: form:"projectId"
    """

    agent_id: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    @gotag: form:"agentId"
    """

    asset_id: "int" = betterproto2.field(3, betterproto2.TYPE_INT64)
    """
    @gotag: form:"assetId"
    """

    link_url: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)
    """
    @gotag: form:"linkUrl" binding:"max=2048"
    """

    document_type: "KnowledgeDocumentType" = betterproto2.field(
        5, betterproto2.TYPE_ENUM, default_factory=lambda: KnowledgeDocumentType(0)
    )
    """
    @gotag: form:"documentType"
    """

    status: "KnowledgeDocumentStatus" = betterproto2.field(
        6, betterproto2.TYPE_ENUM, default_factory=lambda: KnowledgeDocumentStatus(0)
    )
    """
    @gotag: form:"status"
    """

    creator_username: "str" = betterproto2.field(7, betterproto2.TYPE_STRING)
    """
    @gotag: form:"creatorUsername"
    """

    page: "int" = betterproto2.field(8, betterproto2.TYPE_INT32)
    """
    @gotag: form:"page" binding:"required,min=1"
    """

    page_size: "int" = betterproto2.field(9, betterproto2.TYPE_INT32)
    """
    @gotag: form:"pageSize" binding:"required,min=1,max=100"
    """


default_message_pool.register_message(
    "knowledge", "ListKnowledgeDocumentRequest", ListKnowledgeDocumentRequest
)


@dataclass(eq=False, repr=False)
class ListKnowledgeDocumentResponse(betterproto2.Message):
    data: "ListKnowledgeDocumentData | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    @gotag: json:"data"
    """

    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)
    """
    @gotag: json:"code"
    """

    msg: "str" = betterproto2.field(254, betterproto2.TYPE_STRING)
    """
    @gotag: json:"msg"
    """


default_message_pool.register_message(
    "knowledge", "ListKnowledgeDocumentResponse", ListKnowledgeDocumentResponse
)


@dataclass(eq=False, repr=False)
class ListKnowledgeItemsData(betterproto2.Message):
    items: "list[KnowledgeItem]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )
    """
    @gotag: json:"items"
    """

    total: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)
    """
    @gotag: json:"total"
    """

    has_next: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)
    """
    @gotag: json:"hasNext"
    """


default_message_pool.register_message(
    "knowledge", "ListKnowledgeItemsData", ListKnowledgeItemsData
)


@dataclass(eq=False, repr=False)
class ListKnowledgeItemsRequest(betterproto2.Message):
    """
    List all knowledge items (documents, playbooks, deliverables) for a project.
    """

    project_id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: form:"projectId" binding:"required"
    """

    page: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)
    """
    @gotag: form:"page" binding:"required,min=1"
    """

    page_size: "int" = betterproto2.field(3, betterproto2.TYPE_INT32)
    """
    @gotag: form:"pageSize" binding:"required,min=1,max=100"
    """


default_message_pool.register_message(
    "knowledge", "ListKnowledgeItemsRequest", ListKnowledgeItemsRequest
)


@dataclass(eq=False, repr=False)
class ListKnowledgeItemsResponse(betterproto2.Message):
    data: "ListKnowledgeItemsData | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    @gotag: json:"data"
    """

    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)
    """
    @gotag: json:"code"
    """

    msg: "str" = betterproto2.field(254, betterproto2.TYPE_STRING)
    """
    @gotag: json:"msg"
    """


default_message_pool.register_message(
    "knowledge", "ListKnowledgeItemsResponse", ListKnowledgeItemsResponse
)


@dataclass(eq=False, repr=False)
class ListKnowledgePlaybookData(betterproto2.Message):
    playbooks: "list[KnowledgePlaybook]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )
    """
    @gotag: json:"playbooks"
    """

    total: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)
    """
    @gotag: json:"total"
    """

    has_next: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)
    """
    @gotag: json:"hasNext"
    """


default_message_pool.register_message(
    "knowledge", "ListKnowledgePlaybookData", ListKnowledgePlaybookData
)


@dataclass(eq=False, repr=False)
class ListKnowledgePlaybookRequest(betterproto2.Message):
    """
    List Knowledge Playbooks
    """

    project_id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: form:"projectId" binding:"required"
    """

    agent_instance_id: "int" = betterproto2.field(2, betterproto2.TYPE_INT64)
    """
    @gotag: form:"agentInstanceId"
    """

    page: "int" = betterproto2.field(3, betterproto2.TYPE_INT32)
    """
    @gotag: form:"page" binding:"required,min=1"
    """

    page_size: "int" = betterproto2.field(4, betterproto2.TYPE_INT32)
    """
    @gotag: form:"pageSize" binding:"required,min=1,max=100"
    """


default_message_pool.register_message(
    "knowledge", "ListKnowledgePlaybookRequest", ListKnowledgePlaybookRequest
)


@dataclass(eq=False, repr=False)
class ListKnowledgePlaybookResponse(betterproto2.Message):
    data: "ListKnowledgePlaybookData | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    @gotag: json:"data"
    """

    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)
    """
    @gotag: json:"code"
    """

    msg: "str" = betterproto2.field(254, betterproto2.TYPE_STRING)
    """
    @gotag: json:"msg"
    """


default_message_pool.register_message(
    "knowledge", "ListKnowledgePlaybookResponse", ListKnowledgePlaybookResponse
)


@dataclass(eq=False, repr=False)
class ListKnowledgeTagData(betterproto2.Message):
    tags: "list[KnowledgeTag]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )
    """
    @gotag: json:"tags"
    """

    total: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)
    """
    @gotag: json:"total"
    """

    has_next: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)
    """
    @gotag: json:"hasNext"
    """


default_message_pool.register_message(
    "knowledge", "ListKnowledgeTagData", ListKnowledgeTagData
)


@dataclass(eq=False, repr=False)
class ListKnowledgeTagRequest(betterproto2.Message):
    """
    List Knowledge Tags
    """

    project_id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: form:"projectId" binding:"required"
    """

    page: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)
    """
    @gotag: form:"page" binding:"required"
    """

    page_size: "int" = betterproto2.field(3, betterproto2.TYPE_INT32)
    """
    @gotag: form:"pageSize" binding:"required"
    """


default_message_pool.register_message(
    "knowledge", "ListKnowledgeTagRequest", ListKnowledgeTagRequest
)


@dataclass(eq=False, repr=False)
class ListKnowledgeTagResponse(betterproto2.Message):
    data: "ListKnowledgeTagData | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    @gotag: json:"data"
    """

    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)
    """
    @gotag: json:"code"
    """

    msg: "str" = betterproto2.field(254, betterproto2.TYPE_STRING)
    """
    @gotag: json:"msg"
    """


default_message_pool.register_message(
    "knowledge", "ListKnowledgeTagResponse", ListKnowledgeTagResponse
)


@dataclass(eq=False, repr=False)
class UpdateKnowledgeDocumentRequest(betterproto2.Message):
    """
    Update Knowledge Document
    """

    id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: json:"id" form:"id" binding:"required"
    """

    agent_id: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    @gotag: json:"agentId" form:"agentId"
    """

    asset_id: "int" = betterproto2.field(3, betterproto2.TYPE_INT64)
    """
    @gotag: json:"assetId" form:"assetId"
    """

    link_url: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)
    """
    @gotag: json:"linkUrl" form:"linkUrl" binding:"max=2048"
    """

    document_type: "KnowledgeDocumentType" = betterproto2.field(
        5, betterproto2.TYPE_ENUM, default_factory=lambda: KnowledgeDocumentType(0)
    )
    """
    @gotag: json:"documentType" form:"documentType"
    """

    status: "KnowledgeDocumentStatus" = betterproto2.field(
        6, betterproto2.TYPE_ENUM, default_factory=lambda: KnowledgeDocumentStatus(0)
    )
    """
    @gotag: json:"status" form:"status"
    """

    fail_reason: "str" = betterproto2.field(7, betterproto2.TYPE_STRING)
    """
    @gotag: json:"failReason" form:"failReason" binding:"max=1024"
    """

    tag_ids: "list[int]" = betterproto2.field(8, betterproto2.TYPE_INT64, repeated=True)
    """
    @gotag: json:"tagIds" form:"tagIds"
    """

    icon_uri: "str" = betterproto2.field(9, betterproto2.TYPE_STRING)
    """
    @gotag: json:"iconUri" form:"iconUri" binding:"max=256"
    """

    name: "str" = betterproto2.field(10, betterproto2.TYPE_STRING)
    """
    @gotag: json:"name" form:"name" binding:"max=256"
    """


default_message_pool.register_message(
    "knowledge", "UpdateKnowledgeDocumentRequest", UpdateKnowledgeDocumentRequest
)


@dataclass(eq=False, repr=False)
class UpdateKnowledgeDocumentResponse(betterproto2.Message):
    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)
    """
    @gotag: json:"code"
    """

    msg: "str" = betterproto2.field(254, betterproto2.TYPE_STRING)
    """
    @gotag: json:"msg"
    """


default_message_pool.register_message(
    "knowledge", "UpdateKnowledgeDocumentResponse", UpdateKnowledgeDocumentResponse
)


@dataclass(eq=False, repr=False)
class UpdateKnowledgePlaybookRequest(betterproto2.Message):
    """
    Update Knowledge Playbook (name and tags only)
    """

    id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: json:"id" form:"id" binding:"required"
    """

    name: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    @gotag: json:"name" form:"name" binding:"max=256"
    """

    tag_ids: "list[int]" = betterproto2.field(3, betterproto2.TYPE_INT64, repeated=True)
    """
    @gotag: json:"tagIds" form:"tagIds"
    """


default_message_pool.register_message(
    "knowledge", "UpdateKnowledgePlaybookRequest", UpdateKnowledgePlaybookRequest
)


@dataclass(eq=False, repr=False)
class UpdateKnowledgePlaybookResponse(betterproto2.Message):
    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)
    """
    @gotag: json:"code"
    """

    msg: "str" = betterproto2.field(254, betterproto2.TYPE_STRING)
    """
    @gotag: json:"msg"
    """


default_message_pool.register_message(
    "knowledge", "UpdateKnowledgePlaybookResponse", UpdateKnowledgePlaybookResponse
)


@dataclass(eq=False, repr=False)
class UpdateKnowledgeTagRequest(betterproto2.Message):
    """
    Update Knowledge Tag
    """

    id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: json:"id" form:"id" binding:"required"
    """

    name: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    @gotag: json:"name" form:"name" binding:"max=256"
    """

    description: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    """
    @gotag: json:"description" form:"description"
    """


default_message_pool.register_message(
    "knowledge", "UpdateKnowledgeTagRequest", UpdateKnowledgeTagRequest
)


@dataclass(eq=False, repr=False)
class UpdateKnowledgeTagResponse(betterproto2.Message):
    code: "int" = betterproto2.field(253, betterproto2.TYPE_INT32)
    """
    @gotag: json:"code"
    """

    msg: "str" = betterproto2.field(254, betterproto2.TYPE_STRING)
    """
    @gotag: json:"msg"
    """


default_message_pool.register_message(
    "knowledge", "UpdateKnowledgeTagResponse", UpdateKnowledgeTagResponse
)


class KnowledgeServiceStub:
    def __init__(self, channel: grpc.Channel):
        self._channel = channel

    def extract_document(
        self, message: "KnowledgeDocument"
    ) -> "ExtractDocumentResponse":
        return self._channel.unary_unary(
            "/knowledge.KnowledgeService/ExtractDocument",
            KnowledgeDocument.SerializeToString,
            ExtractDocumentResponse.FromString,
        )(message)

    def get_document_details(
        self, message: "GetDocumentDetailsRequest"
    ) -> "GetDocumentDetailsResponse":
        return self._channel.unary_unary(
            "/knowledge.KnowledgeService/GetDocumentDetails",
            GetDocumentDetailsRequest.SerializeToString,
            GetDocumentDetailsResponse.FromString,
        )(message)

    def get_playbook_details(
        self, message: "GetKnowledgePlaybookDetailsGrpcRequest"
    ) -> "GetKnowledgePlaybookDetailsGrpcResponse":
        return self._channel.unary_unary(
            "/knowledge.KnowledgeService/GetPlaybookDetails",
            GetKnowledgePlaybookDetailsGrpcRequest.SerializeToString,
            GetKnowledgePlaybookDetailsGrpcResponse.FromString,
        )(message)


from ...common import common as _common__
from ...project import project as _project__


class KnowledgeServiceBase(betterproto2_grpclib.ServiceBase):
    async def extract_document(
        self, message: "KnowledgeDocument"
    ) -> "ExtractDocumentResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_document_details(
        self, message: "GetDocumentDetailsRequest"
    ) -> "GetDocumentDetailsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_playbook_details(
        self, message: "GetKnowledgePlaybookDetailsGrpcRequest"
    ) -> "GetKnowledgePlaybookDetailsGrpcResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_extract_document(
        self,
        stream: "grpclib.server.Stream[KnowledgeDocument, ExtractDocumentResponse]",
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.extract_document(request)
        await stream.send_message(response)

    async def __rpc_get_document_details(
        self,
        stream: "grpclib.server.Stream[GetDocumentDetailsRequest, GetDocumentDetailsResponse]",
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.get_document_details(request)
        await stream.send_message(response)

    async def __rpc_get_playbook_details(
        self,
        stream: "grpclib.server.Stream[GetKnowledgePlaybookDetailsGrpcRequest, GetKnowledgePlaybookDetailsGrpcResponse]",
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.get_playbook_details(request)
        await stream.send_message(response)

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/knowledge.KnowledgeService/ExtractDocument": grpclib.const.Handler(
                self.__rpc_extract_document,
                grpclib.const.Cardinality.UNARY_UNARY,
                KnowledgeDocument,
                ExtractDocumentResponse,
            ),
            "/knowledge.KnowledgeService/GetDocumentDetails": grpclib.const.Handler(
                self.__rpc_get_document_details,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetDocumentDetailsRequest,
                GetDocumentDetailsResponse,
            ),
            "/knowledge.KnowledgeService/GetPlaybookDetails": grpclib.const.Handler(
                self.__rpc_get_playbook_details,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetKnowledgePlaybookDetailsGrpcRequest,
                GetKnowledgePlaybookDetailsGrpcResponse,
            ),
        }
