"""Create a user (if needed) and print a JWT for follow-up examples."""

from __future__ import annotations

import os
import time

from examples._shared.http import base_url, json_request, print_json


def main() -> None:
    email = os.environ.get("SICO_EXAMPLE_EMAIL", "").strip() or f"example+{int(time.time())}@sico.local"
    password = os.environ.get("SICO_EXAMPLE_PASSWORD", "sico-demo-123")

    create_payload = {
        "email": email,
        "password": password,
        "description": "Generated by examples.auth.register_and_login",
    }

    print(f"Base URL: {base_url()}")
    print(f"Using email: {email}")

    try:
        create_response = json_request(
            "/api/sico/rbac/user",
            method="POST",
            payload=create_payload,
        )
        print("\nCreate user response:")
        print_json(create_response)
    except RuntimeError as exc:
        print(f"\nCreate user skipped: {exc}")

    login_response = json_request(
        "/api/sico/rbac/login",
        method="POST",
        payload={"email": email, "password": password},
    )

    token_info = login_response["data"]["tokenInfo"]

    print("\nLogin response:")
    print_json(login_response)

    print("\nExports for follow-up examples:")
    print(f'export BASE_URL="{base_url()}"')
    print(f'export TOKEN="{token_info["accessToken"]}"')
    print(f'export SICO_EXAMPLE_EMAIL="{email}"')
    print(f'export SICO_EXAMPLE_PASSWORD="{password}"')


if __name__ == "__main__":
    main()
