# Copyright (c) 2026 Sico Authors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Create a user (if needed) and print a JWT for follow-up examples."""

from __future__ import annotations

import os
import time

from examples._shared.http import base_url, json_request, print_json


def main() -> None:
    email = os.environ.get("SICO_EXAMPLE_EMAIL", "").strip() or f"example+{int(time.time())}@sico.local"
    password = os.environ.get("SICO_EXAMPLE_PASSWORD", "sico-demo-123")

    create_payload = {
        "email": email,
        "password": password,
        "description": "Generated by examples.auth.register_and_login",
    }

    print(f"Base URL: {base_url()}")
    print(f"Using email: {email}")

    try:
        create_response = json_request(
            "/api/sico/rbac/user",
            method="POST",
            payload=create_payload,
        )
        print("\nCreate user response:")
        print_json(create_response)
    except RuntimeError as exc:
        print(f"\nCreate user skipped: {exc}")

    login_response = json_request(
        "/api/sico/rbac/login",
        method="POST",
        payload={"email": email, "password": password},
    )

    token_info = login_response["data"]["tokenInfo"]

    print("\nLogin response:")
    print_json(login_response)

    print("\nExports for follow-up examples:")
    print(f'export BASE_URL="{base_url()}"')
    print(f'export TOKEN="{token_info["accessToken"]}"')
    print(f'export SICO_EXAMPLE_EMAIL="{email}"')
    print(f'export SICO_EXAMPLE_PASSWORD="{password}"')


if __name__ == "__main__":
    main()
