replicaCount: 1

image:
  repository: localhost:5000/sico/sico-frontend
  tag: local
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  requests:
    memory: 32Mi
    cpu: 25m
  limits:
    memory: 128Mi
    cpu: 200m

nodeSelector: {}
tolerations: []
affinity: {}
