// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameTProject = "t_project"

// TProject Project Table
type TProject struct {
	ID              int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:Primary Key ID" json:"id"`                               // Primary Key ID
	OwnerUsername   string         `gorm:"column:owner_username;not null;default:0;comment:Owner Username" json:"owner_username"`                  // Owner Username
	Name            string         `gorm:"column:name;not null;comment:Project Name" json:"name"`                                                  // Project Name
	Description     string         `gorm:"column:description;not null;comment:Project Description" json:"description"`                             // Project Description
	IconURI         string         `gorm:"column:icon_uri;not null;comment:Project icon URI" json:"icon_uri"`                                      // Project icon URI
	CreatorUsername string         `gorm:"column:creator_username;not null;default:0;comment:Creator Username" json:"creator_username"`            // Creator Username
	CreatedAt       int64          `gorm:"column:created_at;not null;autoCreateTime:milli;comment:Creation Time (Milliseconds)" json:"created_at"` // Creation Time (Milliseconds)
	UpdatedAt       int64          `gorm:"column:updated_at;not null;autoUpdateTime:milli;comment:Update Time (Milliseconds)" json:"updated_at"`   // Update Time (Milliseconds)
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at;comment:Delete Time" json:"deleted_at"`                                                // Delete Time
}

// TableName TProject's table name
func (*TProject) TableName() string {
	return TableNameTProject
}
