// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameTKnowledgePlaybookTag = "t_knowledge_playbook_tag"

// TKnowledgePlaybookTag Playbook tag relation table
type TKnowledgePlaybookTag struct {
	ID                  int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:Primary key" json:"id"`                                 // Primary key
	KnowledgePlaybookID int64          `gorm:"column:knowledge_playbook_id;not null;comment:Knowledge playbook ID" json:"knowledge_playbook_id"`      // Knowledge playbook ID
	KnowledgeTagID      int64          `gorm:"column:knowledge_tag_id;not null;comment:Knowledge tag ID" json:"knowledge_tag_id"`                     // Knowledge tag ID
	CreatedAt           int64          `gorm:"column:created_at;not null;autoCreateTime:milli;comment:Create Time in Milliseconds" json:"created_at"` // Create Time in Milliseconds
	UpdatedAt           int64          `gorm:"column:updated_at;not null;autoUpdateTime:milli;comment:Update Time in Milliseconds" json:"updated_at"` // Update Time in Milliseconds
	DeletedAt           gorm.DeletedAt `gorm:"column:deleted_at;comment:Delete Time" json:"deleted_at"`                                               // Delete Time
}

// TableName TKnowledgePlaybookTag's table name
func (*TKnowledgePlaybookTag) TableName() string {
	return TableNameTKnowledgePlaybookTag
}
