// Code generated by otelwrapgen; DO NOT EDIT.
package repository

import (
	"context"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
)

func WithTracingCaseReplayRepository(next CaseReplayRepository) CaseReplayRepository {
	if next == nil {
		return nil
	}
	return &otelTracedCaseReplayRepository{next: next}
}

type otelTracedCaseReplayRepository struct {
	next CaseReplayRepository
}

func (w *otelTracedCaseReplayRepository) ActivateVersion(ctx context.Context, caseReplayID int64, versionID int64) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "CaseReplayRepository.ActivateVersion")
	defer span.End()

	ret0 := w.next.ActivateVersion(ctx, caseReplayID, versionID)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedCaseReplayRepository) CreateVersion(ctx context.Context, version *CaseReplayVersionModel) (int64, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "CaseReplayRepository.CreateVersion")
	defer span.End()

	ret0, ret1 := w.next.CreateVersion(ctx, version)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedCaseReplayRepository) GetCaseReplay(ctx context.Context, caseID string, siteHost string, platform string) (*CaseReplayModel, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "CaseReplayRepository.GetCaseReplay")
	defer span.End()

	ret0, ret1 := w.next.GetCaseReplay(ctx, caseID, siteHost, platform)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedCaseReplayRepository) GetOrCreate(ctx context.Context, caseID string, siteHost string, platform string) (int64, bool, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "CaseReplayRepository.GetOrCreate")
	defer span.End()

	ret0, ret1, ret2 := w.next.GetOrCreate(ctx, caseID, siteHost, platform)
	if ret2 != nil {
		span.RecordError(ret2)
		span.SetStatus(codes.Error, ret2.Error())
	}
	return ret0, ret1, ret2
}

func (w *otelTracedCaseReplayRepository) GetVersion(ctx context.Context, versionID int64) (*CaseReplayVersionModel, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "CaseReplayRepository.GetVersion")
	defer span.End()

	ret0, ret1 := w.next.GetVersion(ctx, versionID)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedCaseReplayRepository) MarkStale(ctx context.Context, caseReplayID int64) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "CaseReplayRepository.MarkStale")
	defer span.End()

	ret0 := w.next.MarkStale(ctx, caseReplayID)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedCaseReplayRepository) SetVersionActions(ctx context.Context, versionID int64, actionsBlobPath string) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "CaseReplayRepository.SetVersionActions")
	defer span.End()

	ret0 := w.next.SetVersionActions(ctx, versionID, actionsBlobPath)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}
