apiVersion: v1
kind: Service
metadata:
  name: sico-core
spec:
  type: {{ .Values.service.type }}
  selector:
    app: sico-core
  ports:
    - name: grpc
      port: {{ .Values.service.ports.grpc }}
      targetPort: grpc
