// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: knowledge/reverse_rpc.proto

package reverse_rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReverseKnowledgeRPC_RpcListKnowledgeMetadata_FullMethodName   = "/reverse_rpc.ReverseKnowledgeRPC/RpcListKnowledgeMetadata"
	ReverseKnowledgeRPC_RpcUpsertKnowledgePlaybook_FullMethodName = "/reverse_rpc.ReverseKnowledgeRPC/RpcUpsertKnowledgePlaybook"
)

// ReverseKnowledgeRPCClient is the client API for ReverseKnowledgeRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReverseKnowledgeRPCClient interface {
	// Fetch knowledge metadata (name and tags) for a list of knowledge document IDs.
	RpcListKnowledgeMetadata(ctx context.Context, in *GetKnowledgeMetadataRequest, opts ...grpc.CallOption) (*GetKnowledgeMetadataResponse, error)
	// Create or update a knowledge playbook for a given project and agent instance.
	// If a playbook already exists for the (project_id, agent_instance_id) pair,
	// only the updated_at timestamp is refreshed; otherwise a new record is created.
	RpcUpsertKnowledgePlaybook(ctx context.Context, in *UpsertKnowledgePlaybookRequest, opts ...grpc.CallOption) (*UpsertKnowledgePlaybookResponse, error)
}

type reverseKnowledgeRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewReverseKnowledgeRPCClient(cc grpc.ClientConnInterface) ReverseKnowledgeRPCClient {
	return &reverseKnowledgeRPCClient{cc}
}

func (c *reverseKnowledgeRPCClient) RpcListKnowledgeMetadata(ctx context.Context, in *GetKnowledgeMetadataRequest, opts ...grpc.CallOption) (*GetKnowledgeMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKnowledgeMetadataResponse)
	err := c.cc.Invoke(ctx, ReverseKnowledgeRPC_RpcListKnowledgeMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseKnowledgeRPCClient) RpcUpsertKnowledgePlaybook(ctx context.Context, in *UpsertKnowledgePlaybookRequest, opts ...grpc.CallOption) (*UpsertKnowledgePlaybookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertKnowledgePlaybookResponse)
	err := c.cc.Invoke(ctx, ReverseKnowledgeRPC_RpcUpsertKnowledgePlaybook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReverseKnowledgeRPCServer is the server API for ReverseKnowledgeRPC service.
// All implementations must embed UnimplementedReverseKnowledgeRPCServer
// for forward compatibility.
type ReverseKnowledgeRPCServer interface {
	// Fetch knowledge metadata (name and tags) for a list of knowledge document IDs.
	RpcListKnowledgeMetadata(context.Context, *GetKnowledgeMetadataRequest) (*GetKnowledgeMetadataResponse, error)
	// Create or update a knowledge playbook for a given project and agent instance.
	// If a playbook already exists for the (project_id, agent_instance_id) pair,
	// only the updated_at timestamp is refreshed; otherwise a new record is created.
	RpcUpsertKnowledgePlaybook(context.Context, *UpsertKnowledgePlaybookRequest) (*UpsertKnowledgePlaybookResponse, error)
	mustEmbedUnimplementedReverseKnowledgeRPCServer()
}

// UnimplementedReverseKnowledgeRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReverseKnowledgeRPCServer struct{}

func (UnimplementedReverseKnowledgeRPCServer) RpcListKnowledgeMetadata(context.Context, *GetKnowledgeMetadataRequest) (*GetKnowledgeMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RpcListKnowledgeMetadata not implemented")
}
func (UnimplementedReverseKnowledgeRPCServer) RpcUpsertKnowledgePlaybook(context.Context, *UpsertKnowledgePlaybookRequest) (*UpsertKnowledgePlaybookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RpcUpsertKnowledgePlaybook not implemented")
}
func (UnimplementedReverseKnowledgeRPCServer) mustEmbedUnimplementedReverseKnowledgeRPCServer() {}
func (UnimplementedReverseKnowledgeRPCServer) testEmbeddedByValue()                             {}

// UnsafeReverseKnowledgeRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReverseKnowledgeRPCServer will
// result in compilation errors.
type UnsafeReverseKnowledgeRPCServer interface {
	mustEmbedUnimplementedReverseKnowledgeRPCServer()
}

func RegisterReverseKnowledgeRPCServer(s grpc.ServiceRegistrar, srv ReverseKnowledgeRPCServer) {
	// If the following call panics, it indicates UnimplementedReverseKnowledgeRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReverseKnowledgeRPC_ServiceDesc, srv)
}

func _ReverseKnowledgeRPC_RpcListKnowledgeMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKnowledgeMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseKnowledgeRPCServer).RpcListKnowledgeMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseKnowledgeRPC_RpcListKnowledgeMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseKnowledgeRPCServer).RpcListKnowledgeMetadata(ctx, req.(*GetKnowledgeMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverseKnowledgeRPC_RpcUpsertKnowledgePlaybook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertKnowledgePlaybookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseKnowledgeRPCServer).RpcUpsertKnowledgePlaybook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverseKnowledgeRPC_RpcUpsertKnowledgePlaybook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseKnowledgeRPCServer).RpcUpsertKnowledgePlaybook(ctx, req.(*UpsertKnowledgePlaybookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReverseKnowledgeRPC_ServiceDesc is the grpc.ServiceDesc for ReverseKnowledgeRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReverseKnowledgeRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reverse_rpc.ReverseKnowledgeRPC",
	HandlerType: (*ReverseKnowledgeRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RpcListKnowledgeMetadata",
			Handler:    _ReverseKnowledgeRPC_RpcListKnowledgeMetadata_Handler,
		},
		{
			MethodName: "RpcUpsertKnowledgePlaybook",
			Handler:    _ReverseKnowledgeRPC_RpcUpsertKnowledgePlaybook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "knowledge/reverse_rpc.proto",
}
