# Copyright (c) 2026 Sico Authors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Edit this file, and rename to "mem0_config.yaml", to configure Mem0 for your deployment.

# reference: https://docs.mem0.ai/components/vectordbs/dbs/qdrant
# We have set up a Qdrant instance in our docker-compose/kind cluster,
# so you can use this configuration directly without modification.
vector_store:
  provider: qdrant
  config:
    collection_name: memories
    embedding_model_dims: 1536
    host: ${MEM0_QDRANT_HOST}
    port: 6333

# reference: https://docs.mem0.ai/components/embedders/config
embedder:
  provider: azure_openai
  config:
    model: text-embedding-3-small
    embedding_dims: 1536
    azure_kwargs:
      api_version: 2024-12-01-preview
      azure_endpoint: https://YOUR-OPENAI-ENDPOINT.openai.azure.com/
      api_key: YOUR-API-KEY

# reference: https://docs.mem0.ai/components/llms/config
llm:
  provider: azure_openai
  config:
    model: o1
    temperature: 0.1
    azure_kwargs:
      api_version: 2024-12-01-preview
      azure_endpoint: https://YOUR-OPENAI-ENDPOINT.openai.azure.com/
      api_key: YOUR-API-KEY

version: v1.1
