# Edit this file, and rename to "mem0_config.yaml", to configure Mem0 for your deployment.

# reference: https://docs.mem0.ai/components/vectordbs/dbs/qdrant
# We have set up a Qdrant instance in our docker-compose/kind cluster,
# so you can use this configuration directly without modification.
vector_store:
  provider: qdrant
  config:
    collection_name: memories
    embedding_model_dims: 1536
    host: ${MEM0_QDRANT_HOST}
    port: 6333

# reference: https://docs.mem0.ai/components/embedders/config
embedder:
  provider: azure_openai
  config:
    model: text-embedding-3-small
    embedding_dims: 1536
    azure_kwargs:
      api_version: 2024-12-01-preview
      azure_endpoint: https://YOUR-OPENAI-ENDPOINT.openai.azure.com/
      api_key: YOUR-API-KEY

# reference: https://docs.mem0.ai/components/llms/config
llm:
  provider: azure_openai
  config:
    model: o1
    temperature: 0.1
    azure_kwargs:
      api_version: 2024-12-01-preview
      azure_endpoint: https://YOUR-OPENAI-ENDPOINT.openai.azure.com/
      api_key: YOUR-API-KEY

version: v1.1
