// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                     = new(Query)
	TKnowledgeDocument    *tKnowledgeDocument
	TKnowledgeDocumentTag *tKnowledgeDocumentTag
	TKnowledgePlaybook    *tKnowledgePlaybook
	TKnowledgePlaybookTag *tKnowledgePlaybookTag
	TKnowledgeTag         *tKnowledgeTag
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	TKnowledgeDocument = &Q.TKnowledgeDocument
	TKnowledgeDocumentTag = &Q.TKnowledgeDocumentTag
	TKnowledgePlaybook = &Q.TKnowledgePlaybook
	TKnowledgePlaybookTag = &Q.TKnowledgePlaybookTag
	TKnowledgeTag = &Q.TKnowledgeTag
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                    db,
		TKnowledgeDocument:    newTKnowledgeDocument(db, opts...),
		TKnowledgeDocumentTag: newTKnowledgeDocumentTag(db, opts...),
		TKnowledgePlaybook:    newTKnowledgePlaybook(db, opts...),
		TKnowledgePlaybookTag: newTKnowledgePlaybookTag(db, opts...),
		TKnowledgeTag:         newTKnowledgeTag(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	TKnowledgeDocument    tKnowledgeDocument
	TKnowledgeDocumentTag tKnowledgeDocumentTag
	TKnowledgePlaybook    tKnowledgePlaybook
	TKnowledgePlaybookTag tKnowledgePlaybookTag
	TKnowledgeTag         tKnowledgeTag
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                    db,
		TKnowledgeDocument:    q.TKnowledgeDocument.clone(db),
		TKnowledgeDocumentTag: q.TKnowledgeDocumentTag.clone(db),
		TKnowledgePlaybook:    q.TKnowledgePlaybook.clone(db),
		TKnowledgePlaybookTag: q.TKnowledgePlaybookTag.clone(db),
		TKnowledgeTag:         q.TKnowledgeTag.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                    db,
		TKnowledgeDocument:    q.TKnowledgeDocument.replaceDB(db),
		TKnowledgeDocumentTag: q.TKnowledgeDocumentTag.replaceDB(db),
		TKnowledgePlaybook:    q.TKnowledgePlaybook.replaceDB(db),
		TKnowledgePlaybookTag: q.TKnowledgePlaybookTag.replaceDB(db),
		TKnowledgeTag:         q.TKnowledgeTag.replaceDB(db),
	}
}

type queryCtx struct {
	TKnowledgeDocument    ITKnowledgeDocumentDo
	TKnowledgeDocumentTag ITKnowledgeDocumentTagDo
	TKnowledgePlaybook    ITKnowledgePlaybookDo
	TKnowledgePlaybookTag ITKnowledgePlaybookTagDo
	TKnowledgeTag         ITKnowledgeTagDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		TKnowledgeDocument:    q.TKnowledgeDocument.WithContext(ctx),
		TKnowledgeDocumentTag: q.TKnowledgeDocumentTag.WithContext(ctx),
		TKnowledgePlaybook:    q.TKnowledgePlaybook.WithContext(ctx),
		TKnowledgePlaybookTag: q.TKnowledgePlaybookTag.WithContext(ctx),
		TKnowledgeTag:         q.TKnowledgeTag.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
