// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"sico-backend/internal/store/knowledge/internal/dal/model"
)

func newTKnowledgePlaybook(db *gorm.DB, opts ...gen.DOOption) tKnowledgePlaybook {
	_tKnowledgePlaybook := tKnowledgePlaybook{}

	_tKnowledgePlaybook.tKnowledgePlaybookDo.UseDB(db, opts...)
	_tKnowledgePlaybook.tKnowledgePlaybookDo.UseModel(&model.TKnowledgePlaybook{})

	tableName := _tKnowledgePlaybook.tKnowledgePlaybookDo.TableName()
	_tKnowledgePlaybook.ALL = field.NewAsterisk(tableName)
	_tKnowledgePlaybook.ID = field.NewInt64(tableName, "id")
	_tKnowledgePlaybook.ProjectID = field.NewInt64(tableName, "project_id")
	_tKnowledgePlaybook.AgentInstanceID = field.NewInt64(tableName, "agent_instance_id")
	_tKnowledgePlaybook.Name = field.NewString(tableName, "name")
	_tKnowledgePlaybook.CreatedAt = field.NewInt64(tableName, "created_at")
	_tKnowledgePlaybook.UpdatedAt = field.NewInt64(tableName, "updated_at")
	_tKnowledgePlaybook.DeletedAt = field.NewField(tableName, "deleted_at")

	_tKnowledgePlaybook.fillFieldMap()

	return _tKnowledgePlaybook
}

// tKnowledgePlaybook Playbook table
type tKnowledgePlaybook struct {
	tKnowledgePlaybookDo

	ALL             field.Asterisk
	ID              field.Int64  // Primary key
	ProjectID       field.Int64  // Project ID
	AgentInstanceID field.Int64  // Agent instance ID
	Name            field.String // Playbook name
	CreatedAt       field.Int64  // Create Time in Milliseconds
	UpdatedAt       field.Int64  // Update Time in Milliseconds
	DeletedAt       field.Field  // Delete Time

	fieldMap map[string]field.Expr
}

func (t tKnowledgePlaybook) Table(newTableName string) *tKnowledgePlaybook {
	t.tKnowledgePlaybookDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tKnowledgePlaybook) As(alias string) *tKnowledgePlaybook {
	t.tKnowledgePlaybookDo.DO = *(t.tKnowledgePlaybookDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tKnowledgePlaybook) updateTableName(table string) *tKnowledgePlaybook {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.ProjectID = field.NewInt64(table, "project_id")
	t.AgentInstanceID = field.NewInt64(table, "agent_instance_id")
	t.Name = field.NewString(table, "name")
	t.CreatedAt = field.NewInt64(table, "created_at")
	t.UpdatedAt = field.NewInt64(table, "updated_at")
	t.DeletedAt = field.NewField(table, "deleted_at")

	t.fillFieldMap()

	return t
}

func (t *tKnowledgePlaybook) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tKnowledgePlaybook) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 7)
	t.fieldMap["id"] = t.ID
	t.fieldMap["project_id"] = t.ProjectID
	t.fieldMap["agent_instance_id"] = t.AgentInstanceID
	t.fieldMap["name"] = t.Name
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["deleted_at"] = t.DeletedAt
}

func (t tKnowledgePlaybook) clone(db *gorm.DB) tKnowledgePlaybook {
	t.tKnowledgePlaybookDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tKnowledgePlaybook) replaceDB(db *gorm.DB) tKnowledgePlaybook {
	t.tKnowledgePlaybookDo.ReplaceDB(db)
	return t
}

type tKnowledgePlaybookDo struct{ gen.DO }

type ITKnowledgePlaybookDo interface {
	gen.SubQuery
	Debug() ITKnowledgePlaybookDo
	WithContext(ctx context.Context) ITKnowledgePlaybookDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITKnowledgePlaybookDo
	WriteDB() ITKnowledgePlaybookDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITKnowledgePlaybookDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITKnowledgePlaybookDo
	Not(conds ...gen.Condition) ITKnowledgePlaybookDo
	Or(conds ...gen.Condition) ITKnowledgePlaybookDo
	Select(conds ...field.Expr) ITKnowledgePlaybookDo
	Where(conds ...gen.Condition) ITKnowledgePlaybookDo
	Order(conds ...field.Expr) ITKnowledgePlaybookDo
	Distinct(cols ...field.Expr) ITKnowledgePlaybookDo
	Omit(cols ...field.Expr) ITKnowledgePlaybookDo
	Join(table schema.Tabler, on ...field.Expr) ITKnowledgePlaybookDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITKnowledgePlaybookDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITKnowledgePlaybookDo
	Group(cols ...field.Expr) ITKnowledgePlaybookDo
	Having(conds ...gen.Condition) ITKnowledgePlaybookDo
	Limit(limit int) ITKnowledgePlaybookDo
	Offset(offset int) ITKnowledgePlaybookDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITKnowledgePlaybookDo
	Unscoped() ITKnowledgePlaybookDo
	Create(values ...*model.TKnowledgePlaybook) error
	CreateInBatches(values []*model.TKnowledgePlaybook, batchSize int) error
	Save(values ...*model.TKnowledgePlaybook) error
	First() (*model.TKnowledgePlaybook, error)
	Take() (*model.TKnowledgePlaybook, error)
	Last() (*model.TKnowledgePlaybook, error)
	Find() ([]*model.TKnowledgePlaybook, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TKnowledgePlaybook, err error)
	FindInBatches(result *[]*model.TKnowledgePlaybook, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TKnowledgePlaybook) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITKnowledgePlaybookDo
	Assign(attrs ...field.AssignExpr) ITKnowledgePlaybookDo
	Joins(fields ...field.RelationField) ITKnowledgePlaybookDo
	Preload(fields ...field.RelationField) ITKnowledgePlaybookDo
	FirstOrInit() (*model.TKnowledgePlaybook, error)
	FirstOrCreate() (*model.TKnowledgePlaybook, error)
	FindByPage(offset int, limit int) (result []*model.TKnowledgePlaybook, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITKnowledgePlaybookDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tKnowledgePlaybookDo) Debug() ITKnowledgePlaybookDo {
	return t.withDO(t.DO.Debug())
}

func (t tKnowledgePlaybookDo) WithContext(ctx context.Context) ITKnowledgePlaybookDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tKnowledgePlaybookDo) ReadDB() ITKnowledgePlaybookDo {
	return t.Clauses(dbresolver.Read)
}

func (t tKnowledgePlaybookDo) WriteDB() ITKnowledgePlaybookDo {
	return t.Clauses(dbresolver.Write)
}

func (t tKnowledgePlaybookDo) Session(config *gorm.Session) ITKnowledgePlaybookDo {
	return t.withDO(t.DO.Session(config))
}

func (t tKnowledgePlaybookDo) Clauses(conds ...clause.Expression) ITKnowledgePlaybookDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tKnowledgePlaybookDo) Returning(value interface{}, columns ...string) ITKnowledgePlaybookDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tKnowledgePlaybookDo) Not(conds ...gen.Condition) ITKnowledgePlaybookDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tKnowledgePlaybookDo) Or(conds ...gen.Condition) ITKnowledgePlaybookDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tKnowledgePlaybookDo) Select(conds ...field.Expr) ITKnowledgePlaybookDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tKnowledgePlaybookDo) Where(conds ...gen.Condition) ITKnowledgePlaybookDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tKnowledgePlaybookDo) Order(conds ...field.Expr) ITKnowledgePlaybookDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tKnowledgePlaybookDo) Distinct(cols ...field.Expr) ITKnowledgePlaybookDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tKnowledgePlaybookDo) Omit(cols ...field.Expr) ITKnowledgePlaybookDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tKnowledgePlaybookDo) Join(table schema.Tabler, on ...field.Expr) ITKnowledgePlaybookDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tKnowledgePlaybookDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITKnowledgePlaybookDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tKnowledgePlaybookDo) RightJoin(table schema.Tabler, on ...field.Expr) ITKnowledgePlaybookDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tKnowledgePlaybookDo) Group(cols ...field.Expr) ITKnowledgePlaybookDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tKnowledgePlaybookDo) Having(conds ...gen.Condition) ITKnowledgePlaybookDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tKnowledgePlaybookDo) Limit(limit int) ITKnowledgePlaybookDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tKnowledgePlaybookDo) Offset(offset int) ITKnowledgePlaybookDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tKnowledgePlaybookDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITKnowledgePlaybookDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tKnowledgePlaybookDo) Unscoped() ITKnowledgePlaybookDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tKnowledgePlaybookDo) Create(values ...*model.TKnowledgePlaybook) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tKnowledgePlaybookDo) CreateInBatches(values []*model.TKnowledgePlaybook, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tKnowledgePlaybookDo) Save(values ...*model.TKnowledgePlaybook) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tKnowledgePlaybookDo) First() (*model.TKnowledgePlaybook, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TKnowledgePlaybook), nil
	}
}

func (t tKnowledgePlaybookDo) Take() (*model.TKnowledgePlaybook, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TKnowledgePlaybook), nil
	}
}

func (t tKnowledgePlaybookDo) Last() (*model.TKnowledgePlaybook, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TKnowledgePlaybook), nil
	}
}

func (t tKnowledgePlaybookDo) Find() ([]*model.TKnowledgePlaybook, error) {
	result, err := t.DO.Find()
	return result.([]*model.TKnowledgePlaybook), err
}

func (t tKnowledgePlaybookDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TKnowledgePlaybook, err error) {
	buf := make([]*model.TKnowledgePlaybook, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tKnowledgePlaybookDo) FindInBatches(result *[]*model.TKnowledgePlaybook, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tKnowledgePlaybookDo) Attrs(attrs ...field.AssignExpr) ITKnowledgePlaybookDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tKnowledgePlaybookDo) Assign(attrs ...field.AssignExpr) ITKnowledgePlaybookDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tKnowledgePlaybookDo) Joins(fields ...field.RelationField) ITKnowledgePlaybookDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tKnowledgePlaybookDo) Preload(fields ...field.RelationField) ITKnowledgePlaybookDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tKnowledgePlaybookDo) FirstOrInit() (*model.TKnowledgePlaybook, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TKnowledgePlaybook), nil
	}
}

func (t tKnowledgePlaybookDo) FirstOrCreate() (*model.TKnowledgePlaybook, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TKnowledgePlaybook), nil
	}
}

func (t tKnowledgePlaybookDo) FindByPage(offset int, limit int) (result []*model.TKnowledgePlaybook, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tKnowledgePlaybookDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tKnowledgePlaybookDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tKnowledgePlaybookDo) Delete(models ...*model.TKnowledgePlaybook) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tKnowledgePlaybookDo) withDO(do gen.Dao) *tKnowledgePlaybookDo {
	t.DO = *do.(*gen.DO)
	return t
}
