// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: conversation/rpc.proto

package conversation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	conversation "sico-backend/internal/transport/http/dto/conversation"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_conversation_rpc_proto protoreflect.FileDescriptor

const file_conversation_rpc_proto_rawDesc = "" +
	"\n" +
	"\x16conversation/rpc.proto\x12\x03rpc\x1a\x16conversation/api.proto2\xc3\x02\n" +
	"\vChatService\x127\n" +
	"\n" +
	"StreamChat\x12\x10.api.ChatRequest\x1a\x17.api.ChatDirectResponse\x124\n" +
	"\aGetPlan\x12\x13.api.GetPlanRequest\x1a\x14.api.GetPlanResponse\x12=\n" +
	"\n" +
	"CancelPlan\x12\x16.api.CancelPlanRequest\x1a\x17.api.CancelPlanResponse\x12\x85\x01\n" +
	"\"GenerateOnboardRecommendationTasks\x12..api.GenerateOnboardRecommendationTasksRequest\x1a/.api.GenerateOnboardRecommendationTasksResponseB6Z4sico-backend/internal/transport/grpc/pb/conversationb\x06proto3"

var file_conversation_rpc_proto_goTypes = []any{
	(*conversation.ChatRequest)(nil),                                // 0: api.ChatRequest
	(*conversation.GetPlanRequest)(nil),                             // 1: api.GetPlanRequest
	(*conversation.CancelPlanRequest)(nil),                          // 2: api.CancelPlanRequest
	(*conversation.GenerateOnboardRecommendationTasksRequest)(nil),  // 3: api.GenerateOnboardRecommendationTasksRequest
	(*conversation.ChatDirectResponse)(nil),                         // 4: api.ChatDirectResponse
	(*conversation.GetPlanResponse)(nil),                            // 5: api.GetPlanResponse
	(*conversation.CancelPlanResponse)(nil),                         // 6: api.CancelPlanResponse
	(*conversation.GenerateOnboardRecommendationTasksResponse)(nil), // 7: api.GenerateOnboardRecommendationTasksResponse
}
var file_conversation_rpc_proto_depIdxs = []int32{
	0, // 0: rpc.ChatService.StreamChat:input_type -> api.ChatRequest
	1, // 1: rpc.ChatService.GetPlan:input_type -> api.GetPlanRequest
	2, // 2: rpc.ChatService.CancelPlan:input_type -> api.CancelPlanRequest
	3, // 3: rpc.ChatService.GenerateOnboardRecommendationTasks:input_type -> api.GenerateOnboardRecommendationTasksRequest
	4, // 4: rpc.ChatService.StreamChat:output_type -> api.ChatDirectResponse
	5, // 5: rpc.ChatService.GetPlan:output_type -> api.GetPlanResponse
	6, // 6: rpc.ChatService.CancelPlan:output_type -> api.CancelPlanResponse
	7, // 7: rpc.ChatService.GenerateOnboardRecommendationTasks:output_type -> api.GenerateOnboardRecommendationTasksResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_conversation_rpc_proto_init() }
func file_conversation_rpc_proto_init() {
	if File_conversation_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conversation_rpc_proto_rawDesc), len(file_conversation_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_conversation_rpc_proto_goTypes,
		DependencyIndexes: file_conversation_rpc_proto_depIdxs,
	}.Build()
	File_conversation_rpc_proto = out.File
	file_conversation_rpc_proto_goTypes = nil
	file_conversation_rpc_proto_depIdxs = nil
}
