// Code generated by otelwrapgen; DO NOT EDIT.
package repository

import (
	"context"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
)

func WithTracingIntegrationRepository(next IntegrationRepository) IntegrationRepository {
	if next == nil {
		return nil
	}
	return &otelTracedIntegrationRepository{next: next}
}

type otelTracedIntegrationRepository struct {
	next IntegrationRepository
}

func (w *otelTracedIntegrationRepository) CreateConnection(ctx context.Context, connection *ConnectionModel) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "IntegrationRepository.CreateConnection")
	defer span.End()

	ret0 := w.next.CreateConnection(ctx, connection)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedIntegrationRepository) CreateOrReactivateBinding(ctx context.Context, expected *ConnectionModel, binding *BindingModel) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "IntegrationRepository.CreateOrReactivateBinding")
	defer span.End()

	ret0 := w.next.CreateOrReactivateBinding(ctx, expected, binding)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedIntegrationRepository) DeleteBinding(ctx context.Context, connectionID int64, bindingID int64) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "IntegrationRepository.DeleteBinding")
	defer span.End()

	ret0 := w.next.DeleteBinding(ctx, connectionID, bindingID)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedIntegrationRepository) DeleteConnection(ctx context.Context, expected *ConnectionModel, updaterUsername string) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "IntegrationRepository.DeleteConnection")
	defer span.End()

	ret0 := w.next.DeleteConnection(ctx, expected, updaterUsername)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedIntegrationRepository) GetBinding(ctx context.Context, connectionID int64, bindingID int64) (*BindingModel, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "IntegrationRepository.GetBinding")
	defer span.End()

	ret0, ret1 := w.next.GetBinding(ctx, connectionID, bindingID)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedIntegrationRepository) GetConnectionByKey(ctx context.Context, connectionKey string) (*ConnectionModel, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "IntegrationRepository.GetConnectionByKey")
	defer span.End()

	ret0, ret1 := w.next.GetConnectionByKey(ctx, connectionKey)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedIntegrationRepository) GetCredentialVersion(ctx context.Context, connectionID int64, version int64) (*CredentialModel, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "IntegrationRepository.GetCredentialVersion")
	defer span.End()

	ret0, ret1 := w.next.GetCredentialVersion(ctx, connectionID, version)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedIntegrationRepository) ListBindings(ctx context.Context, connectionID int64, filter *BindingFilter, offset int, limit int) ([]*BindingModel, int64, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "IntegrationRepository.ListBindings")
	defer span.End()

	ret0, ret1, ret2 := w.next.ListBindings(ctx, connectionID, filter, offset, limit)
	if ret2 != nil {
		span.RecordError(ret2)
		span.SetStatus(codes.Error, ret2.Error())
	}
	return ret0, ret1, ret2
}

func (w *otelTracedIntegrationRepository) ListConnections(ctx context.Context, filter *ConnectionFilter, offset int, limit int) ([]*ConnectionModel, int64, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "IntegrationRepository.ListConnections")
	defer span.End()

	ret0, ret1, ret2 := w.next.ListConnections(ctx, filter, offset, limit)
	if ret2 != nil {
		span.RecordError(ret2)
		span.SetStatus(codes.Error, ret2.Error())
	}
	return ret0, ret1, ret2
}

func (w *otelTracedIntegrationRepository) MarkConnectionReauthorizationRequired(ctx context.Context, connectionID int64, expectedStatus int32, expectedCredentialVersion int64, updaterUsername string) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "IntegrationRepository.MarkConnectionReauthorizationRequired")
	defer span.End()

	ret0 := w.next.MarkConnectionReauthorizationRequired(ctx, connectionID, expectedStatus, expectedCredentialVersion, updaterUsername)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedIntegrationRepository) SaveCredentialVersion(ctx context.Context, expected *ConnectionModel, credential *CredentialModel, connectionFields map[string]any) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "IntegrationRepository.SaveCredentialVersion")
	defer span.End()

	ret0 := w.next.SaveCredentialVersion(ctx, expected, credential, connectionFields)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedIntegrationRepository) UpdateBindingStatus(ctx context.Context, expected *ConnectionModel, bindingID int64, status int32) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "IntegrationRepository.UpdateBindingStatus")
	defer span.End()

	ret0 := w.next.UpdateBindingStatus(ctx, expected, bindingID, status)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedIntegrationRepository) UpdateConnectionFields(ctx context.Context, connectionID int64, fields map[string]any) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "IntegrationRepository.UpdateConnectionFields")
	defer span.End()

	ret0 := w.next.UpdateConnectionFields(ctx, connectionID, fields)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedIntegrationRepository) UpdateConnectionState(ctx context.Context, expected *ConnectionModel, fields map[string]any) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "IntegrationRepository.UpdateConnectionState")
	defer span.End()

	ret0 := w.next.UpdateConnectionState(ctx, expected, fields)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}
