// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

const TableNameTIntegrationBinding = "t_integration_binding"

// TIntegrationBinding Sico scope to provider resource bindings
type TIntegrationBinding struct {
	ID              int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:Primary key ID" json:"id"`                                     // Primary key ID
	ConnectionID    int64          `gorm:"column:connection_id;not null;comment:Integration connection ID" json:"connection_id"`                         // Integration connection ID
	SicoScopeType   int32          `gorm:"column:sico_scope_type;not null;comment:1=organization, 2=project" json:"sico_scope_type"`                     // 1=organization, 2=project
	SicoScopeID     string         `gorm:"column:sico_scope_id;not null;comment:Sico RBAC scope identifier" json:"sico_scope_id"`                        // Sico RBAC scope identifier
	ResourceType    string         `gorm:"column:resource_type;not null;comment:Connector-defined resource kind" json:"resource_type"`                   // Connector-defined resource kind
	ResourceKey     string         `gorm:"column:resource_key;not null;comment:Opaque canonical provider resource identifier" json:"resource_key"`       // Opaque canonical provider resource identifier
	ResourceName    string         `gorm:"column:resource_name;not null;comment:Provider resource display name" json:"resource_name"`                    // Provider resource display name
	Status          int32          `gorm:"column:status;not null;default:1;comment:1=active, 2=disabled, 3=inaccessible" json:"status"`                  // 1=active, 2=disabled, 3=inaccessible
	Metadata        datatypes.JSON `gorm:"column:metadata;comment:Versioned non-secret connector metadata" json:"metadata"`                              // Versioned non-secret connector metadata
	CreatorUsername string         `gorm:"column:creator_username;not null;comment:Creator username" json:"creator_username"`                            // Creator username
	CreatedAt       int64          `gorm:"column:created_at;not null;autoCreateTime:milli;comment:Creation time in Unix milliseconds" json:"created_at"` // Creation time in Unix milliseconds
	UpdatedAt       int64          `gorm:"column:updated_at;not null;autoUpdateTime:milli;comment:Update time in Unix milliseconds" json:"updated_at"`   // Update time in Unix milliseconds
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at;comment:Deletion time" json:"deleted_at"`                                                    // Deletion time
}

// TableName TIntegrationBinding's table name
func (*TIntegrationBinding) TableName() string {
	return TableNameTIntegrationBinding
}
