// Code generated by otelwrapgen; DO NOT EDIT.
package knowledge

import (
	"context"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
	"sico-backend/internal/transport/http/dto/knowledge"
	reverse_rpc "sico-backend/internal/transport/reverse_grpc/pb/knowledge"
)

func WithTracing(next Service) Service {
	if next == nil {
		return nil
	}
	return &otelTracedService{next: next}
}

type otelTracedService struct {
	reverse_rpc.UnimplementedReverseKnowledgeRPCServer
	next Service
}

func (w *otelTracedService) Unwrap() Service {
	return w.next
}

func (w *otelTracedService) CreateDocument(ctx context.Context, req *knowledge.CreateKnowledgeDocumentRequest) (*knowledge.CreateKnowledgeDocumentResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.CreateDocument")
	defer span.End()

	ret0, ret1 := w.next.CreateDocument(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) CreateKnowledgeTag(ctx context.Context, req *knowledge.CreateKnowledgeTagRequest) (*knowledge.CreateKnowledgeTagResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.CreateKnowledgeTag")
	defer span.End()

	ret0, ret1 := w.next.CreateKnowledgeTag(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) DeleteDocument(ctx context.Context, req *knowledge.DeleteKnowledgeDocumentRequest) (*knowledge.DeleteKnowledgeDocumentResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.DeleteDocument")
	defer span.End()

	ret0, ret1 := w.next.DeleteDocument(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) DeleteKnowledgeTag(ctx context.Context, req *knowledge.DeleteKnowledgeTagRequest) (*knowledge.DeleteKnowledgeTagResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.DeleteKnowledgeTag")
	defer span.End()

	ret0, ret1 := w.next.DeleteKnowledgeTag(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) DeletePlaybook(ctx context.Context, req *knowledge.DeleteKnowledgePlaybookRequest) (*knowledge.DeleteKnowledgePlaybookResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.DeletePlaybook")
	defer span.End()

	ret0, ret1 := w.next.DeletePlaybook(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) GetDocument(ctx context.Context, req *knowledge.GetKnowledgeDocumentRequest) (*knowledge.GetKnowledgeDocumentResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.GetDocument")
	defer span.End()

	ret0, ret1 := w.next.GetDocument(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) GetDocumentDetails(ctx context.Context, req *knowledge.GetKnowledgeDocumentDetailsRequest) (*knowledge.GetKnowledgeDocumentDetailsResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.GetDocumentDetails")
	defer span.End()

	ret0, ret1 := w.next.GetDocumentDetails(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) GetKnowledgeTag(ctx context.Context, req *knowledge.GetKnowledgeTagRequest) (*knowledge.GetKnowledgeTagResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.GetKnowledgeTag")
	defer span.End()

	ret0, ret1 := w.next.GetKnowledgeTag(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) GetPlaybook(ctx context.Context, req *knowledge.GetKnowledgePlaybookRequest) (*knowledge.GetKnowledgePlaybookResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.GetPlaybook")
	defer span.End()

	ret0, ret1 := w.next.GetPlaybook(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) GetPlaybookDetails(ctx context.Context, req *knowledge.GetKnowledgePlaybookDetailsRequest) (*knowledge.GetKnowledgePlaybookDetailsResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.GetPlaybookDetails")
	defer span.End()

	ret0, ret1 := w.next.GetPlaybookDetails(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) ListDocuments(ctx context.Context, req *knowledge.ListKnowledgeDocumentRequest) (*knowledge.ListKnowledgeDocumentResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.ListDocuments")
	defer span.End()

	ret0, ret1 := w.next.ListDocuments(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) ListKnowledgeItems(ctx context.Context, req *knowledge.ListKnowledgeItemsRequest) (*knowledge.ListKnowledgeItemsResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.ListKnowledgeItems")
	defer span.End()

	ret0, ret1 := w.next.ListKnowledgeItems(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) ListKnowledgeTag(ctx context.Context, req *knowledge.ListKnowledgeTagRequest) (*knowledge.ListKnowledgeTagResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.ListKnowledgeTag")
	defer span.End()

	ret0, ret1 := w.next.ListKnowledgeTag(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) ListPlaybooks(ctx context.Context, req *knowledge.ListKnowledgePlaybookRequest) (*knowledge.ListKnowledgePlaybookResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.ListPlaybooks")
	defer span.End()

	ret0, ret1 := w.next.ListPlaybooks(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) RpcListKnowledgeMetadata(arg0 context.Context, arg1 *reverse_rpc.GetKnowledgeMetadataRequest) (*reverse_rpc.GetKnowledgeMetadataResponse, error) {
	arg0, span := otel.Tracer("sico-backend/otelwrap").Start(arg0, "Service.RpcListKnowledgeMetadata")
	defer span.End()

	ret0, ret1 := w.next.RpcListKnowledgeMetadata(arg0, arg1)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) RpcUpsertKnowledgePlaybook(arg0 context.Context, arg1 *reverse_rpc.UpsertKnowledgePlaybookRequest) (*reverse_rpc.UpsertKnowledgePlaybookResponse, error) {
	arg0, span := otel.Tracer("sico-backend/otelwrap").Start(arg0, "Service.RpcUpsertKnowledgePlaybook")
	defer span.End()

	ret0, ret1 := w.next.RpcUpsertKnowledgePlaybook(arg0, arg1)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) UpdateDocument(ctx context.Context, req *knowledge.UpdateKnowledgeDocumentRequest) (*knowledge.UpdateKnowledgeDocumentResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.UpdateDocument")
	defer span.End()

	ret0, ret1 := w.next.UpdateDocument(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) UpdateKnowledgeTag(ctx context.Context, req *knowledge.UpdateKnowledgeTagRequest) (*knowledge.UpdateKnowledgeTagResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.UpdateKnowledgeTag")
	defer span.End()

	ret0, ret1 := w.next.UpdateKnowledgeTag(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedService) UpdatePlaybook(ctx context.Context, req *knowledge.UpdateKnowledgePlaybookRequest) (*knowledge.UpdateKnowledgePlaybookResponse, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "Service.UpdatePlaybook")
	defer span.End()

	ret0, ret1 := w.next.UpdatePlaybook(ctx, req)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}
