// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: authstate/restful.proto

package authstate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthStateStatus int32

const (
	AuthStateStatus_AUTH_STATE_STATUS_UNKNOWN  AuthStateStatus = 0 // @gotag: json:"AUTH_STATE_STATUS_UNKNOWN"
	AuthStateStatus_AUTH_STATE_STATUS_VALID    AuthStateStatus = 1 // @gotag: json:"AUTH_STATE_STATUS_VALID"
	AuthStateStatus_AUTH_STATE_STATUS_EXPIRED  AuthStateStatus = 2 // @gotag: json:"AUTH_STATE_STATUS_EXPIRED"
	AuthStateStatus_AUTH_STATE_STATUS_DISABLED AuthStateStatus = 3 // @gotag: json:"AUTH_STATE_STATUS_DISABLED"
)

// Enum value maps for AuthStateStatus.
var (
	AuthStateStatus_name = map[int32]string{
		0: "AUTH_STATE_STATUS_UNKNOWN",
		1: "AUTH_STATE_STATUS_VALID",
		2: "AUTH_STATE_STATUS_EXPIRED",
		3: "AUTH_STATE_STATUS_DISABLED",
	}
	AuthStateStatus_value = map[string]int32{
		"AUTH_STATE_STATUS_UNKNOWN":  0,
		"AUTH_STATE_STATUS_VALID":    1,
		"AUTH_STATE_STATUS_EXPIRED":  2,
		"AUTH_STATE_STATUS_DISABLED": 3,
	}
)

func (x AuthStateStatus) Enum() *AuthStateStatus {
	p := new(AuthStateStatus)
	*p = x
	return p
}

func (x AuthStateStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthStateStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_authstate_restful_proto_enumTypes[0].Descriptor()
}

func (AuthStateStatus) Type() protoreflect.EnumType {
	return &file_authstate_restful_proto_enumTypes[0]
}

func (x AuthStateStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthStateStatus.Descriptor instead.
func (AuthStateStatus) EnumDescriptor() ([]byte, []int) {
	return file_authstate_restful_proto_rawDescGZIP(), []int{0}
}

type AuthState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`                                                     
	AccountKey      string                 `protobuf:"bytes,2,opt,name=account_key,json=accountKey,proto3" json:"accountKey"`                    
	SiteHost        string                 `protobuf:"bytes,3,opt,name=site_host,json=siteHost,proto3" json:"siteHost"`                          
	Status          AuthStateStatus        `protobuf:"varint,5,opt,name=status,proto3,enum=authstate.AuthStateStatus" json:"status"`              
	ExpiresAt       int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expiresAt"`                      
	LastValidatedAt int64                  `protobuf:"varint,7,opt,name=last_validated_at,json=lastValidatedAt,proto3" json:"lastValidatedAt"`  
	Metadata        string                 `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata"`                                          
	CreatedAt       int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"createdAt"`                      
	UpdatedAt       int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updatedAt"`                     
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthState) Reset() {
	*x = AuthState{}
	mi := &file_authstate_restful_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthState) ProtoMessage() {}

func (x *AuthState) ProtoReflect() protoreflect.Message {
	mi := &file_authstate_restful_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthState.ProtoReflect.Descriptor instead.
func (*AuthState) Descriptor() ([]byte, []int) {
	return file_authstate_restful_proto_rawDescGZIP(), []int{0}
}

func (x *AuthState) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuthState) GetAccountKey() string {
	if x != nil {
		return x.AccountKey
	}
	return ""
}

func (x *AuthState) GetSiteHost() string {
	if x != nil {
		return x.SiteHost
	}
	return ""
}

func (x *AuthState) GetStatus() AuthStateStatus {
	if x != nil {
		return x.Status
	}
	return AuthStateStatus_AUTH_STATE_STATUS_UNKNOWN
}

func (x *AuthState) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *AuthState) GetLastValidatedAt() int64 {
	if x != nil {
		return x.LastValidatedAt
	}
	return 0
}

func (x *AuthState) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *AuthState) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AuthState) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ImportAuthStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountKey    string                 `protobuf:"bytes,1,opt,name=account_key,json=accountKey,proto3" json:"accountKey" binding:"required"`        
	SiteHost      string                 `protobuf:"bytes,2,opt,name=site_host,json=siteHost,proto3" json:"siteHost" binding:"required"`              
	StorageState  string                 `protobuf:"bytes,3,opt,name=storage_state,json=storageState,proto3" json:"storageState" binding:"required"`  
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expiresAt"`          
	Metadata      string                 `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata"`                              
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportAuthStateRequest) Reset() {
	*x = ImportAuthStateRequest{}
	mi := &file_authstate_restful_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportAuthStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportAuthStateRequest) ProtoMessage() {}

func (x *ImportAuthStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authstate_restful_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportAuthStateRequest.ProtoReflect.Descriptor instead.
func (*ImportAuthStateRequest) Descriptor() ([]byte, []int) {
	return file_authstate_restful_proto_rawDescGZIP(), []int{1}
}

func (x *ImportAuthStateRequest) GetAccountKey() string {
	if x != nil {
		return x.AccountKey
	}
	return ""
}

func (x *ImportAuthStateRequest) GetSiteHost() string {
	if x != nil {
		return x.SiteHost
	}
	return ""
}

func (x *ImportAuthStateRequest) GetStorageState() string {
	if x != nil {
		return x.StorageState
	}
	return ""
}

func (x *ImportAuthStateRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *ImportAuthStateRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type ImportAuthStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *ImportAuthStateData   `protobuf:"bytes,1,opt,name=data,proto3" json:"data"`     
	Code          int32                  `protobuf:"varint,253,opt,name=code,proto3" json:"code"`  
	Msg           string                 `protobuf:"bytes,254,opt,name=msg,proto3" json:"msg"`     
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportAuthStateResponse) Reset() {
	*x = ImportAuthStateResponse{}
	mi := &file_authstate_restful_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportAuthStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportAuthStateResponse) ProtoMessage() {}

func (x *ImportAuthStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authstate_restful_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportAuthStateResponse.ProtoReflect.Descriptor instead.
func (*ImportAuthStateResponse) Descriptor() ([]byte, []int) {
	return file_authstate_restful_proto_rawDescGZIP(), []int{2}
}

func (x *ImportAuthStateResponse) GetData() *ImportAuthStateData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ImportAuthStateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ImportAuthStateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ImportAuthStateData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`  
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportAuthStateData) Reset() {
	*x = ImportAuthStateData{}
	mi := &file_authstate_restful_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportAuthStateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportAuthStateData) ProtoMessage() {}

func (x *ImportAuthStateData) ProtoReflect() protoreflect.Message {
	mi := &file_authstate_restful_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportAuthStateData.ProtoReflect.Descriptor instead.
func (*ImportAuthStateData) Descriptor() ([]byte, []int) {
	return file_authstate_restful_proto_rawDescGZIP(), []int{3}
}

func (x *ImportAuthStateData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAuthStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountKey    string                 `protobuf:"bytes,1,opt,name=account_key,json=accountKey,proto3" json:"account_key,omitempty" form:"accountKey" binding:"required"`  
	SiteHost      string                 `protobuf:"bytes,2,opt,name=site_host,json=siteHost,proto3" json:"site_host,omitempty" form:"siteHost" binding:"required"`        
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthStateRequest) Reset() {
	*x = GetAuthStateRequest{}
	mi := &file_authstate_restful_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthStateRequest) ProtoMessage() {}

func (x *GetAuthStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authstate_restful_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthStateRequest.ProtoReflect.Descriptor instead.
func (*GetAuthStateRequest) Descriptor() ([]byte, []int) {
	return file_authstate_restful_proto_rawDescGZIP(), []int{4}
}

func (x *GetAuthStateRequest) GetAccountKey() string {
	if x != nil {
		return x.AccountKey
	}
	return ""
}

func (x *GetAuthStateRequest) GetSiteHost() string {
	if x != nil {
		return x.SiteHost
	}
	return ""
}

type GetAuthStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *GetAuthStateData      `protobuf:"bytes,1,opt,name=data,proto3" json:"data"`     
	Code          int32                  `protobuf:"varint,253,opt,name=code,proto3" json:"code"`  
	Msg           string                 `protobuf:"bytes,254,opt,name=msg,proto3" json:"msg"`     
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthStateResponse) Reset() {
	*x = GetAuthStateResponse{}
	mi := &file_authstate_restful_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthStateResponse) ProtoMessage() {}

func (x *GetAuthStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authstate_restful_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthStateResponse.ProtoReflect.Descriptor instead.
func (*GetAuthStateResponse) Descriptor() ([]byte, []int) {
	return file_authstate_restful_proto_rawDescGZIP(), []int{5}
}

func (x *GetAuthStateResponse) GetData() *GetAuthStateData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetAuthStateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetAuthStateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetAuthStateData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthState     *AuthState             `protobuf:"bytes,1,opt,name=auth_state,json=authState,proto3" json:"authState"`  
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthStateData) Reset() {
	*x = GetAuthStateData{}
	mi := &file_authstate_restful_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthStateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthStateData) ProtoMessage() {}

func (x *GetAuthStateData) ProtoReflect() protoreflect.Message {
	mi := &file_authstate_restful_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthStateData.ProtoReflect.Descriptor instead.
func (*GetAuthStateData) Descriptor() ([]byte, []int) {
	return file_authstate_restful_proto_rawDescGZIP(), []int{6}
}

func (x *GetAuthStateData) GetAuthState() *AuthState {
	if x != nil {
		return x.AuthState
	}
	return nil
}

type UpdateAuthStateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountKey    string                 `protobuf:"bytes,1,opt,name=account_key,json=accountKey,proto3" json:"accountKey" binding:"required"`        
	SiteHost      string                 `protobuf:"bytes,2,opt,name=site_host,json=siteHost,proto3" json:"siteHost" binding:"required"`              
	Status        AuthStateStatus        `protobuf:"varint,3,opt,name=status,proto3,enum=authstate.AuthStateStatus" json:"status" binding:"required"`  
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAuthStateStatusRequest) Reset() {
	*x = UpdateAuthStateStatusRequest{}
	mi := &file_authstate_restful_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAuthStateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAuthStateStatusRequest) ProtoMessage() {}

func (x *UpdateAuthStateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authstate_restful_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAuthStateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateAuthStateStatusRequest) Descriptor() ([]byte, []int) {
	return file_authstate_restful_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAuthStateStatusRequest) GetAccountKey() string {
	if x != nil {
		return x.AccountKey
	}
	return ""
}

func (x *UpdateAuthStateStatusRequest) GetSiteHost() string {
	if x != nil {
		return x.SiteHost
	}
	return ""
}

func (x *UpdateAuthStateStatusRequest) GetStatus() AuthStateStatus {
	if x != nil {
		return x.Status
	}
	return AuthStateStatus_AUTH_STATE_STATUS_UNKNOWN
}

type UpdateAuthStateStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,253,opt,name=code,proto3" json:"code"`  
	Msg           string                 `protobuf:"bytes,254,opt,name=msg,proto3" json:"msg"`     
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAuthStateStatusResponse) Reset() {
	*x = UpdateAuthStateStatusResponse{}
	mi := &file_authstate_restful_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAuthStateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAuthStateStatusResponse) ProtoMessage() {}

func (x *UpdateAuthStateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authstate_restful_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAuthStateStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateAuthStateStatusResponse) Descriptor() ([]byte, []int) {
	return file_authstate_restful_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAuthStateStatusResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateAuthStateStatusResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_authstate_restful_proto protoreflect.FileDescriptor

const file_authstate_restful_proto_rawDesc = "" +
	"\n" +
	"\x17authstate/restful.proto\x12\tauthstate\"\xb8\x02\n" +
	"\tAuthState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vaccount_key\x18\x02 \x01(\tR\n" +
	"accountKey\x12\x1b\n" +
	"\tsite_host\x18\x03 \x01(\tR\bsiteHost\x122\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1a.authstate.AuthStateStatusR\x06status\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\x12*\n" +
	"\x11last_validated_at\x18\a \x01(\x03R\x0flastValidatedAt\x12\x1a\n" +
	"\bmetadata\x18\b \x01(\tR\bmetadata\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAtJ\x04\b\x04\x10\x05\"\xb6\x01\n" +
	"\x16ImportAuthStateRequest\x12\x1f\n" +
	"\vaccount_key\x18\x01 \x01(\tR\n" +
	"accountKey\x12\x1b\n" +
	"\tsite_host\x18\x02 \x01(\tR\bsiteHost\x12#\n" +
	"\rstorage_state\x18\x03 \x01(\tR\fstorageState\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\tR\bmetadata\"u\n" +
	"\x17ImportAuthStateResponse\x122\n" +
	"\x04data\x18\x01 \x01(\v2\x1e.authstate.ImportAuthStateDataR\x04data\x12\x13\n" +
	"\x04code\x18\xfd\x01 \x01(\x05R\x04code\x12\x11\n" +
	"\x03msg\x18\xfe\x01 \x01(\tR\x03msg\"+\n" +
	"\x13ImportAuthStateData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02idJ\x04\b\x02\x10\x03\"S\n" +
	"\x13GetAuthStateRequest\x12\x1f\n" +
	"\vaccount_key\x18\x01 \x01(\tR\n" +
	"accountKey\x12\x1b\n" +
	"\tsite_host\x18\x02 \x01(\tR\bsiteHost\"o\n" +
	"\x14GetAuthStateResponse\x12/\n" +
	"\x04data\x18\x01 \x01(\v2\x1b.authstate.GetAuthStateDataR\x04data\x12\x13\n" +
	"\x04code\x18\xfd\x01 \x01(\x05R\x04code\x12\x11\n" +
	"\x03msg\x18\xfe\x01 \x01(\tR\x03msg\"G\n" +
	"\x10GetAuthStateData\x123\n" +
	"\n" +
	"auth_state\x18\x01 \x01(\v2\x14.authstate.AuthStateR\tauthState\"\x90\x01\n" +
	"\x1cUpdateAuthStateStatusRequest\x12\x1f\n" +
	"\vaccount_key\x18\x01 \x01(\tR\n" +
	"accountKey\x12\x1b\n" +
	"\tsite_host\x18\x02 \x01(\tR\bsiteHost\x122\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1a.authstate.AuthStateStatusR\x06status\"G\n" +
	"\x1dUpdateAuthStateStatusResponse\x12\x13\n" +
	"\x04code\x18\xfd\x01 \x01(\x05R\x04code\x12\x11\n" +
	"\x03msg\x18\xfe\x01 \x01(\tR\x03msg*\x8c\x01\n" +
	"\x0fAuthStateStatus\x12\x1d\n" +
	"\x19AUTH_STATE_STATUS_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17AUTH_STATE_STATUS_VALID\x10\x01\x12\x1d\n" +
	"\x19AUTH_STATE_STATUS_EXPIRED\x10\x02\x12\x1e\n" +
	"\x1aAUTH_STATE_STATUS_DISABLED\x10\x03B4Z2sico-backend/internal/transport/http/dto/authstateb\x06proto3"

var (
	file_authstate_restful_proto_rawDescOnce sync.Once
	file_authstate_restful_proto_rawDescData []byte
)

func file_authstate_restful_proto_rawDescGZIP() []byte {
	file_authstate_restful_proto_rawDescOnce.Do(func() {
		file_authstate_restful_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authstate_restful_proto_rawDesc), len(file_authstate_restful_proto_rawDesc)))
	})
	return file_authstate_restful_proto_rawDescData
}

var file_authstate_restful_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_authstate_restful_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_authstate_restful_proto_goTypes = []any{
	(AuthStateStatus)(0),                  // 0: authstate.AuthStateStatus
	(*AuthState)(nil),                     // 1: authstate.AuthState
	(*ImportAuthStateRequest)(nil),        // 2: authstate.ImportAuthStateRequest
	(*ImportAuthStateResponse)(nil),       // 3: authstate.ImportAuthStateResponse
	(*ImportAuthStateData)(nil),           // 4: authstate.ImportAuthStateData
	(*GetAuthStateRequest)(nil),           // 5: authstate.GetAuthStateRequest
	(*GetAuthStateResponse)(nil),          // 6: authstate.GetAuthStateResponse
	(*GetAuthStateData)(nil),              // 7: authstate.GetAuthStateData
	(*UpdateAuthStateStatusRequest)(nil),  // 8: authstate.UpdateAuthStateStatusRequest
	(*UpdateAuthStateStatusResponse)(nil), // 9: authstate.UpdateAuthStateStatusResponse
}
var file_authstate_restful_proto_depIdxs = []int32{
	0, // 0: authstate.AuthState.status:type_name -> authstate.AuthStateStatus
	4, // 1: authstate.ImportAuthStateResponse.data:type_name -> authstate.ImportAuthStateData
	7, // 2: authstate.GetAuthStateResponse.data:type_name -> authstate.GetAuthStateData
	1, // 3: authstate.GetAuthStateData.auth_state:type_name -> authstate.AuthState
	0, // 4: authstate.UpdateAuthStateStatusRequest.status:type_name -> authstate.AuthStateStatus
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_authstate_restful_proto_init() }
func file_authstate_restful_proto_init() {
	if File_authstate_restful_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authstate_restful_proto_rawDesc), len(file_authstate_restful_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authstate_restful_proto_goTypes,
		DependencyIndexes: file_authstate_restful_proto_depIdxs,
		EnumInfos:         file_authstate_restful_proto_enumTypes,
		MessageInfos:      file_authstate_restful_proto_msgTypes,
	}.Build()
	File_authstate_restful_proto = out.File
	file_authstate_restful_proto_goTypes = nil
	file_authstate_restful_proto_depIdxs = nil
}
