// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"sico-backend/internal/store/integration/internal/dal/model"
)

func newTIntegrationBinding(db *gorm.DB, opts ...gen.DOOption) tIntegrationBinding {
	_tIntegrationBinding := tIntegrationBinding{}

	_tIntegrationBinding.tIntegrationBindingDo.UseDB(db, opts...)
	_tIntegrationBinding.tIntegrationBindingDo.UseModel(&model.TIntegrationBinding{})

	tableName := _tIntegrationBinding.tIntegrationBindingDo.TableName()
	_tIntegrationBinding.ALL = field.NewAsterisk(tableName)
	_tIntegrationBinding.ID = field.NewInt64(tableName, "id")
	_tIntegrationBinding.ConnectionID = field.NewInt64(tableName, "connection_id")
	_tIntegrationBinding.SicoScopeType = field.NewInt32(tableName, "sico_scope_type")
	_tIntegrationBinding.SicoScopeID = field.NewString(tableName, "sico_scope_id")
	_tIntegrationBinding.ResourceType = field.NewString(tableName, "resource_type")
	_tIntegrationBinding.ResourceKey = field.NewString(tableName, "resource_key")
	_tIntegrationBinding.ResourceName = field.NewString(tableName, "resource_name")
	_tIntegrationBinding.Status = field.NewInt32(tableName, "status")
	_tIntegrationBinding.Metadata = field.NewField(tableName, "metadata")
	_tIntegrationBinding.CreatorUsername = field.NewString(tableName, "creator_username")
	_tIntegrationBinding.CreatedAt = field.NewInt64(tableName, "created_at")
	_tIntegrationBinding.UpdatedAt = field.NewInt64(tableName, "updated_at")
	_tIntegrationBinding.DeletedAt = field.NewField(tableName, "deleted_at")

	_tIntegrationBinding.fillFieldMap()

	return _tIntegrationBinding
}

// tIntegrationBinding Sico scope to provider resource bindings
type tIntegrationBinding struct {
	tIntegrationBindingDo

	ALL             field.Asterisk
	ID              field.Int64  // Primary key ID
	ConnectionID    field.Int64  // Integration connection ID
	SicoScopeType   field.Int32  // 1=organization, 2=project
	SicoScopeID     field.String // Sico RBAC scope identifier
	ResourceType    field.String // Connector-defined resource kind
	ResourceKey     field.String // Opaque canonical provider resource identifier
	ResourceName    field.String // Provider resource display name
	Status          field.Int32  // 1=active, 2=disabled, 3=inaccessible
	Metadata        field.Field  // Versioned non-secret connector metadata
	CreatorUsername field.String // Creator username
	CreatedAt       field.Int64  // Creation time in Unix milliseconds
	UpdatedAt       field.Int64  // Update time in Unix milliseconds
	DeletedAt       field.Field  // Deletion time

	fieldMap map[string]field.Expr
}

func (t tIntegrationBinding) Table(newTableName string) *tIntegrationBinding {
	t.tIntegrationBindingDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tIntegrationBinding) As(alias string) *tIntegrationBinding {
	t.tIntegrationBindingDo.DO = *(t.tIntegrationBindingDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tIntegrationBinding) updateTableName(table string) *tIntegrationBinding {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.ConnectionID = field.NewInt64(table, "connection_id")
	t.SicoScopeType = field.NewInt32(table, "sico_scope_type")
	t.SicoScopeID = field.NewString(table, "sico_scope_id")
	t.ResourceType = field.NewString(table, "resource_type")
	t.ResourceKey = field.NewString(table, "resource_key")
	t.ResourceName = field.NewString(table, "resource_name")
	t.Status = field.NewInt32(table, "status")
	t.Metadata = field.NewField(table, "metadata")
	t.CreatorUsername = field.NewString(table, "creator_username")
	t.CreatedAt = field.NewInt64(table, "created_at")
	t.UpdatedAt = field.NewInt64(table, "updated_at")
	t.DeletedAt = field.NewField(table, "deleted_at")

	t.fillFieldMap()

	return t
}

func (t *tIntegrationBinding) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tIntegrationBinding) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 13)
	t.fieldMap["id"] = t.ID
	t.fieldMap["connection_id"] = t.ConnectionID
	t.fieldMap["sico_scope_type"] = t.SicoScopeType
	t.fieldMap["sico_scope_id"] = t.SicoScopeID
	t.fieldMap["resource_type"] = t.ResourceType
	t.fieldMap["resource_key"] = t.ResourceKey
	t.fieldMap["resource_name"] = t.ResourceName
	t.fieldMap["status"] = t.Status
	t.fieldMap["metadata"] = t.Metadata
	t.fieldMap["creator_username"] = t.CreatorUsername
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["deleted_at"] = t.DeletedAt
}

func (t tIntegrationBinding) clone(db *gorm.DB) tIntegrationBinding {
	t.tIntegrationBindingDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tIntegrationBinding) replaceDB(db *gorm.DB) tIntegrationBinding {
	t.tIntegrationBindingDo.ReplaceDB(db)
	return t
}

type tIntegrationBindingDo struct{ gen.DO }

type ITIntegrationBindingDo interface {
	gen.SubQuery
	Debug() ITIntegrationBindingDo
	WithContext(ctx context.Context) ITIntegrationBindingDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITIntegrationBindingDo
	WriteDB() ITIntegrationBindingDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITIntegrationBindingDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITIntegrationBindingDo
	Not(conds ...gen.Condition) ITIntegrationBindingDo
	Or(conds ...gen.Condition) ITIntegrationBindingDo
	Select(conds ...field.Expr) ITIntegrationBindingDo
	Where(conds ...gen.Condition) ITIntegrationBindingDo
	Order(conds ...field.Expr) ITIntegrationBindingDo
	Distinct(cols ...field.Expr) ITIntegrationBindingDo
	Omit(cols ...field.Expr) ITIntegrationBindingDo
	Join(table schema.Tabler, on ...field.Expr) ITIntegrationBindingDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITIntegrationBindingDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITIntegrationBindingDo
	Group(cols ...field.Expr) ITIntegrationBindingDo
	Having(conds ...gen.Condition) ITIntegrationBindingDo
	Limit(limit int) ITIntegrationBindingDo
	Offset(offset int) ITIntegrationBindingDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITIntegrationBindingDo
	Unscoped() ITIntegrationBindingDo
	Create(values ...*model.TIntegrationBinding) error
	CreateInBatches(values []*model.TIntegrationBinding, batchSize int) error
	Save(values ...*model.TIntegrationBinding) error
	First() (*model.TIntegrationBinding, error)
	Take() (*model.TIntegrationBinding, error)
	Last() (*model.TIntegrationBinding, error)
	Find() ([]*model.TIntegrationBinding, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TIntegrationBinding, err error)
	FindInBatches(result *[]*model.TIntegrationBinding, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TIntegrationBinding) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITIntegrationBindingDo
	Assign(attrs ...field.AssignExpr) ITIntegrationBindingDo
	Joins(fields ...field.RelationField) ITIntegrationBindingDo
	Preload(fields ...field.RelationField) ITIntegrationBindingDo
	FirstOrInit() (*model.TIntegrationBinding, error)
	FirstOrCreate() (*model.TIntegrationBinding, error)
	FindByPage(offset int, limit int) (result []*model.TIntegrationBinding, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITIntegrationBindingDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tIntegrationBindingDo) Debug() ITIntegrationBindingDo {
	return t.withDO(t.DO.Debug())
}

func (t tIntegrationBindingDo) WithContext(ctx context.Context) ITIntegrationBindingDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tIntegrationBindingDo) ReadDB() ITIntegrationBindingDo {
	return t.Clauses(dbresolver.Read)
}

func (t tIntegrationBindingDo) WriteDB() ITIntegrationBindingDo {
	return t.Clauses(dbresolver.Write)
}

func (t tIntegrationBindingDo) Session(config *gorm.Session) ITIntegrationBindingDo {
	return t.withDO(t.DO.Session(config))
}

func (t tIntegrationBindingDo) Clauses(conds ...clause.Expression) ITIntegrationBindingDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tIntegrationBindingDo) Returning(value interface{}, columns ...string) ITIntegrationBindingDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tIntegrationBindingDo) Not(conds ...gen.Condition) ITIntegrationBindingDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tIntegrationBindingDo) Or(conds ...gen.Condition) ITIntegrationBindingDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tIntegrationBindingDo) Select(conds ...field.Expr) ITIntegrationBindingDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tIntegrationBindingDo) Where(conds ...gen.Condition) ITIntegrationBindingDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tIntegrationBindingDo) Order(conds ...field.Expr) ITIntegrationBindingDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tIntegrationBindingDo) Distinct(cols ...field.Expr) ITIntegrationBindingDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tIntegrationBindingDo) Omit(cols ...field.Expr) ITIntegrationBindingDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tIntegrationBindingDo) Join(table schema.Tabler, on ...field.Expr) ITIntegrationBindingDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tIntegrationBindingDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITIntegrationBindingDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tIntegrationBindingDo) RightJoin(table schema.Tabler, on ...field.Expr) ITIntegrationBindingDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tIntegrationBindingDo) Group(cols ...field.Expr) ITIntegrationBindingDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tIntegrationBindingDo) Having(conds ...gen.Condition) ITIntegrationBindingDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tIntegrationBindingDo) Limit(limit int) ITIntegrationBindingDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tIntegrationBindingDo) Offset(offset int) ITIntegrationBindingDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tIntegrationBindingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITIntegrationBindingDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tIntegrationBindingDo) Unscoped() ITIntegrationBindingDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tIntegrationBindingDo) Create(values ...*model.TIntegrationBinding) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tIntegrationBindingDo) CreateInBatches(values []*model.TIntegrationBinding, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tIntegrationBindingDo) Save(values ...*model.TIntegrationBinding) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tIntegrationBindingDo) First() (*model.TIntegrationBinding, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TIntegrationBinding), nil
	}
}

func (t tIntegrationBindingDo) Take() (*model.TIntegrationBinding, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TIntegrationBinding), nil
	}
}

func (t tIntegrationBindingDo) Last() (*model.TIntegrationBinding, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TIntegrationBinding), nil
	}
}

func (t tIntegrationBindingDo) Find() ([]*model.TIntegrationBinding, error) {
	result, err := t.DO.Find()
	return result.([]*model.TIntegrationBinding), err
}

func (t tIntegrationBindingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TIntegrationBinding, err error) {
	buf := make([]*model.TIntegrationBinding, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tIntegrationBindingDo) FindInBatches(result *[]*model.TIntegrationBinding, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tIntegrationBindingDo) Attrs(attrs ...field.AssignExpr) ITIntegrationBindingDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tIntegrationBindingDo) Assign(attrs ...field.AssignExpr) ITIntegrationBindingDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tIntegrationBindingDo) Joins(fields ...field.RelationField) ITIntegrationBindingDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tIntegrationBindingDo) Preload(fields ...field.RelationField) ITIntegrationBindingDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tIntegrationBindingDo) FirstOrInit() (*model.TIntegrationBinding, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TIntegrationBinding), nil
	}
}

func (t tIntegrationBindingDo) FirstOrCreate() (*model.TIntegrationBinding, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TIntegrationBinding), nil
	}
}

func (t tIntegrationBindingDo) FindByPage(offset int, limit int) (result []*model.TIntegrationBinding, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tIntegrationBindingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tIntegrationBindingDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tIntegrationBindingDo) Delete(models ...*model.TIntegrationBinding) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tIntegrationBindingDo) withDO(do gen.Dao) *tIntegrationBindingDo {
	t.DO = *do.(*gen.DO)
	return t
}
