// Copyright (c) 2026 Sico Authors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: skill/skill.proto

package skill

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Skill status
type SkillStatus int32

const (
	SkillStatus_SKILL_STATUS_UNKNOWN   SkillStatus = 0 // @gotag: json:"SKILL_STATUS_UNKNOWN"
	SkillStatus_SKILL_STATUS_UPLOADING SkillStatus = 1 // @gotag: json:"SKILL_STATUS_UPLOADING"
	SkillStatus_SKILL_STATUS_UPLOADED  SkillStatus = 2 // @gotag: json:"SKILL_STATUS_UPLOADED"
	SkillStatus_SKILL_STATUS_FAILED    SkillStatus = 3 // @gotag: json:"SKILL_STATUS_FAILED"
)

// Enum value maps for SkillStatus.
var (
	SkillStatus_name = map[int32]string{
		0: "SKILL_STATUS_UNKNOWN",
		1: "SKILL_STATUS_UPLOADING",
		2: "SKILL_STATUS_UPLOADED",
		3: "SKILL_STATUS_FAILED",
	}
	SkillStatus_value = map[string]int32{
		"SKILL_STATUS_UNKNOWN":   0,
		"SKILL_STATUS_UPLOADING": 1,
		"SKILL_STATUS_UPLOADED":  2,
		"SKILL_STATUS_FAILED":    3,
	}
)

func (x SkillStatus) Enum() *SkillStatus {
	p := new(SkillStatus)
	*p = x
	return p
}

func (x SkillStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SkillStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_skill_skill_proto_enumTypes[0].Descriptor()
}

func (SkillStatus) Type() protoreflect.EnumType {
	return &file_skill_skill_proto_enumTypes[0]
}

func (x SkillStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SkillStatus.Descriptor instead.
func (SkillStatus) EnumDescriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{0}
}

// Skill entity
type Skill struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`                                                  
	ProjectId       int64                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"projectId"`                   
	AgentId         string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agentId"`                          
	Name            string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name"`                                               
	Description     string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description"`                                 
	AssetId         int64                  `protobuf:"varint,6,opt,name=asset_id,json=assetId,proto3" json:"assetId"`                         
	CreatorUsername string                 `protobuf:"bytes,7,opt,name=creator_username,json=creatorUsername,proto3" json:"creatorUsername"`  
	Status          SkillStatus            `protobuf:"varint,8,opt,name=status,proto3,enum=skill.SkillStatus" json:"status"`                   
	FailReason      string                 `protobuf:"bytes,9,opt,name=fail_reason,json=failReason,proto3" json:"failReason"`                 
	CreatedAt       int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"createdAt"`                  
	UpdatedAt       int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updatedAt"`                  
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_skill_skill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{0}
}

func (x *Skill) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Skill) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *Skill) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Skill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Skill) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Skill) GetAssetId() int64 {
	if x != nil {
		return x.AssetId
	}
	return 0
}

func (x *Skill) GetCreatorUsername() string {
	if x != nil {
		return x.CreatorUsername
	}
	return ""
}

func (x *Skill) GetStatus() SkillStatus {
	if x != nil {
		return x.Status
	}
	return SkillStatus_SKILL_STATUS_UNKNOWN
}

func (x *Skill) GetFailReason() string {
	if x != nil {
		return x.FailReason
	}
	return ""
}

func (x *Skill) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Skill) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// Create Skill
type CreateSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"projectId" form:"projectId"`  
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agentId" form:"agentId"`         
	AssetId       int64                  `protobuf:"varint,3,opt,name=asset_id,json=assetId,proto3" json:"assetId" form:"assetId" binding:"required"`        
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSkillRequest) Reset() {
	*x = CreateSkillRequest{}
	mi := &file_skill_skill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkillRequest) ProtoMessage() {}

func (x *CreateSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkillRequest.ProtoReflect.Descriptor instead.
func (*CreateSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSkillRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *CreateSkillRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateSkillRequest) GetAssetId() int64 {
	if x != nil {
		return x.AssetId
	}
	return 0
}

type CreateSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *CreateSkillData       `protobuf:"bytes,1,opt,name=data,proto3" json:"data"`     
	Code          int32                  `protobuf:"varint,253,opt,name=code,proto3" json:"code"`  
	Msg           string                 `protobuf:"bytes,254,opt,name=msg,proto3" json:"msg"`     
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSkillResponse) Reset() {
	*x = CreateSkillResponse{}
	mi := &file_skill_skill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkillResponse) ProtoMessage() {}

func (x *CreateSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkillResponse.ProtoReflect.Descriptor instead.
func (*CreateSkillResponse) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSkillResponse) GetData() *CreateSkillData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateSkillResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateSkillResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CreateSkillData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skill         *Skill                 `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill"`  
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSkillData) Reset() {
	*x = CreateSkillData{}
	mi := &file_skill_skill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkillData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkillData) ProtoMessage() {}

func (x *CreateSkillData) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkillData.ProtoReflect.Descriptor instead.
func (*CreateSkillData) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSkillData) GetSkill() *Skill {
	if x != nil {
		return x.Skill
	}
	return nil
}

// Get Skill
type GetSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" form:"id" binding:"required"`  
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillRequest) Reset() {
	*x = GetSkillRequest{}
	mi := &file_skill_skill_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillRequest) ProtoMessage() {}

func (x *GetSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillRequest.ProtoReflect.Descriptor instead.
func (*GetSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{4}
}

func (x *GetSkillRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *GetSkillData          `protobuf:"bytes,1,opt,name=data,proto3" json:"data"`     
	Code          int32                  `protobuf:"varint,253,opt,name=code,proto3" json:"code"`  
	Msg           string                 `protobuf:"bytes,254,opt,name=msg,proto3" json:"msg"`     
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillResponse) Reset() {
	*x = GetSkillResponse{}
	mi := &file_skill_skill_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillResponse) ProtoMessage() {}

func (x *GetSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillResponse.ProtoReflect.Descriptor instead.
func (*GetSkillResponse) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{5}
}

func (x *GetSkillResponse) GetData() *GetSkillData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetSkillResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetSkillResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetSkillData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skill         *Skill                 `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill"`  
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillData) Reset() {
	*x = GetSkillData{}
	mi := &file_skill_skill_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillData) ProtoMessage() {}

func (x *GetSkillData) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillData.ProtoReflect.Descriptor instead.
func (*GetSkillData) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{6}
}

func (x *GetSkillData) GetSkill() *Skill {
	if x != nil {
		return x.Skill
	}
	return nil
}

// Update Skill
type UpdateSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" form:"id" binding:"required"`                           
	AssetId       int64                  `protobuf:"varint,2,opt,name=asset_id,json=assetId,proto3" json:"assetId" form:"assetId" binding:"required"`  
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSkillRequest) Reset() {
	*x = UpdateSkillRequest{}
	mi := &file_skill_skill_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSkillRequest) ProtoMessage() {}

func (x *UpdateSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSkillRequest.ProtoReflect.Descriptor instead.
func (*UpdateSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSkillRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSkillRequest) GetAssetId() int64 {
	if x != nil {
		return x.AssetId
	}
	return 0
}

type UpdateSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *UpdateSkillData       `protobuf:"bytes,1,opt,name=data,proto3" json:"data"`     
	Code          int32                  `protobuf:"varint,253,opt,name=code,proto3" json:"code"`  
	Msg           string                 `protobuf:"bytes,254,opt,name=msg,proto3" json:"msg"`     
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSkillResponse) Reset() {
	*x = UpdateSkillResponse{}
	mi := &file_skill_skill_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSkillResponse) ProtoMessage() {}

func (x *UpdateSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSkillResponse.ProtoReflect.Descriptor instead.
func (*UpdateSkillResponse) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateSkillResponse) GetData() *UpdateSkillData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateSkillResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateSkillResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdateSkillData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skill         *Skill                 `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill"`  
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSkillData) Reset() {
	*x = UpdateSkillData{}
	mi := &file_skill_skill_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSkillData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSkillData) ProtoMessage() {}

func (x *UpdateSkillData) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSkillData.ProtoReflect.Descriptor instead.
func (*UpdateSkillData) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateSkillData) GetSkill() *Skill {
	if x != nil {
		return x.Skill
	}
	return nil
}

// Delete Skill
type DeleteSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" form:"id" binding:"required"`  
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSkillRequest) Reset() {
	*x = DeleteSkillRequest{}
	mi := &file_skill_skill_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSkillRequest) ProtoMessage() {}

func (x *DeleteSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSkillRequest.ProtoReflect.Descriptor instead.
func (*DeleteSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteSkillRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,253,opt,name=code,proto3" json:"code"`  
	Msg           string                 `protobuf:"bytes,254,opt,name=msg,proto3" json:"msg"`     
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSkillResponse) Reset() {
	*x = DeleteSkillResponse{}
	mi := &file_skill_skill_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSkillResponse) ProtoMessage() {}

func (x *DeleteSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSkillResponse.ProtoReflect.Descriptor instead.
func (*DeleteSkillResponse) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteSkillResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteSkillResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// List Skills
type ListSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty" form:"projectId"`  
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty" form:"agentId"`         
	Status        SkillStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=skill.SkillStatus" json:"status,omitempty" form:"status"`  
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty" form:"page" binding:"required,min=1"`                             
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty" form:"pageSize" binding:"required,min=1,max=100"`     
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillRequest) Reset() {
	*x = ListSkillRequest{}
	mi := &file_skill_skill_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillRequest) ProtoMessage() {}

func (x *ListSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillRequest.ProtoReflect.Descriptor instead.
func (*ListSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{12}
}

func (x *ListSkillRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ListSkillRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListSkillRequest) GetStatus() SkillStatus {
	if x != nil {
		return x.Status
	}
	return SkillStatus_SKILL_STATUS_UNKNOWN
}

func (x *ListSkillRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSkillRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *ListSkillData         `protobuf:"bytes,1,opt,name=data,proto3" json:"data"`     
	Code          int32                  `protobuf:"varint,253,opt,name=code,proto3" json:"code"`  
	Msg           string                 `protobuf:"bytes,254,opt,name=msg,proto3" json:"msg"`     
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillResponse) Reset() {
	*x = ListSkillResponse{}
	mi := &file_skill_skill_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillResponse) ProtoMessage() {}

func (x *ListSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillResponse.ProtoReflect.Descriptor instead.
func (*ListSkillResponse) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{13}
}

func (x *ListSkillResponse) GetData() *ListSkillData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListSkillResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListSkillResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ListSkillData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skills        []*Skill               `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills"`                    
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total"`                     
	HasNext       bool                   `protobuf:"varint,3,opt,name=has_next,json=hasNext,proto3" json:"hasNext"`  
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillData) Reset() {
	*x = ListSkillData{}
	mi := &file_skill_skill_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillData) ProtoMessage() {}

func (x *ListSkillData) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillData.ProtoReflect.Descriptor instead.
func (*ListSkillData) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{14}
}

func (x *ListSkillData) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ListSkillData) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListSkillData) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

// Get Skill Details (returns file contents)
type GetSkillDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" form:"id" binding:"required"`  
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillDetailsRequest) Reset() {
	*x = GetSkillDetailsRequest{}
	mi := &file_skill_skill_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillDetailsRequest) ProtoMessage() {}

func (x *GetSkillDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetSkillDetailsRequest) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{15}
}

func (x *GetSkillDetailsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetSkillDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *GetSkillDetailsData   `protobuf:"bytes,1,opt,name=data,proto3" json:"data"`     
	Code          int32                  `protobuf:"varint,253,opt,name=code,proto3" json:"code"`  
	Msg           string                 `protobuf:"bytes,254,opt,name=msg,proto3" json:"msg"`     
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillDetailsResponse) Reset() {
	*x = GetSkillDetailsResponse{}
	mi := &file_skill_skill_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillDetailsResponse) ProtoMessage() {}

func (x *GetSkillDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetSkillDetailsResponse) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{16}
}

func (x *GetSkillDetailsResponse) GetData() *GetSkillDetailsData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetSkillDetailsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetSkillDetailsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetSkillDetailsData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*SkillFile           `protobuf:"bytes,1,rep,name=files,proto3" json:"files"`  
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillDetailsData) Reset() {
	*x = GetSkillDetailsData{}
	mi := &file_skill_skill_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillDetailsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillDetailsData) ProtoMessage() {}

func (x *GetSkillDetailsData) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillDetailsData.ProtoReflect.Descriptor instead.
func (*GetSkillDetailsData) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{17}
}

func (x *GetSkillDetailsData) GetFiles() []*SkillFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type SkillFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path"`        
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content"`  
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillFile) Reset() {
	*x = SkillFile{}
	mi := &file_skill_skill_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillFile) ProtoMessage() {}

func (x *SkillFile) ProtoReflect() protoreflect.Message {
	mi := &file_skill_skill_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillFile.ProtoReflect.Descriptor instead.
func (*SkillFile) Descriptor() ([]byte, []int) {
	return file_skill_skill_proto_rawDescGZIP(), []int{18}
}

func (x *SkillFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SkillFile) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_skill_skill_proto protoreflect.FileDescriptor

const file_skill_skill_proto_rawDesc = "" +
	"\n" +
	"\x11skill/skill.proto\x12\x05skill\"\xd8\x02\n" +
	"\x05Skill\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x03R\tprojectId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x19\n" +
	"\basset_id\x18\x06 \x01(\x03R\aassetId\x12)\n" +
	"\x10creator_username\x18\a \x01(\tR\x0fcreatorUsername\x12*\n" +
	"\x06status\x18\b \x01(\x0e2\x12.skill.SkillStatusR\x06status\x12\x1f\n" +
	"\vfail_reason\x18\t \x01(\tR\n" +
	"failReason\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\"i\n" +
	"\x12CreateSkillRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x19\n" +
	"\basset_id\x18\x03 \x01(\x03R\aassetId\"i\n" +
	"\x13CreateSkillResponse\x12*\n" +
	"\x04data\x18\x01 \x01(\v2\x16.skill.CreateSkillDataR\x04data\x12\x13\n" +
	"\x04code\x18\xfd\x01 \x01(\x05R\x04code\x12\x11\n" +
	"\x03msg\x18\xfe\x01 \x01(\tR\x03msg\"5\n" +
	"\x0fCreateSkillData\x12\"\n" +
	"\x05skill\x18\x01 \x01(\v2\f.skill.SkillR\x05skill\"!\n" +
	"\x0fGetSkillRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"c\n" +
	"\x10GetSkillResponse\x12'\n" +
	"\x04data\x18\x01 \x01(\v2\x13.skill.GetSkillDataR\x04data\x12\x13\n" +
	"\x04code\x18\xfd\x01 \x01(\x05R\x04code\x12\x11\n" +
	"\x03msg\x18\xfe\x01 \x01(\tR\x03msg\"2\n" +
	"\fGetSkillData\x12\"\n" +
	"\x05skill\x18\x01 \x01(\v2\f.skill.SkillR\x05skill\"?\n" +
	"\x12UpdateSkillRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\x03R\aassetId\"i\n" +
	"\x13UpdateSkillResponse\x12*\n" +
	"\x04data\x18\x01 \x01(\v2\x16.skill.UpdateSkillDataR\x04data\x12\x13\n" +
	"\x04code\x18\xfd\x01 \x01(\x05R\x04code\x12\x11\n" +
	"\x03msg\x18\xfe\x01 \x01(\tR\x03msg\"5\n" +
	"\x0fUpdateSkillData\x12\"\n" +
	"\x05skill\x18\x01 \x01(\v2\f.skill.SkillR\x05skill\"$\n" +
	"\x12DeleteSkillRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"=\n" +
	"\x13DeleteSkillResponse\x12\x13\n" +
	"\x04code\x18\xfd\x01 \x01(\x05R\x04code\x12\x11\n" +
	"\x03msg\x18\xfe\x01 \x01(\tR\x03msg\"\xa9\x01\n" +
	"\x10ListSkillRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12*\n" +
	"\x06status\x18\x03 \x01(\x0e2\x12.skill.SkillStatusR\x06status\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"e\n" +
	"\x11ListSkillResponse\x12(\n" +
	"\x04data\x18\x01 \x01(\v2\x14.skill.ListSkillDataR\x04data\x12\x13\n" +
	"\x04code\x18\xfd\x01 \x01(\x05R\x04code\x12\x11\n" +
	"\x03msg\x18\xfe\x01 \x01(\tR\x03msg\"f\n" +
	"\rListSkillData\x12$\n" +
	"\x06skills\x18\x01 \x03(\v2\f.skill.SkillR\x06skills\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x19\n" +
	"\bhas_next\x18\x03 \x01(\bR\ahasNext\"(\n" +
	"\x16GetSkillDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"q\n" +
	"\x17GetSkillDetailsResponse\x12.\n" +
	"\x04data\x18\x01 \x01(\v2\x1a.skill.GetSkillDetailsDataR\x04data\x12\x13\n" +
	"\x04code\x18\xfd\x01 \x01(\x05R\x04code\x12\x11\n" +
	"\x03msg\x18\xfe\x01 \x01(\tR\x03msg\"=\n" +
	"\x13GetSkillDetailsData\x12&\n" +
	"\x05files\x18\x01 \x03(\v2\x10.skill.SkillFileR\x05files\"9\n" +
	"\tSkillFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent*w\n" +
	"\vSkillStatus\x12\x18\n" +
	"\x14SKILL_STATUS_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16SKILL_STATUS_UPLOADING\x10\x01\x12\x19\n" +
	"\x15SKILL_STATUS_UPLOADED\x10\x02\x12\x17\n" +
	"\x13SKILL_STATUS_FAILED\x10\x03B0Z.sico-backend/internal/transport/http/dto/skillb\x06proto3"

var (
	file_skill_skill_proto_rawDescOnce sync.Once
	file_skill_skill_proto_rawDescData []byte
)

func file_skill_skill_proto_rawDescGZIP() []byte {
	file_skill_skill_proto_rawDescOnce.Do(func() {
		file_skill_skill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skill_skill_proto_rawDesc), len(file_skill_skill_proto_rawDesc)))
	})
	return file_skill_skill_proto_rawDescData
}

var file_skill_skill_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_skill_skill_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_skill_skill_proto_goTypes = []any{
	(SkillStatus)(0),                // 0: skill.SkillStatus
	(*Skill)(nil),                   // 1: skill.Skill
	(*CreateSkillRequest)(nil),      // 2: skill.CreateSkillRequest
	(*CreateSkillResponse)(nil),     // 3: skill.CreateSkillResponse
	(*CreateSkillData)(nil),         // 4: skill.CreateSkillData
	(*GetSkillRequest)(nil),         // 5: skill.GetSkillRequest
	(*GetSkillResponse)(nil),        // 6: skill.GetSkillResponse
	(*GetSkillData)(nil),            // 7: skill.GetSkillData
	(*UpdateSkillRequest)(nil),      // 8: skill.UpdateSkillRequest
	(*UpdateSkillResponse)(nil),     // 9: skill.UpdateSkillResponse
	(*UpdateSkillData)(nil),         // 10: skill.UpdateSkillData
	(*DeleteSkillRequest)(nil),      // 11: skill.DeleteSkillRequest
	(*DeleteSkillResponse)(nil),     // 12: skill.DeleteSkillResponse
	(*ListSkillRequest)(nil),        // 13: skill.ListSkillRequest
	(*ListSkillResponse)(nil),       // 14: skill.ListSkillResponse
	(*ListSkillData)(nil),           // 15: skill.ListSkillData
	(*GetSkillDetailsRequest)(nil),  // 16: skill.GetSkillDetailsRequest
	(*GetSkillDetailsResponse)(nil), // 17: skill.GetSkillDetailsResponse
	(*GetSkillDetailsData)(nil),     // 18: skill.GetSkillDetailsData
	(*SkillFile)(nil),               // 19: skill.SkillFile
}
var file_skill_skill_proto_depIdxs = []int32{
	0,  // 0: skill.Skill.status:type_name -> skill.SkillStatus
	4,  // 1: skill.CreateSkillResponse.data:type_name -> skill.CreateSkillData
	1,  // 2: skill.CreateSkillData.skill:type_name -> skill.Skill
	7,  // 3: skill.GetSkillResponse.data:type_name -> skill.GetSkillData
	1,  // 4: skill.GetSkillData.skill:type_name -> skill.Skill
	10, // 5: skill.UpdateSkillResponse.data:type_name -> skill.UpdateSkillData
	1,  // 6: skill.UpdateSkillData.skill:type_name -> skill.Skill
	0,  // 7: skill.ListSkillRequest.status:type_name -> skill.SkillStatus
	15, // 8: skill.ListSkillResponse.data:type_name -> skill.ListSkillData
	1,  // 9: skill.ListSkillData.skills:type_name -> skill.Skill
	18, // 10: skill.GetSkillDetailsResponse.data:type_name -> skill.GetSkillDetailsData
	19, // 11: skill.GetSkillDetailsData.files:type_name -> skill.SkillFile
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_skill_skill_proto_init() }
func file_skill_skill_proto_init() {
	if File_skill_skill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skill_skill_proto_rawDesc), len(file_skill_skill_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_skill_skill_proto_goTypes,
		DependencyIndexes: file_skill_skill_proto_depIdxs,
		EnumInfos:         file_skill_skill_proto_enumTypes,
		MessageInfos:      file_skill_skill_proto_msgTypes,
	}.Build()
	File_skill_skill_proto = out.File
	file_skill_skill_proto_goTypes = nil
	file_skill_skill_proto_depIdxs = nil
}
