// Code generated by otelwrapgen; DO NOT EDIT.
package repository

import (
	"context"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
	entity "sico-backend/internal/entity/rbac"
)

func WithTracingCasbinRuleRepository(next CasbinRuleRepository) CasbinRuleRepository {
	if next == nil {
		return nil
	}
	return &otelTracedCasbinRuleRepository{next: next}
}

type otelTracedCasbinRuleRepository struct {
	next CasbinRuleRepository
}

func (w *otelTracedCasbinRuleRepository) Create(ctx context.Context, rule *PolicyModel) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "CasbinRuleRepository.Create")
	defer span.End()

	ret0 := w.next.Create(ctx, rule)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedCasbinRuleRepository) Delete(ctx context.Context, id int64) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "CasbinRuleRepository.Delete")
	defer span.End()

	ret0 := w.next.Delete(ctx, id)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedCasbinRuleRepository) Get(ctx context.Context, id int64) (*PolicyModel, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "CasbinRuleRepository.Get")
	defer span.End()

	ret0, ret1 := w.next.Get(ctx, id)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedCasbinRuleRepository) GetByRule(ctx context.Context, ptype string, rule []string) (*PolicyModel, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "CasbinRuleRepository.GetByRule")
	defer span.End()

	ret0, ret1 := w.next.GetByRule(ctx, ptype, rule)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedCasbinRuleRepository) Query(ctx context.Context, ptype string, v0 string, v1 string, v2 string, page int32, pageSize int32) ([]*PolicyModel, int64, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "CasbinRuleRepository.Query")
	defer span.End()

	ret0, ret1, ret2 := w.next.Query(ctx, ptype, v0, v1, v2, page, pageSize)
	if ret2 != nil {
		span.RecordError(ret2)
		span.SetStatus(codes.Error, ret2.Error())
	}
	return ret0, ret1, ret2
}

func (w *otelTracedCasbinRuleRepository) Update(ctx context.Context, rule *PolicyModel) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "CasbinRuleRepository.Update")
	defer span.End()

	ret0 := w.next.Update(ctx, rule)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func WithTracingUserRepository(next UserRepository) UserRepository {
	if next == nil {
		return nil
	}
	return &otelTracedUserRepository{next: next}
}

type otelTracedUserRepository struct {
	next UserRepository
}

func (w *otelTracedUserRepository) CreateUser(ctx context.Context, user *UserModel) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "UserRepository.CreateUser")
	defer span.End()

	ret0 := w.next.CreateUser(ctx, user)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedUserRepository) DeleteUser(ctx context.Context, id int64) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "UserRepository.DeleteUser")
	defer span.End()

	ret0 := w.next.DeleteUser(ctx, id)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedUserRepository) GetUserByEmail(ctx context.Context, email string) (*UserModel, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "UserRepository.GetUserByEmail")
	defer span.End()

	ret0, ret1 := w.next.GetUserByEmail(ctx, email)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedUserRepository) GetUserByID(ctx context.Context, id int64) (*UserModel, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "UserRepository.GetUserByID")
	defer span.End()

	ret0, ret1 := w.next.GetUserByID(ctx, id)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedUserRepository) GetUserByUsername(ctx context.Context, username string) (*UserModel, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "UserRepository.GetUserByUsername")
	defer span.End()

	ret0, ret1 := w.next.GetUserByUsername(ctx, username)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedUserRepository) GetUsersByIDs(ctx context.Context, ids []int64) ([]*UserModel, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "UserRepository.GetUsersByIDs")
	defer span.End()

	ret0, ret1 := w.next.GetUsersByIDs(ctx, ids)
	if ret1 != nil {
		span.RecordError(ret1)
		span.SetStatus(codes.Error, ret1.Error())
	}
	return ret0, ret1
}

func (w *otelTracedUserRepository) QueryUsers(ctx context.Context, filter *entity.UserFilter, page int32, pageSize int32) ([]*UserModel, int64, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "UserRepository.QueryUsers")
	defer span.End()

	ret0, ret1, ret2 := w.next.QueryUsers(ctx, filter, page, pageSize)
	if ret2 != nil {
		span.RecordError(ret2)
		span.SetStatus(codes.Error, ret2.Error())
	}
	return ret0, ret1, ret2
}

func (w *otelTracedUserRepository) UpdatePassword(ctx context.Context, id int64, hashedPassword string) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "UserRepository.UpdatePassword")
	defer span.End()

	ret0 := w.next.UpdatePassword(ctx, id, hashedPassword)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedUserRepository) UpdateUser(ctx context.Context, user *UserModel) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "UserRepository.UpdateUser")
	defer span.End()

	ret0 := w.next.UpdateUser(ctx, user)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedUserRepository) UpdateUserFields(ctx context.Context, id int64, fields map[string]interface{}) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "UserRepository.UpdateUserFields")
	defer span.End()

	ret0 := w.next.UpdateUserFields(ctx, id, fields)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func WithTracingUserRoleRepository(next UserRoleRepository) UserRoleRepository {
	if next == nil {
		return nil
	}
	return &otelTracedUserRoleRepository{next: next}
}

type otelTracedUserRoleRepository struct {
	next UserRoleRepository
}

func (w *otelTracedUserRoleRepository) Assign(ctx context.Context, ur *UserRoleModel) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "UserRoleRepository.Assign")
	defer span.End()

	ret0 := w.next.Assign(ctx, ur)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedUserRoleRepository) List(ctx context.Context, filter *UserRoleFilter) ([]*UserRoleModel, int64, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "UserRoleRepository.List")
	defer span.End()

	ret0, ret1, ret2 := w.next.List(ctx, filter)
	if ret2 != nil {
		span.RecordError(ret2)
		span.SetStatus(codes.Error, ret2.Error())
	}
	return ret0, ret1, ret2
}

func (w *otelTracedUserRoleRepository) Remove(ctx context.Context, userID int64, roleCode string, scopeType string, scopeID string) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "UserRoleRepository.Remove")
	defer span.End()

	ret0 := w.next.Remove(ctx, userID, roleCode, scopeType, scopeID)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}
