// Code generated by otelwrapgen; DO NOT EDIT.
package repository

import (
	"context"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
)

func WithTracingTaskRuntimeRepository(next TaskRuntimeRepository) TaskRuntimeRepository {
	if next == nil {
		return nil
	}
	return &otelTracedTaskRuntimeRepository{next: next}
}

type otelTracedTaskRuntimeRepository struct {
	next TaskRuntimeRepository
}

func (w *otelTracedTaskRuntimeRepository) CancelBatch(ctx context.Context, batchID string, reason string) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "TaskRuntimeRepository.CancelBatch")
	defer span.End()

	ret0 := w.next.CancelBatch(ctx, batchID, reason)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedTaskRuntimeRepository) CancelRun(ctx context.Context, runID string, reason string) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "TaskRuntimeRepository.CancelRun")
	defer span.End()

	ret0 := w.next.CancelRun(ctx, runID, reason)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedTaskRuntimeRepository) ClaimRun(ctx context.Context, runID string, workerID string) (string, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "TaskRuntimeRepository.ClaimRun")
	defer span.End()

	tokenJSON, err := w.next.ClaimRun(ctx, runID, workerID)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return tokenJSON, err
}

func (w *otelTracedTaskRuntimeRepository) CreateBatch(ctx context.Context, batchJSON string) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "TaskRuntimeRepository.CreateBatch")
	defer span.End()

	ret0 := w.next.CreateBatch(ctx, batchJSON)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedTaskRuntimeRepository) CreateRun(ctx context.Context, runJSON string) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "TaskRuntimeRepository.CreateRun")
	defer span.End()

	ret0 := w.next.CreateRun(ctx, runJSON)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedTaskRuntimeRepository) GetBatch(ctx context.Context, batchID string) (string, bool, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "TaskRuntimeRepository.GetBatch")
	defer span.End()

	batchJSON, found, err := w.next.GetBatch(ctx, batchID)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return batchJSON, found, err
}

func (w *otelTracedTaskRuntimeRepository) GetRun(ctx context.Context, runID string) (string, bool, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "TaskRuntimeRepository.GetRun")
	defer span.End()

	runJSON, found, err := w.next.GetRun(ctx, runID)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return runJSON, found, err
}

func (w *otelTracedTaskRuntimeRepository) GetTaskDetail(ctx context.Context, runID string, view string) (TaskDetail, bool, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "TaskRuntimeRepository.GetTaskDetail")
	defer span.End()

	detail, found, err := w.next.GetTaskDetail(ctx, runID, view)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return detail, found, err
}

func (w *otelTracedTaskRuntimeRepository) HeartbeatBatch(ctx context.Context, batchID string) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "TaskRuntimeRepository.HeartbeatBatch")
	defer span.End()

	ret0 := w.next.HeartbeatBatch(ctx, batchID)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedTaskRuntimeRepository) ListBatchRuns(ctx context.Context, batchID string) ([]string, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "TaskRuntimeRepository.ListBatchRuns")
	defer span.End()

	runsJSON, err := w.next.ListBatchRuns(ctx, batchID)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return runsJSON, err
}

func (w *otelTracedTaskRuntimeRepository) ListBatchesByTurn(ctx context.Context, parentConversationID int64, parentTurnID int64, activeOnly bool) ([]string, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "TaskRuntimeRepository.ListBatchesByTurn")
	defer span.End()

	batchesJSON, err := w.next.ListBatchesByTurn(ctx, parentConversationID, parentTurnID, activeOnly)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return batchesJSON, err
}

func (w *otelTracedTaskRuntimeRepository) LookupIdempotent(ctx context.Context, idempotencyKey string) (string, bool, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "TaskRuntimeRepository.LookupIdempotent")
	defer span.End()

	runJSON, found, err := w.next.LookupIdempotent(ctx, idempotencyKey)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return runJSON, found, err
}

func (w *otelTracedTaskRuntimeRepository) ReopenRunForRetry(ctx context.Context, runJSON string, expectedAttempt int32) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "TaskRuntimeRepository.ReopenRunForRetry")
	defer span.End()

	ret0 := w.next.ReopenRunForRetry(ctx, runJSON, expectedAttempt)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedTaskRuntimeRepository) SetRunProgress(ctx context.Context, runID string, message string, ts int64) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "TaskRuntimeRepository.SetRunProgress")
	defer span.End()

	ret0 := w.next.SetRunProgress(ctx, runID, message, ts)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedTaskRuntimeRepository) SweepStaleRuns(ctx context.Context, beforeTs int64) ([]string, error) {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "TaskRuntimeRepository.SweepStaleRuns")
	defer span.End()

	staleRunsJSON, err := w.next.SweepStaleRuns(ctx, beforeTs)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return staleRunsJSON, err
}

func (w *otelTracedTaskRuntimeRepository) UpdateBatch(ctx context.Context, batchJSON string) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "TaskRuntimeRepository.UpdateBatch")
	defer span.End()

	ret0 := w.next.UpdateBatch(ctx, batchJSON)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedTaskRuntimeRepository) UpdateRun(ctx context.Context, runJSON string) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "TaskRuntimeRepository.UpdateRun")
	defer span.End()

	ret0 := w.next.UpdateRun(ctx, runJSON)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}

func (w *otelTracedTaskRuntimeRepository) WriteResult(ctx context.Context, runID string, tokenJSON string, resultJSON string) error {
	ctx, span := otel.Tracer("sico-backend/otelwrap").Start(ctx, "TaskRuntimeRepository.WriteResult")
	defer span.End()

	ret0 := w.next.WriteResult(ctx, runID, tokenJSON, resultJSON)
	if ret0 != nil {
		span.RecordError(ret0)
		span.SetStatus(codes.Error, ret0.Error())
	}
	return ret0
}
