# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: common/common.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "AgentInstanceDigest",
    "Attachment",
    "ColumnType",
    "DocTableColumn",
    "DocTableSheet",
    "FileType",
    "NamedTypeInfo",
    "SandboxDigest",
    "SortOrder",
    "TypeInfo",
    "UserDigest",
)

from dataclasses import dataclass

import betterproto2

from ..message_pool import default_message_pool

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class ColumnType(betterproto2.Enum):
    UNKNOWN = 0
    """
    Unknown
    """

    TEXT = 1
    """
    Text
    """

    NUMBER = 2
    """
    Number
    """

    DATE = 3
    """
    Date
    """

    FLOAT = 4
    """
    Float
    """

    BOOLEAN = 5
    """
    Boolean
    """

    IMAGE = 6
    """
    Image
    """

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "COLUMN_TYPE_UNKNOWN",
            1: "COLUMN_TYPE_TEXT",
            2: "COLUMN_TYPE_NUMBER",
            3: "COLUMN_TYPE_DATE",
            4: "COLUMN_TYPE_FLOAT",
            5: "COLUMN_TYPE_BOOLEAN",
            6: "COLUMN_TYPE_IMAGE",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "COLUMN_TYPE_UNKNOWN": 0,
            "COLUMN_TYPE_TEXT": 1,
            "COLUMN_TYPE_NUMBER": 2,
            "COLUMN_TYPE_DATE": 3,
            "COLUMN_TYPE_FLOAT": 4,
            "COLUMN_TYPE_BOOLEAN": 5,
            "COLUMN_TYPE_IMAGE": 6,
        }


class FileType(betterproto2.Enum):
    UNKNOWN = 0

    TYPE_IMAGE = 1

    TYPE_VIDEO = 2

    TYPE_AUDIO = 3

    TYPE_FILE = 4

    TYPE_ARCHIVE = 5

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "FILE_TYPE_UNKNOWN",
            1: "FILE_TYPE_TYPE_IMAGE",
            2: "FILE_TYPE_TYPE_VIDEO",
            3: "FILE_TYPE_TYPE_AUDIO",
            4: "FILE_TYPE_TYPE_FILE",
            5: "FILE_TYPE_TYPE_ARCHIVE",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "FILE_TYPE_UNKNOWN": 0,
            "FILE_TYPE_TYPE_IMAGE": 1,
            "FILE_TYPE_TYPE_VIDEO": 2,
            "FILE_TYPE_TYPE_AUDIO": 3,
            "FILE_TYPE_TYPE_FILE": 4,
            "FILE_TYPE_TYPE_ARCHIVE": 5,
        }


class SortOrder(betterproto2.Enum):
    """
    SortOrder specifies the sort direction for list queries.
    """

    UNSPECIFIED = 0
    """
    Default: DESC
    """

    ASC = 1

    DESC = 2

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "SORT_ORDER_UNSPECIFIED",
            1: "SORT_ORDER_ASC",
            2: "SORT_ORDER_DESC",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "SORT_ORDER_UNSPECIFIED": 0,
            "SORT_ORDER_ASC": 1,
            "SORT_ORDER_DESC": 2,
        }


@dataclass(eq=False, repr=False)
class AgentInstanceDigest(betterproto2.Message):
    """
    AgentInstanceDigest holds display information about an agent instance.
    """

    agent_name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    """
    @gotag: json:"agentName"
    """

    agent_icon_url: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    @gotag: json:"agentIconUrl"
    """

    operator_username: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    """
    @gotag: json:"operatorUsername"
    """

    id: "int" = betterproto2.field(4, betterproto2.TYPE_INT64)
    """
    @gotag: json:"id"
    """


default_message_pool.register_message(
    "common", "AgentInstanceDigest", AgentInstanceDigest
)


@dataclass(eq=False, repr=False)
class Attachment(betterproto2.Message):
    name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    """
    @gotag: json:"name"
    """

    uri: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    @gotag: json:"uri"
    """

    sas_url: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    """
    @gotag: json:"sasUrl"
    """

    type: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)
    """
    @gotag: json:"type"
    """

    size: "int" = betterproto2.field(5, betterproto2.TYPE_INT64)
    """
    @gotag: json:"size"
    """

    id: "int" = betterproto2.field(6, betterproto2.TYPE_INT64)
    """
    @gotag: json:"id"
    """


default_message_pool.register_message("common", "Attachment", Attachment)


@dataclass(eq=False, repr=False)
class DocTableColumn(betterproto2.Message):
    id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    column ID
    """

    column_name: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    column name
    """

    is_semantic: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)
    """
    whether it's a semantic matching column
    """

    sequence: "int" = betterproto2.field(4, betterproto2.TYPE_INT64)
    """
    original column sequence number in excel
    """

    column_type: "ColumnType | None" = betterproto2.field(
        5, betterproto2.TYPE_ENUM, optional=True
    )
    """
    column type
    """

    contains_empty_value: "bool | None" = betterproto2.field(
        6, betterproto2.TYPE_BOOL, optional=True
    )
    """
    whether contains empty values
    """

    desc: "str | None" = betterproto2.field(7, betterproto2.TYPE_STRING, optional=True)
    """
    description
    """


default_message_pool.register_message("common", "DocTableColumn", DocTableColumn)


@dataclass(eq=False, repr=False)
class DocTableSheet(betterproto2.Message):
    id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    sheet number/ID
    """

    sheet_name: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    sheet name
    """

    total_row: "int" = betterproto2.field(3, betterproto2.TYPE_INT64)
    """
    total number of rows
    """


default_message_pool.register_message("common", "DocTableSheet", DocTableSheet)


@dataclass(eq=False, repr=False)
class NamedTypeInfo(betterproto2.Message):
    name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    """
    @gotag: json:"name" binding:"required"
    """

    type: "TypeInfo | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    @gotag: json:"type" binding:"required"
    """


default_message_pool.register_message("common", "NamedTypeInfo", NamedTypeInfo)


@dataclass(eq=False, repr=False)
class SandboxDigest(betterproto2.Message):
    """
    SandboxDigest holds summary information about a sandbox.
    """

    sandbox_id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    """
    @gotag: json:"sandboxId"
    """

    type: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    @gotag: json:"type"
    """

    status: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    """
    @gotag: json:"status"
    """

    endpoint: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)
    """
    @gotag: json:"endpoint"
    """

    vnc_url: "str" = betterproto2.field(5, betterproto2.TYPE_STRING)
    """
    @gotag: json:"vncUrl"
    """

    docs_url: "str" = betterproto2.field(6, betterproto2.TYPE_STRING)
    """
    @gotag: json:"docsUrl"
    """

    display_name: "str" = betterproto2.field(7, betterproto2.TYPE_STRING)
    """
    @gotag: json:"displayName"
    """

    instance_id: "int" = betterproto2.field(8, betterproto2.TYPE_INT64)
    """
    @gotag: json:"instanceId"
    """

    project_id: "int" = betterproto2.field(9, betterproto2.TYPE_INT64)
    """
    @gotag: json:"projectId"
    """

    organization_id: "int" = betterproto2.field(10, betterproto2.TYPE_INT64)
    """
    @gotag: json:"organizationId"
    """


default_message_pool.register_message("common", "SandboxDigest", SandboxDigest)


@dataclass(eq=False, repr=False)
class TypeInfo(betterproto2.Message):
    data_type: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    """
    @gotag: json:"dataType" binding:"required"
    """

    required: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)
    """
    @gotag: json:"required,omitempty"
    """

    description: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    """
    @gotag: json:"description,omitempty"
    """

    elem_type: "TypeInfo | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    @gotag: json:"elemType,omitempty"
    """

    properties: "dict[str, TypeInfo]" = betterproto2.field(
        5,
        betterproto2.TYPE_MAP,
        map_meta=betterproto2.map_meta(
            betterproto2.TYPE_STRING, betterproto2.TYPE_MESSAGE
        ),
    )
    """
    @gotag: json:"properties,omitempty"
    """

    file_sub_type: "str | None" = betterproto2.field(
        6, betterproto2.TYPE_STRING, optional=True
    )
    """
    @gotag: json:"fileSubType,omitempty"
    """


default_message_pool.register_message("common", "TypeInfo", TypeInfo)


@dataclass(eq=False, repr=False)
class UserDigest(betterproto2.Message):
    """
    UserDigest holds summary information about a user.
    """

    id: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    @gotag: json:"id"
    """

    alias: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    @gotag: json:"alias"
    """

    username: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    """
    @gotag: json:"username"
    """

    email: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)
    """
    @gotag: json:"email"
    """

    icon_url: "str" = betterproto2.field(5, betterproto2.TYPE_STRING)
    """
    @gotag: json:"iconUrl"
    """


default_message_pool.register_message("common", "UserDigest", UserDigest)
