syntax = "proto3";
package auth;

option go_package = "sico-backend/internal/transport/http/dto/rbac/token";

import "rbac/rbac_common.proto";

message LoginRequest {
  string email = 1;       // @gotag: json:"email" binding:"required,min=3,max=64"
  string password = 2;    // @gotag: json:"password" binding:"required,min=6,max=128"
}

// Response message for logout
message LoginResponse {
  LoginResponseData data = 1; // @gotag: json:"data"
  int32 code = 253; // @gotag: json:"code"
  string msg = 254; // @gotag: json:"msg"
}

message LoginResponseData {
  TokenInfo token_info = 1; // @gotag: json:"tokenInfo"
  common.User user = 2;    // @gotag: json:"user"
}

// Request message for refreshing token
message RefreshTokenRequest {
}

// Response message for refreshing token
message RefreshTokenResponse {
  RefreshTokenResponseData data = 1; // @gotag: json:"data"
  int32 code = 253;          // @gotag: json:"code"
  string msg = 254;          // @gotag: json:"msg"
}

message RefreshTokenResponseData {
    TokenInfo token_info = 1; // @gotag: json:"tokenInfo"
}

message TokenInfo {
  string access_token = 1;  // @gotag: json:"accessToken"
  string token_type = 2; // @gotag: json:"tokenType"
  int64 expires_at = 3;     // @gotag: json:"expiresAt"
}

// Request message for logout
message LogoutRequest {
}

// Response message for logout
message LogoutResponse {
  int32 code = 253; // @gotag: json:"code"
  string msg = 254; // @gotag: json:"msg"
}
