apiVersion: v1
kind: ConfigMap
metadata:
  name: linux-workstation-sandbox-config
  labels:
    app: linux-workstation-sandbox
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
