import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";

import { AssetDetailMetaPanel } from "@/features/projects/components/asset-detail-meta-panel";

// A local-time value (no `Z`) → formatDateTime renders "2026-01-18 16:31"
// independent of the test machine's timezone.
const CREATED_AT = new Date("2026-01-18T16:31:00").getTime();

describe("AssetDetailMetaPanel", () => {
  it("renders the file name", () => {
    render(<AssetDetailMetaPanel fileName="report.pdf" />);
    expect(screen.getByText("report.pdf")).toBeInTheDocument();
  });

  it("renders the Digital Worker name after 'Generated by'", () => {
    render(<AssetDetailMetaPanel fileName="report.pdf" dwName="Max" />);
    expect(screen.getByText("Generated by Max")).toBeInTheDocument();
  });

  it("falls back to a placeholder when no dwName", () => {
    render(<AssetDetailMetaPanel fileName="report.pdf" />);
    expect(screen.getByText("Generated by —")).toBeInTheDocument();
  });

  it("renders the formatted created time", () => {
    render(
      <AssetDetailMetaPanel fileName="report.pdf" createdAt={CREATED_AT} />,
    );
    expect(screen.getByText("2026-01-18 16:31")).toBeInTheDocument();
  });

  it("renders the human operator", () => {
    render(
      <AssetDetailMetaPanel fileName="report.pdf" operator="Sarah Bennet" />,
    );
    expect(screen.getByText("Sarah Bennet")).toBeInTheDocument();
  });

  it("renders a placeholder when created time is missing", () => {
    render(<AssetDetailMetaPanel fileName="report.pdf" />);
    // Created time + Operator both absent → two em-dash placeholders.
    expect(screen.getAllByText("—")).toHaveLength(2);
  });
});
