// Copyright (c) 2026 Sico Authors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: rbac/rbac_common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserStatus int32

const (
	UserStatus_USER_STATUS_INACTIVE UserStatus = 0
	UserStatus_USER_STATUS_ACTIVE   UserStatus = 1
	UserStatus_USER_STATUS_FROZEN   UserStatus = 2
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "USER_STATUS_INACTIVE",
		1: "USER_STATUS_ACTIVE",
		2: "USER_STATUS_FROZEN",
	}
	UserStatus_value = map[string]int32{
		"USER_STATUS_INACTIVE": 0,
		"USER_STATUS_ACTIVE":   1,
		"USER_STATUS_FROZEN":   2,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rbac_rbac_common_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_rbac_rbac_common_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_rbac_rbac_common_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`                                     
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias"`                                
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username"`                          
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"-"`                          
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email"`                                
	Tenant        string                 `protobuf:"bytes,6,opt,name=tenant,proto3" json:"tenant"`                              
	Phone         string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone"`                                
	IconUri       string                 `protobuf:"bytes,8,opt,name=icon_uri,json=iconUri,proto3" json:"iconUri"`             
	RawIconUri    string                 `protobuf:"bytes,9,opt,name=raw_icon_uri,json=rawIconUri,proto3" json:"rawIconUri"`  
	Status        UserStatus             `protobuf:"varint,10,opt,name=status,proto3,enum=common.UserStatus" json:"status"`     
	Description   string                 `protobuf:"bytes,11,opt,name=description,proto3" json:"description"`                   
	Roles         []string               `protobuf:"bytes,12,rep,name=roles,proto3" json:"roles"`                               
	CreatedAt     int64                  `protobuf:"varint,13,opt,name=created_at,json=createdAt,proto3" json:"createdAt"`     
	UpdatedAt     int64                  `protobuf:"varint,14,opt,name=updated_at,json=updatedAt,proto3" json:"updatedAt"`     
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_rbac_rbac_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_rbac_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_rbac_rbac_common_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetIconUri() string {
	if x != nil {
		return x.IconUri
	}
	return ""
}

func (x *User) GetRawIconUri() string {
	if x != nil {
		return x.RawIconUri
	}
	return ""
}

func (x *User) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_INACTIVE
}

func (x *User) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *User) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *User) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *User) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_rbac_rbac_common_proto protoreflect.FileDescriptor

const file_rbac_rbac_common_proto_rawDesc = "" +
	"\n" +
	"\x16rbac/rbac_common.proto\x12\x06common\"\x87\x03\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x16\n" +
	"\x06tenant\x18\x06 \x01(\tR\x06tenant\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12\x19\n" +
	"\bicon_uri\x18\b \x01(\tR\aiconUri\x12 \n" +
	"\fraw_icon_uri\x18\t \x01(\tR\n" +
	"rawIconUri\x12*\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x12.common.UserStatusR\x06status\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription\x12\x14\n" +
	"\x05roles\x18\f \x03(\tR\x05roles\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\x03R\tupdatedAt*V\n" +
	"\n" +
	"UserStatus\x12\x18\n" +
	"\x14USER_STATUS_INACTIVE\x10\x00\x12\x16\n" +
	"\x12USER_STATUS_ACTIVE\x10\x01\x12\x16\n" +
	"\x12USER_STATUS_FROZEN\x10\x02B6Z4sico-backend/internal/transport/http/dto/rbac/commonb\x06proto3"

var (
	file_rbac_rbac_common_proto_rawDescOnce sync.Once
	file_rbac_rbac_common_proto_rawDescData []byte
)

func file_rbac_rbac_common_proto_rawDescGZIP() []byte {
	file_rbac_rbac_common_proto_rawDescOnce.Do(func() {
		file_rbac_rbac_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rbac_rbac_common_proto_rawDesc), len(file_rbac_rbac_common_proto_rawDesc)))
	})
	return file_rbac_rbac_common_proto_rawDescData
}

var file_rbac_rbac_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rbac_rbac_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rbac_rbac_common_proto_goTypes = []any{
	(UserStatus)(0), // 0: common.UserStatus
	(*User)(nil),    // 1: common.User
}
var file_rbac_rbac_common_proto_depIdxs = []int32{
	0, // 0: common.User.status:type_name -> common.UserStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rbac_rbac_common_proto_init() }
func file_rbac_rbac_common_proto_init() {
	if File_rbac_rbac_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rbac_rbac_common_proto_rawDesc), len(file_rbac_rbac_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rbac_rbac_common_proto_goTypes,
		DependencyIndexes: file_rbac_rbac_common_proto_depIdxs,
		EnumInfos:         file_rbac_rbac_common_proto_enumTypes,
		MessageInfos:      file_rbac_rbac_common_proto_msgTypes,
	}.Build()
	File_rbac_rbac_common_proto = out.File
	file_rbac_rbac_common_proto_goTypes = nil
	file_rbac_rbac_common_proto_depIdxs = nil
}
