// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/datatypes"
)

const TableNameTTaskRuntimeBatch = "t_task_runtime_batch"

// TTaskRuntimeBatch Task runtime batch metadata
type TTaskRuntimeBatch struct {
	ID                   int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:Primary key ID" json:"id"`                              // Primary key ID
	BatchID              string         `gorm:"column:batch_id;not null;comment:Task runtime batch ID" json:"batch_id"`                                // Task runtime batch ID
	ParentConversationID int64          `gorm:"column:parent_conversation_id;not null;comment:Parent conversation ID" json:"parent_conversation_id"`   // Parent conversation ID
	ParentTurnID         int64          `gorm:"column:parent_turn_id;not null;comment:Parent turn ID" json:"parent_turn_id"`                           // Parent turn ID
	ParentToolCallID     *int64         `gorm:"column:parent_tool_call_id;comment:Parent plan tool call ID" json:"parent_tool_call_id"`                // Parent plan tool call ID
	Status               string         `gorm:"column:status;not null;default:queued;comment:Batch status" json:"status"`                              // Batch status
	Reason               string         `gorm:"column:reason;not null;comment:Delegation reason" json:"reason"`                                        // Delegation reason
	JoinStrategy         string         `gorm:"column:join_strategy;not null;default:partial_ok;comment:Batch join strategy" json:"join_strategy"`     // Batch join strategy
	TotalCount           int32          `gorm:"column:total_count;not null;comment:Number of runs in this batch" json:"total_count"`                   // Number of runs in this batch
	CountsJSON           datatypes.JSON `gorm:"column:counts_json;comment:Aggregated terminal counts" json:"counts_json"`                              // Aggregated terminal counts
	BatchJSON            datatypes.JSON `gorm:"column:batch_json;not null;comment:Full BatchRecord JSON payload" json:"batch_json"`                    // Full BatchRecord JSON payload
	CreatedAt            int64          `gorm:"column:created_at;not null;autoCreateTime:milli;comment:Create time in milliseconds" json:"created_at"` // Create time in milliseconds
	UpdatedAt            int64          `gorm:"column:updated_at;not null;autoUpdateTime:milli;comment:Update time in milliseconds" json:"updated_at"` // Update time in milliseconds
	LivenessAt           *int64         `gorm:"column:liveness_at;comment:Owner-process batch liveness heartbeat in milliseconds" json:"liveness_at"`  // Owner-process batch liveness heartbeat in milliseconds
	EndedAt              *int64         `gorm:"column:ended_at;comment:End time in milliseconds" json:"ended_at"`                                      // End time in milliseconds
	CancellationReason   string         `gorm:"column:cancellation_reason;not null;comment:Cancellation reason" json:"cancellation_reason"`            // Cancellation reason
}

// TableName TTaskRuntimeBatch's table name
func (*TTaskRuntimeBatch) TableName() string {
	return TableNameTTaskRuntimeBatch
}
