# HomePage Lowest priority
location = / {
    return 302 $scheme://$http_host/index.html;
}

location = /index.html {
    default_type text/html;
    alias /opt/linux-workstation/index.html;
}

location = /favicon.ico {
    access_log off;
    log_not_found off;
    try_files /opt/linux-workstation/favicon.ico =204;
}
