/**
 * Copyright (c) 2026 Sico Authors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import {
  Button,
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  toast,
} from "@sico/ui";
import { useNavigate } from "@tanstack/react-router";
import { Ellipsis, Trash2 } from "lucide-react";
import type * as React from "react";

import { AssetContentCard } from "./asset-content-card";
import { AssetDetailLayout } from "./asset-detail-layout";
import { AssetDetailMetaPanel } from "./asset-detail-meta-panel";
import { Markdown } from "../../../components/markdown";
import type { AssetDetail as AssetDetailData } from "../hooks/use-asset-detail-query";
import { useAssetMutation } from "../hooks/use-asset-mutation";

type ExperienceDetail = Extract<AssetDetailData, { type: "experience" }>;

export type AssetDetailExperienceProps = {
  asset: ExperienceDetail;
  /** Owning project — the back-fallback target when there's no in-app history. */
  projectId: number;
};

// The experience `…` overflow menu — Delete only (the body is read-only, so
// there's no download). A plain module-scope render helper (NOT a nested
// component) so the component body stays under the line cap.
function renderActions(onRequestDelete: () => void): React.JSX.Element {
  return (
    <DropdownMenu>
      <DropdownMenuTrigger
        render={
          <Button variant="subtle" size="icon-sm" aria-label="Asset actions" />
        }
      >
        <Ellipsis />
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={onRequestDelete}>
          <Trash2 />
          Delete
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}

// Delete the experience, then toast + navigate back to the project on success.
// Module-scope (no hooks) so the component body stays under the line cap.
function runExperienceDelete(
  remove: ReturnType<typeof useAssetMutation>["remove"],
  args: { assetId: number; projectId: number; name: string },
  navigate: ReturnType<typeof useNavigate>,
): void {
  remove.mutate(
    { id: args.assetId, type: "experience" },
    {
      onSuccess: () => {
        toast.success(`"${args.name}" was deleted.`, { invert: true });
        void navigate({
          to: "/project/$projectId",
          params: { projectId: String(args.projectId) },
        });
      },
      onError: () => {
        toast.error("We couldn't delete this. Try again.");
      },
    },
  );
}

/**
 * Experience (playbook) asset detail — a read-only Markdown body in the content
 * card on the left and the simple Detail panel on the right, inside the shared
 * {@link AssetDetailLayout}. The route's `useAssetDetailQuery` resolves the
 * playbook ROW + `/details` body together (mirrors Knowledge), so `asset`
 * already carries `createdAt` (Detail panel) and `projectId`. The authoring DW
 * name + human operator ride in `extraInfo.agentInstance` (`agentName` →
 * "Generated by", `operatorUsername` → "Operator"); each falls back to a
 * placeholder when its block is absent.
 */
export function AssetDetailExperience({
  asset,
  projectId,
}: AssetDetailExperienceProps): React.JSX.Element {
  const navigate = useNavigate();
  const { remove } = useAssetMutation(projectId);

  return (
    <AssetDetailLayout
      projectId={projectId}
      current={asset.name}
      leftBody={
        <div className="@container flex min-h-0 flex-1 flex-col px-5 pt-0 pb-4">
          <AssetContentCard>
            {/* Fluid reading gutter: px-34 at full page width (≥768px column),
                relaxing to px-4 once the column narrows so the body isn't
                crushed. Container-query on the column, not the viewport. */}
            <div className="px-4 py-11 @3xl:px-34">
              <Markdown content={asset.content} />
            </div>
          </AssetContentCard>
        </div>
      }
      rightPanel={
        <AssetDetailMetaPanel
          fileName={asset.name}
          createdAt={asset.createdAt}
          dwName={asset.extraInfo?.agentInstance?.agentName}
          operator={asset.extraInfo?.agentInstance?.operatorUsername}
        />
      }
      actions={renderActions}
      confirm={{
        title: "Delete Experience",
        body: "Permanently remove this experience across your organization.",
        onConfirm: () =>
          runExperienceDelete(
            remove,
            { assetId: asset.id, projectId, name: asset.name },
            navigate,
          ),
        pending: remove.isPending,
      }}
    />
  );
}
