/**
 * Copyright (c) 2026 Sico Authors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import { cn } from "@sico/ui/lib/utils.ts";
import type * as React from "react";

import { formatDateTime } from "../utils/format-date-time";

const LABEL_CLASS = "text-foreground-secondary leading-body text-sm";
const VALUE_CLASS = "text-foreground-primary leading-body-2";
const PLACEHOLDER = "—";

// A labelled metadata field stacked label-over-value. A missing `value` renders
// the muted em-dash placeholder (a slot the backend will fill later — e.g.
// experience Operator). The value wraps (`break-words`) so a long Operator email
// shows in full across the panel width rather than being clipped. A plain
// JSX-returning helper (NOT a component) so it neither trips `react/no-multi-comp`
// nor remounts children.
function renderField(label: string, value?: string): React.JSX.Element {
  // Treat empty/whitespace as missing too — a backend `""` should read as the
  // muted placeholder, not a blank primary-colored line.
  const hasValue = Boolean(value?.trim());
  return (
    <div className="flex min-w-0 flex-col gap-2">
      <p className={LABEL_CLASS}>{label}</p>
      <p
        className={cn(
          "break-words",
          hasValue ? VALUE_CLASS : "text-foreground-tertiary",
        )}
      >
        {hasValue ? value : PLACEHOLDER}
      </p>
    </div>
  );
}

export type AssetDetailMetaPanelProps = {
  fileName: string;
  createdAt?: number;
  /** Authoring Digital Worker's display name (`agentInstance.agentName`). */
  dwName?: string;
  /** Human user who operated the run (`creatorUsername`). */
  operator?: string;
};

/**
 * The simple "Detail" panel body (Figma 20648-49058) shared by the deliverable
 * and experience asset-detail pages: the file name, the authoring Digital Worker
 * ("Generated by …"), and a stacked Created-time / Operator pair. `Generated
 * by` is the DW; `Operator` is the human user — two distinct subjects. Fields
 * with no data render a muted placeholder rather than collapsing the layout.
 */
export function AssetDetailMetaPanel({
  fileName,
  createdAt,
  dwName,
  operator,
}: AssetDetailMetaPanelProps): React.JSX.Element {
  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-col gap-2">
        <p className={cn(VALUE_CLASS, "min-w-0 truncate font-medium")}>
          {fileName}
        </p>
        <p className={LABEL_CLASS}>
          Generated by {dwName?.trim() ? dwName : PLACEHOLDER}
        </p>
      </div>
      <div className="flex flex-col gap-6">
        {renderField(
          "Created time",
          createdAt === undefined ? undefined : formatDateTime(createdAt),
        )}
        {renderField("Operator", operator)}
      </div>
    </div>
  );
}
